<?php
header("Content-Type:   application/vnd.ms-excel; charset=utf-8");
header("Content-Disposition: attachment; filename=".$_POST['RefApplicant']."_".date('d-m-Y').".xls");  //File name extension was wrong
header("Expires: 0");
header("Cache-Control: must-revalidate, post-check=0, pre-check=0");
header("Cache-Control: private",false);
?>

	<table>
		<tr>
			<td>Language</td>
			<td><?=$_POST['Language']?></td>
		</tr>
		<tr>
			<td>NameApplicant</td>
			<td><?=$_POST['NameApplicant']?></td>
		</tr>
		<tr>
			<td>AddressApplicant</td>
			<td><?=$_POST['AddressApplicant']?></td>
		</tr>
		<tr>
			<td>CityApplicant1</td>
			<td><?=$_POST['CityApplicant1']?></td>
		</tr>
		<tr>
			<td>NameContactApplicant</td>
			<td><?=$_POST['NameContactApplicant']?></td>
		</tr>
		<tr>
			<td>TelContactApplicant</td>
			<td><?=$_POST['TelContactApplicant']?></td>
		</tr>
		<tr>
			<td>EmailContactApplicant</td>
			<td><?=$_POST['EmailContactApplicant']?></td>
		</tr>
		<tr>
			<td>RefApplicant</td>
			<td><?=$_POST['RefApplicant']?></td>
		</tr>
		<tr>
			<td>SiteDescription</td>
			<td><?=$_POST['SiteDescription']?></td>
		</tr>
		<tr>
			<td>SiteShareable</td>
			<td><?=$_POST['SiteShareable']?></td>
		</tr>
		<tr>
			<td>OtherExploitant</td>
			<td><?=$_POST['OtherExploitant']?></td>
		</tr>
		<tr>
			<td>OtherExploitant</td>
			<td><?=$_POST['OtherExploitant']?></td>
		</tr>
		<tr>
			<td>OtherExploitant</td>
			<td><?=$_POST['OtherExploitant']?></td>
		</tr>
		<tr>
			<td>OtherExploitant</td>
			<td><?=$_POST['OtherExploitant']?></td>
		</tr>
		<tr>
			<td>OtherExploitant</td>
			<td><?=$_POST['OtherExploitant']?></td>
		</tr>
		<tr>
			<td>OtherExploitant</td>
			<td><?=$_POST['OtherExploitant']?></td>
		</tr>
		<tr>
			<td>OtherExploitant</td>
			<td><?=$_POST['OtherExploitant']?></td>
		</tr>
		<tr>
			<td>OtherExploitant</td>
			<td><?=$_POST['OtherExploitant']?></td>
		</tr>
		<tr>
			<td>OwnerName</td>
			<td><?=$_POST['OwnerName']?></td>
		</tr>
		<tr>
			<td>OwnerAddress</td>
			<td><?=$_POST['OwnerAddress']?></td>
		</tr>
		<tr>
			<td>OwnerContact</td>
			<td><?=$_POST['OwnerContact']?></td>
		</tr>
		<tr>
			<td>TelContactOwner</td>
			<td><?=$_POST['TelContactOwner']?></td>
		</tr>
		<tr>
			<td>AddressSite</td>
			<td><?=$_POST['AddressSite']?></td>
		</tr>
		<tr>
			<td>DescriptionLocationSite</td>
			<td><?=$_POST['DescriptionLocationSite']?></td>
		</tr>
		<tr>
			<td>CitySite</td>
			<td><?=$_POST['CitySite']?></td>
		</tr>
		<tr>
			<td>XCoordinateSite</td>
			<td><?=$_POST['XCoordinateSite" value="<?=$longlat[0]?>']?></td>
		</tr>
		<tr>
			<td>YCoordinateSite</td>
			<td><?=$_POST['YCoordinateSite" value="<?=$longlat[1]?>']?></td>
		</tr>
		<tr>
			<td>HeightSupport</td>
			<td><?=$_POST['HeightSupport']?></td>
		</tr>
		<tr>
			<td>AntennasApplicant</td>
			<td><?=$_POST['AntennasApplicant']?></td>
		</tr>
		<tr>
			<td>AntennasThirdParties</td>
			<td><?=$_POST['AntennasThirdParties']?></td>
		</tr>
		<tr>
			<td>SiteExists</td>
			<td><?=$_POST['SiteExists']?></td>
		</tr>
		<tr>
			<td>GSM900</td>
			<td><?=$_POST['GSM90']?></td>
		</tr>
		<tr>
			<td>GSM1800</td>
			<td><?=$_POST['GSM1800']?></td>
		</tr>
		<tr>
			<td>UMTS900</td>
			<td><?=$_POST['UMTS900']?></td>
		</tr>
		<tr>
			<td>UMTS2100</td>
			<td><?=$_POST['UMTS2100']?></td>
		</tr>
		<tr>
			<td>LTE800</td>
			<td><?=$_POST['LTE800']?></td>
		</tr>
		<tr>
			<td>LTE1800</td>
			<td><?=$_POST['LTE1800']?></td>
		</tr>
		<tr>
			<td>LTE2600</td>
			<td><?=$_POST['LTE2600']?></td>
		</tr>
		<tr>
			<td>FH</td>
			<td><?=$_POST['FH']?></td>
		</tr>
		<tr>
			<td>Outside</td>
			<td><?=$_POST['Outside']?></td>
		</tr>
		<tr>
			<td>OwnerCity</td>
			<td><?=$_POST['OwnerCity']?></td>
		</tr>
		<tr>
			<td>InfoAA09</td>
			<td><?=$_POST['InfoAA09']?></td>
		</tr>
		<tr>
			<td>InfoOwnerES05</td>
			<td><?=$_POST['InfoOwnerES05']?></td>
		</tr>
		<tr>
			<td>InfoSiteLS06</td>
			<td><?=$_POST['InfoSiteLS06']?></td>
		</tr>
		<tr>
			<td>InfoAS05</td>
			<td><?=$_POST['InfoAS05']?></td>
		</tr>

		<?php
		foreach($_POST['AntennaNumberOnPlan'] as $key => $n ) {
			?>
			 <tr>
				<td>AntennaNumberOnPlan</td>
				<td><?=$_POST['AntennaNumberOnPlan'][$key]?></td>
			</tr>
			<tr>
				<td>AntennaType</td>
				<td><?=$_POST['AntennaType'][$key]?></td>
			</tr>
			<tr>
				<td>AntennaPositionHeight</td>
				<td><?=$_POST['AntennaPositionHeight'][$key]?></td>
			</tr>
			<tr>
				<td>AntennaAzimut</td>
				<td><?=$_POST['AntennaAzimut'][$key]?></td>
			</tr>
			<tr>
				<td>AntennaMechanicalTilt</td>
				<td><?=$_POST['AntennaMechanicalTilt'][$key]?></td>
			</tr>
			<tr>
				<td>AntennaEntryPowerBm</td>
				<td><?=$_POST['AntennaEntryPowerBm'][$key]?></td>
			</tr>
			<tr>
				<td>AntennaNumberOfTransmitters</td>
				<td><?=$_POST['AntennaNumberOfTransmitters'][$key]?></td>
			</tr>
			<tr>
				<td>Frequency</td>
				<td><?=$_POST['Frequency'][$key]?></td>
			</tr>
			<tr>
				<td>AntennaDescription</td>
				<td><?=$_POST['AntennaDescription'][$key]?></td>
			</tr>
			<?
		}

		?>
	</table>