<?
require_once($_SERVER['DOCUMENT_ROOT'].'/bsds/config.php');
require_once($config['phpguarddog_path']."/guard.php");
protect("","Radioplanners,BASE_MP,BASE_NPF,BSDS_view","");
require_once($config['sitepath_abs']."/bsds/PHPlibs/oci8_funcs.php");
require_once("../general_info/general_info_procedures.php");

$conn_Infobase = oci_connect($user_Infobase,$passwd_Infobase, $sid_Infobase);
$stmt = OCIParse($conn_Infobase,"ALTER SESSION SET NLS_DATE_FORMAT='DD/MM/YYYY HH24:MI:SS'");
OCIExecute($stmt,OCI_DEFAULT);

if ($_POST['action']=="addComments"){
  if (escape_sq($_POST['comments'])==''){
    $res["type"]='error';
    $res["message"]='You need to provide comments';
    echo json_encode($res);
  }else if (escape_sq($_POST['code'])==''){
    $res["type"]='error';
    $res["message"]='You need to provide a task';
    echo json_encode($res);
  }else{
    $query="INSERT INTO TASK_COMMENTS VALUES ('".$_POST['rafid']."','".$_POST['code']."','".escape_sq($_POST['comments'])."','".$guard_username."',SYSDATE,'".$_POST['status']."')";
    //echo $query."<hr>";
    $stmt = parse_exec_free($conn_Infobase, $query, $error_str);
    if (!$stmt){
      die_silently($conn_Infobase, $error_str);
    }else{
      OCICommit($conn_Infobase);
      if($_POST['status']=='General Info'){
        $res["color1"]="info";
        $res["color2"]="#FFFFFF";
      }else if($_POST['status']=='Partner General Info'){
        $res["color1"]="";
        $res["color2"]="#5bc0de";
      }else if($_POST['status']=='Blocking'){
        $res["color1"]="danger";
        $res["color2"]="#FFFFFF";
      }else if($_POST['status']=='Partner Blocking'){
        $res["color1"]="";
        $res["color2"]="#d2322d";
      }else if($_POST['status']=='Non-Blocking'){
        $res["color1"]="warning";
        $res["color2"]="#FFFFFF";
      }else if($_POST['status']=='Partner Non-Blocking'){
        $res["color1"]="";
        $res["color2"]="#f0ad4e";
      }else if($_POST['status']=='Resolved'){
        $res["color1"]="success";
        $res["color2"]="#FFFFFF";
      }else if($_POST['status']=='Partner Resolved'){
        $res["color1"]="";
        $res["color2"]="#5cb85c";
      }else{
        $res["color1"]="";
        $res["color2"]="#000000";
      }


      $res["type"]='info';
      $res["task"]=$_POST['code'];
      $res["rafid"]=$_POST['rafid'];
      $res["status"]=$_POST['status'];
      $res["comments"]=escape_sq($_POST['comments']);
      $res["message"]='Comments added to MS '.$_POST['code'].'!';
      echo json_encode($res);
    }
  }
}else if ($_POST['action']=="makeupdatable"){
  $query="UPDATE TASKS_ADMIN SET UPDATABLE=1 WHERE TASK='".$_POST['task']."'";
  //echo $query."<hr>";
  $stmt = parse_exec_free($conn_Infobase, $query, $error_str);
  if (!$stmt){
    die_silently($conn_Infobase, $error_str);
  }else{
    OCICommit($conn_Infobase);
    $res["type"]='info';
    $res["task"]=$_POST['task'];
    $res["rafid"]=$_POST['rafid'];
    $res["message"]='Task '.$_POST['task'].' has been made updatable!';
    echo json_encode($res);
  }
  
}else if ($_POST['site']!='' && $_POST['siteupgnr']!='' && $_POST['nbup']=='NB'){

	$query="DELETE FROM NET1_NEWBUILDS_2 WHERE SITENAME='".$_POST['siteupgnr']."'";
	//echo $query;
	$stmt = parse_exec_free($conn_Infobase, $query, $error_str);
	if (!$stmt) {
		die_silently($conn_Infobase, $error_str);
	}else{
		OCICommit($conn_Infobase);
	}

	$query="INSERT INTO NET1_NEWBUILDS_2(
SELECT
  SITES.SIT_ID AS SIT_ID,
  SITES.SIT_NAME AS SITE_ADDRESS,
  trunc(sysdate) AS TODAY_DATE,
  WORKS_ORDER_ELEMENTS.WOE_DOM_WES_CODE AS PREF_STATE,
  SITE_TYPE.LDE_DESC AS SITE_TYPE,
  WORKS_ORDERS_DYNAMICS.DRE_C046 AS BAND,
  WORKS_ORDERS_DYNAMICS.DRE_C011 AS DRE_V2_1,
  substr(SITES.SIT_UDK,1,3) AS REGION,
  CONCAT(WORKS_ORDERS.WOR_UDK, substr(SITES.SIT_UDK,8,1)) AS SITENAME,
  WORKS_ORDERS.WOR_NET_CODE AS BTS_TYPE,
  WORKS_ORDERS.WOR_NOTES AS COMMENTS,
  SITES.SIT_UDK AS SITENAME_2,
  to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A26',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A26,
  to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A709',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A709,
  to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A105',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A105,
  to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A50',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A50,
  to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A45',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A45,
  to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A55',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A55,
  to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A59',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A59,
  to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A61',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A61,
  to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A63',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A63,
  to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A110',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A110,
  to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A64',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A64,
  to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A91',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A91,
  to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A92',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A92,
  to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A87',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A87,
  to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A47',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A47,
  to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A84',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A84,
  to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A71',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A71,
  to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A83',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A83,
  to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A80',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A80,
  to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A301',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A301,
  to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A353',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A353,
  to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A04',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A04,
  to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A66',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A66,
  to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A285',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A285,
  to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A288',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A288,
  to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A290',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A290,
  to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A77',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A77,
  to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A76',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A76,
  to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A306',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A306,
  to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A307',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A307,
  to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A72',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A72,
  to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A81',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A81,
  to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A44',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A44,
  to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A305',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A305,
  to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A308',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A308,
  to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A71',ALL_TASKS.WOT_ESTIMATE,NULL)),'DD-MON-YYYY') AS A71_ESTIM,
  to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A308',ALL_TASKS.WOT_ESTIMATE,NULL)),'DD-MON-YYYY') AS A308_ESTIM,
  to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A306',ALL_TASKS.WOT_ESTIMATE,NULL)),'DD-MON-YYYY') AS A306_ESTIM,
  to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A307',ALL_TASKS.WOT_ESTIMATE,NULL)),'DD-MON-YYYY') AS A307_ESTIM,
  to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A22',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A22
FROM
  WORKS_ORDER_TASKS@NET1PRD  ALL_TASKS,
  SITES@NET1PRD,
  LOOKUP_DETAILS@NET1PRD  SITE_TYPE,
  WORKS_ORDER_ELEMENTS@NET1PRD,
  WORKS_ORDERS@NET1PRD,
  DYNAMIC_RECORDS@NET1PRD  WORKS_ORDERS_DYNAMICS
WHERE
  ( WORKS_ORDER_ELEMENTS.WOE_WOR_ID=WORKS_ORDERS.WOR_ID  )
  AND  ( SITES.SIT_ID=WORKS_ORDER_ELEMENTS.WOE_SIT_ID(+)  )
  AND  ( WORKS_ORDERS.WOR_LKP_WAR_CODE='ROL'  )
  AND  ( SITES.SIT_LKP_STY_CODE=SITE_TYPE.LDE_CODE(+)  )
  AND  ( SITE_TYPE.LDE_DOM_LOH_CODE='STY' OR SITE_TYPE.LDE_DOM_LOH_CODE IS NULL  )
  AND  ( WORKS_ORDERS.WOR_DRE_ID= WORKS_ORDERS_DYNAMICS.DRE_ID(+)  )
  AND  ( ALL_TASKS.WOT_TOS_TAS_CODE != 'START' AND ALL_TASKS.WOT_TOS_TAS_CODE != 'END'  )
  AND  ( ALL_TASKS.WOT_LKP_TGC_CODE IS NULL  )
  AND  ( WORKS_ORDER_ELEMENTS.WOE_WOR_ID=ALL_TASKS.WOT_WOR_ID  )
  AND  ( NVL( ALL_TASKS.WOT_SIT_ID, WORKS_ORDER_ELEMENTS.WOE_SIT_ID ) = WORKS_ORDER_ELEMENTS.WOE_SIT_ID  )
  AND  (  WORKS_ORDER_ELEMENTS.WOE_RANK  =  '1'
  AND  WORKS_ORDERS.WOR_DOM_WOS_CODE  =  'IS'
  AND  WORKS_ORDERS.WOR_NET_CODE  IN  ('BTS', 'RPT')
  )
AND (substr(SITES.SIT_UDK,1,3) LIKE '_%' OR substr(SITES.SIT_UDK,1,3) LIKE 'M%' OR substr(SITES.SIT_UDK,1,3) LIKE 'S%')
AND SITES.SIT_UDK='".$_POST['siteupgnr']."'
GROUP BY
  SITES.SIT_ID, 
  SITES.SIT_NAME, 
  trunc(sysdate), 
  WORKS_ORDER_ELEMENTS.WOE_DOM_WES_CODE, 
  SITE_TYPE.LDE_DESC, 
  WORKS_ORDERS_DYNAMICS.DRE_C046, 
  WORKS_ORDERS_DYNAMICS.DRE_C011, 
  substr(SITES.SIT_UDK,1,3), 
  CONCAT(WORKS_ORDERS.WOR_UDK, substr(SITES.SIT_UDK,8,1)), 
  WORKS_ORDERS.WOR_NET_CODE, 
  WORKS_ORDERS.WOR_NOTES, 
  SITES.SIT_UDK
HAVING
  ( 
  max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A353',ALL_TASKS.WOT_COMPLETE,NULL))  IS NOT NULL  
  AND  max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A80',ALL_TASKS.WOT_COMPLETE,NULL))  IS NULL  
  ))";
	//echo $query;
	
	$stmt = parse_exec_free($conn_Infobase, $query, $error_str);
	if (!$stmt) {
		die_silently($conn_Infobase, $error_str);
	}else{
		OCICommit($conn_Infobase);
	}

	$query="DELETE FROM NET1_ALL_NEWBUILDS4 WHERE SIT_UDK='".$_POST['siteupgnr']."' AND WOR_UDK='".$_POST['site']."'";
	//echo $query;
	$stmt = parse_exec_free($conn_Infobase, $query, $error_str);
	if (!$stmt) {
		die_silently($conn_Infobase, $error_str);
	}else{
		OCICommit($conn_Infobase);
	}

	$query="INSERT INTO NET1_ALL_NEWBUILDS4(
SELECT
SYSDATE AS IMPORT_DATE,
SITES.SIT_ID AS SIT_ID,
  WORKS_ORDERS.WOR_UDK as WOR_UDK,
  SITES.SIT_UDK as SIT_UDK,
  WORKS_ORDERS.WOR_DOM_WOS_CODE as WOR_DOM_WOS_CODE,
  WORKS_ORDER_ELEMENTS.WOE_RANK as WOE_RANK,
  WORKS_ORDERS_DYNAMICS.DRE_V2_1 AS DRE_V2_1,
  WORKS_ORDERS.WOR_NPH_CODE AS WOR_NPH_CODE,
  WORKS_ORDERS_DYNAMICS.DRE_V20_1 AS DRE_V20_1,
  SITE_TYPE.LDE_DESC AS SITE_TYPE_LDE_DESC,
SITES.SIT_LKP_SAC_CODE AS SIT_LKP_SAC_CODE,
  decode(WORKS_ORDERS_DYNAMICS.DRE_V2_1,'6','Replacement','New') AS DRE_V2_1_6,
  decode(SITES.SIT_LKP_STY_CODE,'5','INDOOR','09','INDOOR','13','INDOOR','90','INDOOR','92','INDOOR','94','INDOOR','96','INDOOR','55','INDOOR','94','INDOOR','0','MACROCELLS','10','MACROCELLS','15','MACROCELLS','20','MACROCELLS','22','MACROCELLS','25','MACROCELLS','30','MACROCELLS','35','MACROCELLS','40','MACROCELLS','45','MACROCELLS','50','MACROCELLS','55','MACROCELLS','65','MACROCELLS','66','MACROCELLS','70','MACROCELLS','75','MACROCELLS','80','MACROCELLS','85','MACROCELLS','98','MICROCELLS','MOBIL','MOBIL','GF','MACROCELLS','60','OTHER','UNDEFINED') as SIT_LKP_STY_CODE,
  WORKS_ORDERS.WOR_HSDPA_CLUSTER as WOR_HSDPA_CLUSTER,
  SITES.SIT_NAME AS SIT_NAME,
  WORKS_ORDERS.WOR_NAME  AS WOR_NAME,
  CASE
		WHEN SITES.SIT_ADDRESS_1 IS NOT NULL THEN
			SITES.SIT_ADDRESS_1||', '
		ELSE
			NULL
	END || 
	CASE
		WHEN SITES.SIT_ADDRESS_2 IS NOT NULL THEN
			SITES.SIT_ADDRESS_2||', '
		ELSE
			NULL
	END || 
	CASE
		WHEN SITES.SIT_ADDRESS_3 IS NOT NULL THEN
			SITES.SIT_ADDRESS_3||', '
		ELSE
			NULL
	END || 
	CASE
		WHEN SITES.SIT_ADDRESS_4 IS NOT NULL THEN
			SITES.SIT_ADDRESS_4||', '
		ELSE
			NULL
	END
	AS SIT_ADDRESS,
SITES.SIT_BUILDING_HEIGHT as SIT_BUILDING_HEIGHT,
SITES.SIT_POSTCODE AS POSTCODE, 
	SITES.SIT_ADDRESS_1,
  SITES.SIT_ADDRESS_2,
	SITES.SIT_ADDRESS_3,
	SITES.SIT_ADDRESS_4,
WORKS_ORDERS.WOR_NET_CODE as CLASS_CODE,
WORKS_ORDERS.WOR_LKP_WCT_CODE as WOR_LKP_WCT_CODE,
  WORK_ORDER_CATEGORY.LDE_DESC as LDE_DESC,
   substr(replace(WORKS_ORDERS.WOR_NOTES,chr(10),'<br>'), 1, 200) AS WOR_NOTES,
 SITES.SIT_X_COORDINATE AS SIT_X_COORDINATE,
    SITES.SIT_Y_COORDINATE AS SIT_Y_COORDINATE,
    WORKS_ORDERS.WOR_X_COORDINATE AS WOR_X_COORDINATE,
    WORKS_ORDERS.WOR_Y_COORDINATE AS WOR_Y_COORDINATE,
  WORKS_ORDERS.WOR_TARGET_START AS WOR_TARGET_START,
  WORKS_ORDER_ELEMENTS.WOE_LATEST_MILESTONE AS LATESTMILESTONE,
  WORKS_ORDER_ELEMENTS.WOE_LATEST_MILESTONE_TASK as WOE_LATEST_MILESTONE_TASK,
  OPERATIONS_GRADE.LDE_DESC as OPS_LDE_DESC ,
  SITES.SIT_LKP_SOG_CODE as SIT_LKP_SOG_CODE,
  SITES.SIT_LKP_SUB_CODE as SIT_LKP_SUB_CODE ,
  SITES.SIT_NOTES as SIT_NOTES,
  LOOKUP_DETAILS_PUNCH_SUB.LDE_DESC as PUNCH_LDE_DESC,
 to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A04',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A04,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A05',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A05,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A06',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A06,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A07',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A07,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A08',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A08,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A09',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A09,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A10',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A10,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A100',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A100,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A101',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A101,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A102',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A102,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A103',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A103,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A104',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A104,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A105',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A105,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A11',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A11,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A110',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A110,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A111',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A111,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A112',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A112,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A113',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A113,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A114',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A114,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A115',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A115,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A116',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A116,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A12',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A12,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A13',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A13,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A134',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A134,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A134',ALL_TASKS.WOT_ESTIMATE,NULL)),'DD-MON-YYYY') AS A134_ESTIM,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A14',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A14,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A141',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A141,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A15',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A15,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A16',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A16,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A17',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A17,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A18',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A18,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A19',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A19,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A196',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A196,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A1961',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A1961,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A197',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A197,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A1971',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A1971,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A199',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A199,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A20',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A20,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A200',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A200,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A205',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A205,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A21',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A21,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A210',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A210,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A211',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A211,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A212',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A212,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A215',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A215,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A22',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A22,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A220',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A220,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A225',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A225,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A23',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A23,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A230',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A230,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A235',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A235,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A237',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A237,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A239',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A239,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A24',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A24,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A240',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A240,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A25',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A25,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A250',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A250,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A255',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A255,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A26',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A26,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A260',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A260,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A27',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A27,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A270',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A270,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A270',ALL_TASKS.WOT_ESTIMATE,NULL)),'DD-MON-YYYY') AS A270_ESTIM,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A275',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A275,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A28',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A28,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A280',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A280,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A285',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A285,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A288',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A288,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A29',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A29,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A290',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A290,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A291',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A291,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A30',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A30,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A300',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A300,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A301',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A301,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A304',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A304,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A305',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A305,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A306',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A306,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A307',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A307,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A307',ALL_TASKS.WOT_ESTIMATE,NULL)),'DD-MON-YYYY') AS A307_ESTIM,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A308',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A308,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A309',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A309,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A31',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A31,
to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A319',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A319,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A32',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A32,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A33',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A33,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A34',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A34,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A35',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A35,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A352',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A352,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A353',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A353,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A354',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A354,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A36',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A36,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A361',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A361,
		to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A366',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A366,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A37',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A37,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A38',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A38,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A39',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A39,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A40',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A40,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A407',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A407,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A408',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A408,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A409',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A409,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A41',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A41,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A42',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A42,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A43',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A43,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A44',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A44,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A45',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A45,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A45',ALL_TASKS.WOT_ESTIMATE,NULL)),'DD-MON-YYYY') AS A45_ESTIM,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A46',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A46,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A47',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A47,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A48',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A48,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A49',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A49,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A50',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A50,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A501',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A501,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A502',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A502,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A503',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A503,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A504',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A504,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A505',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A505,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A506',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A506,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A507',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A507,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A51',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A51,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A52',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A52,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A53',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A53,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A54',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A54,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A55',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A55,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A56',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A56,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A57',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A57,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A58',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A58,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A59',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A59,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A60',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A60,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A61',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A61,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A62',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A62,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A63',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A63,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A63',ALL_TASKS.WOT_ESTIMATE,NULL)),'DD-MON-YYYY') AS A63_ESTIM,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A64',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A64,
 to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A64',ALL_TASKS.WOT_ESTIMATE,NULL)),'DD-MON-YYYY') AS A64_ESTIM,    
to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A65',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A65,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A66',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A66,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A67',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A67,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A68',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A68,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A680',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A680,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A69',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A69,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A70',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A70,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A709',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A709,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A71',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A71,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A71',ALL_TASKS.WOT_ESTIMATE,NULL)),'DD-MON-YYYY') AS A71_ESTIM,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A710',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A710,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A711',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A711,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A712',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A712,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A712',ALL_TASKS.WOT_ESTIMATE,NULL)),'DD-MON-YYYY') AS A712_ESTIM,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A72',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A72,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A73',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A73,
to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A733',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A733,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A74',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A74,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A75',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A75,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A76',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A76,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A77',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A77,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A77',ALL_TASKS.WOT_ESTIMATE,NULL)),'DD-MON-YYYY') AS A77_ESTIM,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A78',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A78,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A79',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A79,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A80',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A80,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A80',ALL_TASKS.WOT_ESTIMATE,NULL)),'DD-MON-YYYY') AS A80_ESTIM,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A800',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A800,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A801',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A801,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A81',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A81,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A826',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A826,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A83',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A83,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A83',ALL_TASKS.WOT_ESTIMATE,NULL)),'DD-MON-YYYY') AS A83_ESTIM,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A84',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A84,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A85',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A85,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A86',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A86,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A87',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A87,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A88',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A88,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A89',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A89,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A90',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A90,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A901',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A901,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A902',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A902,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A903',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A903,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A904',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A904,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A904',ALL_TASKS.WOT_ESTIMATE,NULL)),'DD-MON-YYYY') AS A904_ESTIM,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A905',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A905,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A907',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A907,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A908',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A908,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A909',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A909,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A91',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A91,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A91',ALL_TASKS.WOT_ESTIMATE,NULL)),'DD-MON-YYYY') AS A91_ESTIM,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A92',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A92,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A93',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A93,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A94',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A94,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A96',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A96,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A97',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A97,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A98',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A98,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A99',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A99,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A998',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A998,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'CNP',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS CNP,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'REBP',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS REBP,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'STAC',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS STAC,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'STBP',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS STBP,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'STCI',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS STCI,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'STER',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS STER,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'STRF',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS STRF,
    to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'STTR',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS STTR,
  to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A361',ALL_TASKS.WOT_ESTIMATE,NULL)),'DD-MON-YYYY') AS A361_ESTIM,
to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A0772',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A0772,
to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A0773',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A0773,
to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A1972',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A1972,
to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A1973',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A1973,
to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A1974',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A1974,
to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A1975',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A1975,
to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A1976',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A1976,
to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A1977',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A1977,
to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A2501',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A2501,
to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A3051',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A3051,
to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A310',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A310,
to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A310',ALL_TASKS.WOT_ESTIMATE,NULL)),'DD-MON-YYYY') AS A310_ESTIM,
to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A356',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A356,
to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A508',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A508,
to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A715',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A715,
to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A720',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A720,
to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A725',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A725,
to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A726',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A726,
to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A728',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A728,
to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A745',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A745,
to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A82',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A82,
to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A86',ALL_TASKS.WOT_ESTIMATE,NULL)),'DD-MON-YYYY') AS A86_ESTIM,
to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A95',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A95,
to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A729',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A729,
to_char(max(decode(ALL_TASKS.WOT_TOS_TAS_CODE,'A2502',ALL_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS A2502
FROM
WORKS_ORDER_TASKS@NET1PRD  ALL_TASKS,
  SITES@NET1PRD,
  LOOKUP_DETAILS@NET1PRD  SITE_TYPE,
  LOOKUP_DETAILS@NET1PRD  WORK_ORDER_CATEGORY,
  LOOKUP_DETAILS@NET1PRD  OPERATIONS_GRADE,
  LOOKUP_DETAILS@NET1PRD  LOOKUP_DETAILS_PUNCH_SUB,
  WORKS_ORDER_ELEMENTS@NET1PRD,
  WORKS_ORDERS@NET1PRD,
  DYNAMIC_RECORDS_LEGACY@NET1PRD  WORKS_ORDERS_DYNAMICS
WHERE
  ( WORKS_ORDER_ELEMENTS.WOE_WOR_ID=WORKS_ORDERS.WOR_ID  )
  AND  ( SITES.SIT_ID=WORKS_ORDER_ELEMENTS.WOE_SIT_ID(+)  )
  AND  ( OPERATIONS_GRADE.LDE_CODE(+)=SITES.SIT_LKP_SOG_CODE  )
  AND  ( OPERATIONS_GRADE.LDE_DOM_LOH_CODE='SOG' OR OPERATIONS_GRADE.LDE_DOM_LOH_CODE IS NULL  )
  AND  ( WORKS_ORDERS.WOR_LKP_WAR_CODE='ROL'  )
  AND  ( WORKS_ORDERS.WOR_LKP_WCT_CODE=WORK_ORDER_CATEGORY.LDE_CODE(+)  )
  AND  ( WORK_ORDER_CATEGORY.LDE_DOM_LOH_CODE='WCT' OR WORK_ORDER_CATEGORY.LDE_DOM_LOH_CODE IS NULL  )
  AND  ( SITES.SIT_LKP_STY_CODE=SITE_TYPE.LDE_CODE(+)  )
  AND  ( SITE_TYPE.LDE_DOM_LOH_CODE='STY' OR SITE_TYPE.LDE_DOM_LOH_CODE IS NULL  )
  AND  ( WORKS_ORDERS.WOR_DRE_ID= WORKS_ORDERS_DYNAMICS.DRE_ID(+)  )
  AND  ( ALL_TASKS.WOT_TOS_TAS_CODE != 'START' AND ALL_TASKS.WOT_TOS_TAS_CODE != 'END'  )
  AND  ( ALL_TASKS.WOT_LKP_TGC_CODE IS NULL  )
  AND  ( WORKS_ORDER_ELEMENTS.WOE_WOR_ID=ALL_TASKS.WOT_WOR_ID  )
  AND  ( NVL( ALL_TASKS.WOT_SIT_ID, WORKS_ORDER_ELEMENTS.WOE_SIT_ID ) = WORKS_ORDER_ELEMENTS.WOE_SIT_ID  )
  AND  ( SITES.SIT_LKP_SUB_CODE=LOOKUP_DETAILS_PUNCH_SUB.LDE_CODE(+)  )
  AND  ( LOOKUP_DETAILS_PUNCH_SUB.LDE_DOM_LOH_CODE(+)='SUB'
  )
	AND SIT_UDK='".$_POST['siteupgnr']."' 
	AND WOR_UDK='".$_POST['site']."'
GROUP BY
SYSDATE,
SITES.SIT_ID,
  WORKS_ORDERS.WOR_UDK, 
  SITES.SIT_UDK, 
  WORKS_ORDERS.WOR_DOM_WOS_CODE, 
  WORKS_ORDER_ELEMENTS.WOE_RANK, 
  WORKS_ORDERS_DYNAMICS.DRE_V2_1, 
  WORKS_ORDERS.WOR_NPH_CODE, 
  WORKS_ORDERS_DYNAMICS.DRE_V20_1, 
  SITE_TYPE.LDE_DESC, 
SITES.SIT_LKP_SAC_CODE,
  decode(WORKS_ORDERS_DYNAMICS.DRE_V2_1,'6','Replacement','New'), 
  decode(SITES.SIT_LKP_STY_CODE,'5','INDOOR','09','INDOOR','13','INDOOR','90','INDOOR','92','INDOOR','94','INDOOR','96','INDOOR','55','INDOOR','94','INDOOR','0','MACROCELLS','10','MACROCELLS','15','MACROCELLS','20','MACROCELLS','22','MACROCELLS','25','MACROCELLS','30','MACROCELLS','35','MACROCELLS','40','MACROCELLS','45','MACROCELLS','50','MACROCELLS','55','MACROCELLS','65','MACROCELLS','66','MACROCELLS','70','MACROCELLS','75','MACROCELLS','80','MACROCELLS','85','MACROCELLS','98','MICROCELLS','MOBIL','MOBIL','GF','MACROCELLS','60','OTHER','UNDEFINED'), 
  WORKS_ORDERS.WOR_HSDPA_CLUSTER, 
  SITES.SIT_NAME, 
  WORKS_ORDERS.WOR_NAME, 
SITES.SIT_BUILDING_HEIGHT,
CASE
		WHEN SITES.SIT_ADDRESS_1 IS NOT NULL THEN
			SITES.SIT_ADDRESS_1||', '
		ELSE
			NULL
	END || 
	CASE
		WHEN SITES.SIT_ADDRESS_2 IS NOT NULL THEN
			SITES.SIT_ADDRESS_2||', '
		ELSE
			NULL
	END || 
	CASE
		WHEN SITES.SIT_ADDRESS_3 IS NOT NULL THEN
			SITES.SIT_ADDRESS_3||', '
		ELSE
			NULL
	END || 
	CASE
		WHEN SITES.SIT_ADDRESS_4 IS NOT NULL THEN
			SITES.SIT_ADDRESS_4||', '
		ELSE
			NULL
	END,
SITES.SIT_POSTCODE, 
	SITES.SIT_ADDRESS_1,
  SITES.SIT_ADDRESS_2,
	SITES.SIT_ADDRESS_3,
	SITES.SIT_ADDRESS_4,  
WORKS_ORDERS.WOR_NET_CODE,
WORKS_ORDERS.WOR_LKP_WCT_CODE, 
  WORK_ORDER_CATEGORY.LDE_DESC, 
  WORKS_ORDERS.WOR_NOTES, 
  SITES.SIT_X_COORDINATE, 
  SITES.SIT_Y_COORDINATE, 
  WORKS_ORDERS.WOR_X_COORDINATE, 
  WORKS_ORDERS.WOR_Y_COORDINATE, 
  WORKS_ORDERS.WOR_TARGET_START, 
  WORKS_ORDER_ELEMENTS.WOE_LATEST_MILESTONE, 
  to_char(WORKS_ORDER_ELEMENTS.WOE_LATEST_MILESTONE), 
  WORKS_ORDER_ELEMENTS.WOE_LATEST_MILESTONE_TASK, 
  OPERATIONS_GRADE.LDE_DESC, 
  SITES.SIT_LKP_SOG_CODE, 
  SITES.SIT_LKP_SUB_CODE, 
  SITES.SIT_LKP_STY_CODE, 
  SITES.SIT_ADDRESS_4, 
  SITES.SIT_NOTES, 
  SITES.SIT_LKP_SUB_CODE, 
  SITES.SIT_POSTCODE, 
  LOOKUP_DETAILS_PUNCH_SUB.LDE_DESC
	)";
	//echo $query;

	$stmt = parse_exec_free($conn_Infobase, $query, $error_str);
	if (!$stmt) {
		die_silently($conn_Infobase, $error_str);
	}else{
		OCICommit($conn_Infobase);
	}

	echo "NET1 explorer and BSDS NET1 data has been refreshed!";

}else if ($_POST['site']!='' && $_POST['siteupgnr']!='' && $_POST['nbup']=='UPG'){
	
	$query="DELETE FROM NET1_ALL_UPGRADES1 WHERE WOR_UDK='".$_POST['siteupgnr']."' AND SIT_UDK='".$_POST['site']."'";
	//echo $query;
	$stmt = parse_exec_free($conn_Infobase, $query, $error_str);
	if (!$stmt) {
		die_silently($conn_Infobase, $error_str);
	}else{
		OCICommit($conn_Infobase);
	}

	$query="INSERT INTO NET1_ALL_UPGRADES1(
SELECT
SYSDATE AS IMPORT_DATE,
  SITES.SIT_UDK AS SIT_UDK,
  WORKS_ORDERS.WOR_LKP_WCO_CODE AS WOR_LKP_WCO_CODE,
  SITES.SIT_LKP_STY_CODE AS SIT_LKP_STY_CODE,
  WORKS_ORDERS.WOR_UDK AS WOR_UDK,
  WORKS_ORDERS.WOR_NPH_CODE AS WOR_NPH_CODE,
  WORKS_ORDERS.WOR_NAME AS WOR_NAME,
  WORKS_ORDERS.WOR_NET_CODE AS CLASS_CODE,
  WORKS_ORDERS.WOR_HSDPA_CLUSTER AS WOR_HSDPA_CLUSTER,
  WORKS_ORDERS.WOR_DOM_WOS_CODE AS WOR_DOM_WOS_CODE,
  WORKS_ORDER_ELEMENTS.WOE_DOM_WES_CODE AS WOE_DOM_WES_CODE,
 WORKS_ORDERS.WOR_NOTES,
max(replace(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U001',SITE_TASKS.WOT_Notes,NULL),chr(10),'<br>')) AS U001_NOTES,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U001',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U001,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U002',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U002,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U003',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U003,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U004',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U004,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U005',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U005,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U006',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U006,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U007',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U007,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U009',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U009,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U010',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U010,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U011',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U011,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U014',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U014,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U015',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U015,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U072',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U072,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U0726',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U0726,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U0729',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U0729,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U073',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U073,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U0734',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U0734,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U0735',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U0735,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U074',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U074,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U075',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U075,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U076',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U076,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U0761',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U0761,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U077',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U077,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U0771',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U0771,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U0772',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U0772,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U0773',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U0773, 
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U0774',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U0774,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U0775',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U0775,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U0776',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U0776,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'UO777',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U0777,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U100',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U100,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U101',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U101,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U102',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U102,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U103',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U103,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U104',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U104,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U105',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U105,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U106',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U106,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U107',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U107,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U108',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U108,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U109',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U109,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U110',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U110,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U120',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U120,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U130',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U130,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U134',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U134,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U134',SITE_TASKS.WOT_ESTIMATE,NULL)),'DD-MON-YYYY') AS U134_ESTIM,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U135',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U135,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U141',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U141,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U162',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U162,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U164',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U164,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U166',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U166,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U170',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U170,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U180',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U180,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U190',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U190,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U200',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U200,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U210',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U210,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U220',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U220,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U240',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U240,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U260',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U260,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U270',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U270,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U270',SITE_TASKS.WOT_ESTIMATE,NULL)),'DD-MON-YYYY') AS U270_ESTIM,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U281',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U281,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U282',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U282,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U283',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U283,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U300',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U300,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U301',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U301,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U304',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U304,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U305',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U305,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U3051',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U3051,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U306',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U306,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U307',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U307,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U307',SITE_TASKS.WOT_ESTIMATE,NULL)),'DD-MON-YYYY') AS U307_ESTIM,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U308',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U308,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U309',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U309,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U310',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U310,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U317',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U317,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U318',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U318,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U322',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U322,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U323',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U323,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U323',SITE_TASKS.WOT_ESTIMATE,NULL)),'DD-MON-YYYY') AS U323_ESTIM,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U324',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U324,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U325',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U325,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U326',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U326,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U327',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U327,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U328',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U328,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U329',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U329,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U329',SITE_TASKS.WOT_ESTIMATE,NULL)),'DD-MON-YYYY') AS U329_ESTIM,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U330',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U330,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U331',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U331,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U332',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U332,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U334',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U334,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U335',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U335,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U337',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U337,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U339',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U339,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U340',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U340,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U341',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U341,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U343',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U343,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U345',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U345,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U345',SITE_TASKS.WOT_ESTIMATE,NULL)),'DD-MON-YYYY') AS U345_ESTIM,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U348',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U348,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U349',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U349,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U352',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U352,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U353',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U353,
 CONCAT(max(replace(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U353',SITE_TASKS.WOT_Notes,NULL),chr(10),'<br>')),'|') AS U353_NOTES,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U354',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U354,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U355',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U355,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U356',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U356,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U361',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U361,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U361',SITE_TASKS.WOT_ESTIMATE,NULL)),'DD-MON-YYYY') AS U361_ESTIM,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U363',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U363,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U363',SITE_TASKS.WOT_ESTIMATE,NULL)),'DD-MON-YYYY') AS U363_ESTIM,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U364',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U364,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U364',SITE_TASKS.WOT_ESTIMATE,NULL)),'DD-MON-YYYY') AS U364_ESTIM,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U365',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U365,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U366',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U366,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U367',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U367,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U368',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U368,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U369',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U369,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U377',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U377,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U377',SITE_TASKS.WOT_ESTIMATE,NULL)),'DD-MON-YYYY') AS U377_ESTIM,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U380',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U380,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U380',SITE_TASKS.WOT_ESTIMATE,NULL)),'DD-MON-YYYY') AS U380_ESTIM,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U381',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U381,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U382',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U382,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U383',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U383,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U383',SITE_TASKS.WOT_ESTIMATE,NULL)),'DD-MON-YYYY') AS U383_ESTIM,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U386',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U386,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U386',SITE_TASKS.WOT_ESTIMATE,NULL)),'DD-MON-YYYY') AS U386_ESTIM,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U387',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U387,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U388',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U388,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U391',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U391,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U391',SITE_TASKS.WOT_ESTIMATE,NULL)),'DD-MON-YYYY') AS U391_ESTIM,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U392',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U392,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U393',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U393,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U394',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U394,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U395',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U395,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U400',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U400,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U401',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U401,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U402',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U402,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U403',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U403,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U404',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U404,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U405',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U405,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U407',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U407,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U408',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U408,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U409',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U409,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U411',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U411,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U412',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U412,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U413',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U413,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U414',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U414,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U415',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U415,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U416',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U416,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U417',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U417,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U418',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U418,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U430',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U430,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U433',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U433,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U434',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U434,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U440',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U440,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U441',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U441,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U442',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U442,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U446',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U446,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U450',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U450,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U451',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U451,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U452',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U452,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U453',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U453,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U454',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U454,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U459',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U459,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U460',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U460,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U461',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U461,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U465',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U465,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U466',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U466,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U467',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U467,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U479',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U479,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U481',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U481,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U484',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U484,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U501',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U501,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U502',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U502,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U503',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U503,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U504',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U504,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U505',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U505,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U506',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U506,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U507',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U507,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U508',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U508,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U516',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U516,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U518',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U518,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U529',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U529,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U557',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U557,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U558',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U558,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U571',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U571,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U571',SITE_TASKS.WOT_ESTIMATE,NULL)),'DD-MON-YYYY') AS U571_ESTIM,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U572',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U572,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U574',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U574,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U588',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U588,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U589',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U589,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U670',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U670,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U680',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U680,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U701',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U701,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U707',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U707,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U708',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U708,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U709',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U709,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U710',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U710,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U711',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U711,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U712',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U712,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U712',SITE_TASKS.WOT_ESTIMATE,NULL)),'DD-MON-YYYY') AS U712_ESTIM,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U715',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U715,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U720',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U720,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U723',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U723,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U725',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U725,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U726',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U726,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U733',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U733,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U734',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U734,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U735',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U735,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U736',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U736,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U745',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U745,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U800',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U800,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U801',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U801,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U802',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U802,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U825',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U825,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U826',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U826,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U901',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U901,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U902',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U902,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U903',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U903,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U904',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U904,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U904',SITE_TASKS.WOT_ESTIMATE,NULL)),'DD-MON-YYYY') AS U904_ESTIM,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U905',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U905,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U906',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U906,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U907',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U907,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U908',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U908,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U998',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U998,
max(replace(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U998',SITE_TASKS.WOT_Notes,NULL),chr(10),'<br>')) AS U998_NOTES,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U999',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U999,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U487',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U487,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U729',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U729,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U0040',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U0040,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U0042',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U0042,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U0030',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U0030,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U0031',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U0031,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U0032',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U0032,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U0033',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U0033,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U0034',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U0034,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U0035',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U0035,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U0036',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U0036,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U0037',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U0037,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U0038',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U0038,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U0039',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U0039,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U0044',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U0044,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U0045',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U0045,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U0021',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U0021,
to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U0023',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U0023

FROM
  WORKS_ORDER_TASKS@NET1PRD  SITE_TASKS,
  SITES@NET1PRD,
  WORKS_ORDER_ELEMENTS@NET1PRD,
  WORKS_ORDERS@NET1PRD
WHERE
  ( WORKS_ORDER_ELEMENTS.WOE_WOR_ID=WORKS_ORDERS.WOR_ID  )
  AND  ( SITE_TASKS.WOT_LKP_WOL_CODE='SIT'  )
  AND  ( SITE_TASKS.WOT_TOS_TAS_CODE != 'START' AND SITE_TASKS.WOT_TOS_TAS_CODE != 'END'  )
  AND  ( SITE_TASKS.WOT_LKP_TGC_CODE IS NULL  )
  AND  ( SITES.SIT_ID=WORKS_ORDER_ELEMENTS.WOE_SIT_ID  )
  AND  ( SITE_TASKS.WOT_SIT_ID=WORKS_ORDER_ELEMENTS.WOE_SIT_ID and SITE_TASKS.WOT_WOR_ID=WORKS_ORDER_ELEMENTS.WOE_WOR_ID  )
  AND  ( WORKS_ORDERS.WOR_LKP_WAR_CODE='NEM'  )
 AND SIT_UDK='".$_POST['site']."'
AND WOR_UDK='".$_POST['siteupgnr']."'
GROUP BY
SYSDATE,
  SITES.SIT_UDK, 
  WORKS_ORDERS.WOR_LKP_WCO_CODE, 
  SITES.SIT_LKP_STY_CODE, 
  WORKS_ORDERS.WOR_UDK, 
  WORKS_ORDERS.WOR_NPH_CODE, 
  WORKS_ORDERS.WOR_NAME, 
  WORKS_ORDERS.WOR_HSDPA_CLUSTER,
WORKS_ORDERS.WOR_NET_CODE, 
  WORKS_ORDERS.WOR_DOM_WOS_CODE, 
WORKS_ORDERS.WOR_NOTES, 
  ( WORKS_ORDER_ELEMENTS.WOE_DOM_WES_CODE ))";
	$stmt = parse_exec_free($conn_Infobase, $query, $error_str);
	if (!$stmt) {
		die_silently($conn_Infobase, $error_str);
	}else{
		OCICommit($conn_Infobase);
	}


	$query="DELETE FROM NET1_UPGRADES_2 WHERE WOR_UDK='".$_POST['siteupgnr']."' AND SITE_ID='".$_POST['site']."'";
	//echo $query;
	
	$stmt = parse_exec_free($conn_Infobase, $query, $error_str);
	if (!$stmt) {
		die_silently($conn_Infobase, $error_str);
	}else{
		OCICommit($conn_Infobase);
	}


	$query="INSERT INTO NET1_UPGRADES_2(
SELECT
 WORKS_ORDERS.WOR_UDK AS WOR_UDK,
  SITES.SIT_UDK AS SITE_ID,
  WORKS_ORDERS.WOR_LKP_WCO_CODE AS BAND,
  SITES.SIT_NAME AS SITE_TYPE,
  trunc(sysdate) AS RUN_DATE,
  trim(WORKS_ORDERS.WOR_NOTES) AS COMMENTS,
  SITE_TYPE.LDE_DESC AS SITE_DESC,
  WORKS_ORDERS.WOR_NAME AS WOR_NAME,
  to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U001',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U001,
  to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U326',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U326,
  to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U709',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U709,
  to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U334',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U334,
  to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U405',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U405,
  to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U349',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U349,
  to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U345',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U345,
  to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U355',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U355,
  to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U459',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U459,
  to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U391',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U391,
  to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U392',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U392,
  to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U074',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U074,
  to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U383',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U383,
  to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U075',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U075,
  to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U381',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U381,
  to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U327',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U327,
  to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U328',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U328,
  to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U341',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U341,
  to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U348',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U348,
  to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U363',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U363,
  to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U366',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U366,
  to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U364',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U364,
  to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U574',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U574,
  to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U332',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U332,
  to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U380',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U380,
  to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U825',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U825,
  to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U301',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U301,
  to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U353',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U353,
  max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U001',SITE_TASKS.WOT_Notes,NULL)) AS U001_NOTES,
  to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U440',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U440,
  to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U467',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U467,
  to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U481',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U481,
  to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U368',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U368,
  to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U461',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U461,
  max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U461',SITE_TASKS.WOT_Notes,NULL)) AS U461_COM ,
  to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U999',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U999,
  to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U306',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U306,
  to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U307',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U307,
  to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U418',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U418,
  to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U571',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U571,
  to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U305',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U305,
  to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U308',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U308,
  to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U571',SITE_TASKS.WOT_ESTIMATE,NULL)),'DD-MON-YYYY') AS U571_ESTIM,
  to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U308',SITE_TASKS.WOT_ESTIMATE,NULL)),'DD-MON-YYYY') AS U308_ESTIM,
  to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U306',SITE_TASKS.WOT_ESTIMATE,NULL)),'DD-MON-YYYY') AS U306_ESTIM,
  to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U307',SITE_TASKS.WOT_ESTIMATE,NULL)),'DD-MON-YYYY') AS U307_ESTIM,
  to_char(max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U322',SITE_TASKS.WOT_COMPLETE,NULL)),'DD-MON-YYYY') AS U322
FROM
  WORKS_ORDER_TASKS@NET1PRD  SITE_TASKS,
  SITES@NET1PRD,
  LOOKUP_DETAILS@NET1PRD  SITE_TYPE,
  WORKS_ORDER_ELEMENTS@NET1PRD,
  WORKS_ORDERS@NET1PRD
WHERE
  ( WORKS_ORDER_ELEMENTS.WOE_WOR_ID=WORKS_ORDERS.WOR_ID  )
  AND  ( SITE_TASKS.WOT_LKP_WOL_CODE='SIT'  )
  AND  ( SITE_TASKS.WOT_TOS_TAS_CODE != 'START' AND SITE_TASKS.WOT_TOS_TAS_CODE != 'END'  )
  AND  ( SITE_TASKS.WOT_LKP_TGC_CODE IS NULL  )
  AND  ( SITES.SIT_ID=WORKS_ORDER_ELEMENTS.WOE_SIT_ID  )
  AND  ( SITE_TASKS.WOT_SIT_ID=WORKS_ORDER_ELEMENTS.WOE_SIT_ID and SITE_TASKS.WOT_WOR_ID=WORKS_ORDER_ELEMENTS.WOE_WOR_ID  )
  AND  ( WORKS_ORDERS.WOR_LKP_WAR_CODE='NEM'  )
  AND  ( SITE_TYPE.LDE_DOM_LOH_CODE='STY' OR SITE_TYPE.LDE_DOM_LOH_CODE IS NULL  )
  AND  ( SITES.SIT_LKP_STY_CODE=SITE_TYPE.LDE_CODE  )
  AND  (
  WORKS_ORDERS.WOR_LKP_WCO_CODE  IN  ('ANT', 'ASC', 'CAB', 'DCS', 'EG6', 'EGS', 'UMTS', 'UMT6', 'HSDPA', 'HSPX', 'SWAP','IND','ANT','MSH','LTE','LTEX','DISM','MOV')
  AND  WORKS_ORDERS.WOR_DOM_WOS_CODE  IN  ('IS')
  )
 AND SIT_UDK='".$_POST['site']."'
AND WOR_UDK='".$_POST['siteupgnr']."'
GROUP BY
  WORKS_ORDERS.WOR_UDK, 
  SITES.SIT_UDK, 
  WORKS_ORDERS.WOR_LKP_WCO_CODE, 
  SITES.SIT_NAME, 
  trunc(sysdate), 
  WORKS_ORDERS.WOR_NOTES, 
  SITE_TYPE.LDE_DESC, 
  WORKS_ORDERS.WOR_NAME
HAVING
  ( 
  max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U380',SITE_TASKS.WOT_COMPLETE,NULL))  IS NULL  
  AND max(decode(SITE_TASKS.WOT_TOS_TAS_CODE,'U353',SITE_TASKS.WOT_COMPLETE,NULL))  IS NOT NULL  
  ))";
	//echo $query;

	$stmt = parse_exec_free($conn_Infobase, $query, $error_str);
	if (!$stmt) {
		die_silently($conn_Infobase, $error_str);
	}else{
		OCICommit($conn_Infobase);
	}

	echo "NET1 explorer and BSDS NET1 data has been refreshed!";
}
