DELETE FROM BSDS_PLANNED_GEN_GSM900
WHERE ROWID IN (
SELECT t.ROWID AS targetrowid
FROM BSDS_PLANNED_GEN_GSM900 t,
(SELECT BSDSKEY, MAX (ROWID) AS maxrowid
FROM BSDS_PLANNED_GEN_GSM900
GROUP BY BSDSKEY
HAVING COUNT (*) > 1) m
WHERE t.ROWID != m.maxrowid AND t.BSDSKEY = m.BSDSKEY)