<?php
include_once($_SERVER['DOCUMENT_ROOT'].'/bsds/config.php');
require_once($config['sitepath_abs']."/bsds/PHPlibs/oci8_funcs.php");
require_once('raf_procedures.php');

$conn_Infobase = oci_connect($user_Infobase,$passwd_Infobase, $sid_Infobase);
$stmt = OCIParse($conn_Infobase,"ALTER SESSION SET nls_date_format='DD/MM/YYYY HH24:MI:SS'");
OCIExecute($stmt,OCI_DEFAULT);

require_once '/var/www/html/infobase/plugins/phpExcel/Classes/PHPExcel.php';
require_once '/var/www/html/infobase/plugins/phpExcel/Classes/PHPExcel/IOFactory.php';

// Create new PHPExcel object
$objPHPExcel = new PHPExcel();

// Set properties
$objPHPExcel->getProperties()->setCreator("Infobase")
							 ->setLastModifiedBy("Frederick Eyland")
							 ->setTitle("RAF REPORT")
							 ->setSubject("RAF report")
							 ->setDescription("RAF report generated by Infobase base on selected filters.")
							 ->setKeywords("rafreport")
							 ->setCategory("Reporting");

$objPHPExcel->getActiveSheet()->getRowDimension('1')->setRowHeight(70);

$objDrawing = new PHPExcel_Worksheet_Drawing();
$objDrawing->setName('PHPExcel logo');
$objDrawing->setDescription('KPNGroup logo');
$objDrawing->setPath('/var/www/html/infobase/files/infobase/images/KPNGroupBelgium+5brands.gif');
$objDrawing->setHeight(70);
$objDrawing->setCoordinates('A1');
$objDrawing->setOffsetX(10);
$objDrawing->setOffsetY(10);
$objDrawing->setWorksheet($objPHPExcel->getActiveSheet());


$objDrawing = new PHPExcel_Worksheet_Drawing();
$objDrawing->setName('PHPExcel logo');
$objDrawing->setDescription('KPNGroup logo');
$objDrawing->setPath('/var/www/html/infobase/files/infobase/images/logo_infobase.png');
$objDrawing->setCoordinates('Z1');
$objDrawing->setOffsetY(10);
$objDrawing->setWorksheet($objPHPExcel->getActiveSheet());


$objPHPExcel->getActiveSheet()->mergeCells('E1:Y1');
			$objPHPExcel->setActiveSheetIndex(0)->setCellValue('E1', 'RAF REPORT ('.$_GET['actionby'].') LEAD TIMES GENERATED ON '.date('d-m-Y H:i:s'));
			$objPHPExcel->getActiveSheet()->getStyle('E1')->getFont()->setSize(20);
			-
$objPHPExcel->setActiveSheetIndex(0)
	->setCellValue('A3', 'RAF ID')
	->setCellValue('B3', 'REGION')
	->setCellValue('C3', 'SITEID')
	->setCellValue('D3', 'TYPE')
	->setCellValue('E3', 'OTHER INPUT')
	->setCellValue('F3', 'OTHER INPUT DATE')
	->setCellValue('G3', 'RF INPUT')
	->setCellValue('H3', 'RF INPUT DATE')
	->setCellValue('I3', 'TX INPUT')
	->setCellValue('J3', 'TX INPUT DATE')
	->setCellValue('K3', 'NET1 LINK')
	->setCellValue('L3', 'NET1 LINK DATE')
	->setCellValue('M3', 'ALU INPUT')
	->setCellValue('N3', 'ALU INPUT DATE')
	->setCellValue('O3', 'BCS STATUS')
	->setCellValue('P3', 'BCS STATUS DATE')
	->setCellValue('Q3', 'LS&BP OK')
	->setCellValue('R3', 'ALU ACQUIRED')
	->setCellValue('S3', 'ALU ACQUIRED DATE')
	->setCellValue('T3', 'TX ACQUIRED')
	->setCellValue('U3', 'TX ACQUIRED DATE')
	->setCellValue('V3', 'RAF AQUIRED')
	->setCellValue('W3', 'FUND SITE')
	->setCellValue('X3', 'FUND SITE DATE')
	->setCellValue('Y3', 'PO for Construction')
	->setCellValue('Z3', 'FUNDING DATE')
	->setCellValue('AA3', 'ALU PAC')
	->setCellValue('AB3', 'ALU PAC DATE')
	->setCellValue('AC3', 'RF PAC')
	->setCellValue('AD3', 'RF PAC DATE')
	->setCellValue('AE3', 'PAC DATE')
	->setCellValue('AF3', 'ACTION BY')
	->setCellValue('AG3', 'BAND')
	->setCellValue('AH3', 'RFINFO')
	->setCellValue('AI3', 'SAC')
	->setCellValue('AJ3', 'CON')
	->setCellValue('AK3', 'STATUS')
	->setCellValue('AL3', 'PO for Acquisition')
	->setCellValue('AM3', 'Physical start')
	->setCellValue('AN3', 'Site Integrated')
	->setCellValue('AO3', 'Vendor GSM900')
	->setCellValue('AP3', 'Vendor GSM1800')
	->setCellValue('AQ3', 'Vendor 3G UMTS2100')
	->setCellValue('AR3', 'Vendor 3G UMTS900')
	->setCellValue('AS3', 'BAND GSM900')
	->setCellValue('AT3', 'BAND GSM1800')
	->setCellValue('AU3', 'BAND UMTS2100')
	->setCellValue('AU3', 'BAND UMTS900');

$styleArray = array(
	'font' => array(
		'bold' => true,
	),
	'alignment' => array(
		'horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_LEFT,
	),
	'borders' => array(
		'bottom' => array(
			'style' => PHPExcel_Style_Border::BORDER_THICK,
		),
	),
	'fill' => array(
		'type' => PHPExcel_Style_Fill::FILL_GRADIENT_LINEAR,
		'rotation' => 90,
		'startcolor' => array(
			'argb' => 'FFA0A0A0',
		),
		'endcolor' => array(
			'argb' => 'FFFFFFFF',
		),
	),
	);

$objPHPExcel->getActiveSheet()->getStyle('A3:AV3')->applyFromArray($styleArray);



$query=create_query($_GET['site_key'],$_GET['region'],$_GET['type'],$_GET['actionby'],$_GET['orderby'],$_GET['order'],"","",$_GET['phase'],$_GET['allocated']);
//echo $query."<br>";

$stmt = parse_exec_fetch($conn_Infobase, $query, $error_str, $res1);
if (!$stmt) {
	die_silently($conn_Infobase, $error_str);
 	exit;
} else {
	OCIFreeStatement($stmt);
	$amount_of_RAFS=count($res1['SITEID']);
}
//echo $amount_of_RAFS;

$styleArray_orange = array(
'alignment' => array(
	'horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_LEFT,
),
'fill' => array(
	'type' => PHPExcel_Style_Fill::FILL_SOLID,
	'color' => array(
		'argb' => 'FFFFFF00',
	)
),
);



$styleArray_green = array(
'alignment' => array(
	'horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_LEFT,
),
'fill' => array(
	'type' => PHPExcel_Style_Fill::FILL_SOLID,
	'color' => array(
		'argb' => 'FF00FF00',
	)
),
);


$output_raf="";
if ($amount_of_RAFS>=1){
	$row=4;
	for ($i = 0; $i <$amount_of_RAFS; $i++) {

		$TXMN_INP_SEL="";
		$NET1_CREATED_SEL="";
		$PARTNER_INP_SEL="";
		$RADIO_ACC_SEL="";
		$TXMN_ACC_SEL="";
		$status="";


		if ($res1['TYPE'][$i]=="New Indoor" || $res1['TYPE'][$i]=="Indoor Upgrade"  || $res1['TYPE'][$i]=="IND Upgrade"){
			$raf_type="indoor";
		}else{
			$raf_type="outdoor";
		}

		include('raf_color_analysis.php');

		$band="";
		$query2 = "select * FROM BSDS_RAF_RADIO WHERE RAFID='".$res1['RAFID'][$i]."'";
		//echo "<br><br>".$query1;
		$stmt2 = parse_exec_fetch($conn_Infobase, $query2, $error_str, $res2);
		if (!$stmt2) {
			die_silently($conn_Infobase, $error_str);
		 	exit;
		} else {
			OCIFreeStatement($stmt2);
			if($res2['BAND_900'][0]==1){
				$band.="GSM900 ";
				$vendor_2G_GSM900=$res2['VENDOR2G_GSM900'][0];
			}
			if($res2['BAND_1800'][0]==1){
				$band.="GSM1800 ";
				$vendor_2G_GSM1800=$res2['VENDOR2G_GSM1800'][0];
			}
			if($res2['BAND_UMTS'][0]==1){
				$band.="UMTS ";
				$vendor_3G=$res2['VENDOR3G_UMTS'][0];
			}
			if($res2['BAND_UMTS900'][0]==1){
							$band.="UMTS ";
							$vendor_3G=$res2['VENDOR3G_UMTS900'][0];
			}
		}


		if ($val1=="selected_RAF"){
			$letter="E";
		}else if ($val2=="selected_RAF"){
			$letter="F";
		}else if ($val3=="selected_RAF"){
			$letter="G";
		}else if ($val4=="selected_RAF"){
			$letter="H";
		}else if ($val5=="selected_RAF"){
			$letter="I";
		}else if ($val6=="selected_RAF"){
			$letter="J";
		}else if ($val7=="selected_RAF"){
			$letter="K";
		}else if ($val14=="selected_RAF"){
			$letter="L";
		}else if ($val15=="selected_RAF"){
			$letter="M";
		}else if ($val8=="selected_RAF"){
			$letter="N";
		}else if ($val9=="selected_RAF"){
			$letter="O";
		}else if ($val10=="selected_RAF"){
			$letter="Q";
		}else if ($val11=="selected_RAF"){
			$letter="R";
		}else if ($val12=="selected_RAF"){
			$letter="S";
		}else if ($val13=="selected_RAF"){
			$letter="T";
		}

		if ($status=="RAF ASBUILD"){
			$objPHPExcel->getActiveSheet()->getStyle('A'.$row.':AV'.$row)->applyFromArray($styleArray_green);
		}else{
			$objPHPExcel->getActiveSheet()->getStyle($letter.$row)->applyFromArray($styleArray_orange);
		}



		$objPHPExcel->setActiveSheetIndex(0)
		            ->setCellValue("A".$row, $res1['RAFID'][$i])
					->setCellValue("B".$row, substr($res1['SITEID'][$i],0,2))
					->setCellValue("C".$row, substr($res1['SITEID'][$i],2))
					->setCellValue("D".$row, $res1['TYPE'][$i]." ".$res1['CANDIDATE'][$i])
					->setCellValue("E".$row, $res1['OTHER_INP'][$i])
					->setCellValue("F".$row, $res1['OTHER_INP_DATE'][$i])
					->setCellValue("G".$row, $res1['RADIO_INP'][$i])
					->setCellValue("H".$row, $res1['RADIO_INP_DATE'][$i])
					->setCellValue("I".$row, $res1['TXMN_INP'][$i])
					->setCellValue("J".$row, $res1['TXMN_INP_DATE'][$i])
					->setCellValue("K".$row, $res1['NET1_LINK'][$i])
					->setCellValue("L".$row, $res1['NET1_LINK_DATE'][$i])
					->setCellValue("M".$row, $res1['ALU_INP'][$i])
					->setCellValue("N".$row, $res1['ALU_INP_DATE'][$i])
					->setCellValue("O".$row, $res1['BCS_NET1'][$i])
					->setCellValue("P".$row, $res1['BCS_NET1_DATE'][$i])
					->setCellValue("Q".$row, $res1['NET1_LBP'][$i])
					->setCellValue("R".$row, $res1['ALU_ACQUIRED'][$i])
					->setCellValue("S".$row, $res1['ALU_ACQUIRED_DATE'][$i])
					->setCellValue("T".$row, $res1['TXMN_ACQUIRED'][$i])
					->setCellValue("U".$row, $res1['TXMN_ACQUIRED_DATE'][$i])
					->setCellValue("V".$row, $res1['NET1_AQUIRED'][$i])
					->setCellValue("W".$row, $res1['STATUS_FUND'][$i])
					->setCellValue("X".$row, $res1['STATUS_FUND_DATE'][$i])
					->setCellValue("Y".$row, $res1['UA503'][$i])
					->setCellValue("AA".$row, $res1['NET1_FUND'][$i])
					->setCellValue("AB".$row, $res1['PAC_STATUS'][$i])
					->setCellValue("AC".$row, $res1['PAC_STATUS_DATE'][$i])
					->setCellValue("AD".$row, $res1['RF_PAC'][$i])
					->setCellValue("AE".$row, $res1['RF_PAC_DATE'][$i])
					->setCellValue("AF".$row, $res1['NET1_PAC'][$i])
					->setCellValue("AG".$row, $status." ".$status_special)
					->setCellValue("AH".$row, $band)
					->setCellValue("AI".$row, $res1['RFINFO'][$i])
					->setCellValue("AI".$row, $res1['SAC'][$i])
					->setCellValue("AJ".$row, $res1['CON'][$i])
					->setCellValue("AK".$row, $res1['STATUS'][$i])
					->setCellValue("AL".$row, $res1['UA501'][$i])
					->setCellValue("AM".$row, $res1['U459A59'][$i])
					->setCellValue("AN".$row, $res1['U571A71'][$i])
					->setCellValue("AO".$row, $vendor_2G_GSM900)
					->setCellValue("AP".$row, $vendor_2G_GSM1800)
					->setCellValue("AQ".$row, $VENDOR3G_UMTS)
					->setCellValue("AR".$row, $VENDOR3G_UMTS900)
					->setCellValue("AS".$row, $res2['BAND_900'][0])
					->setCellValue("AT".$row, $res2['BAND_1800'][0])
					->setCellValue("AU".$row, $res2['BAND_UMTS'][0])
					->setCellValue("AV".$row, $res2['BAND_UMTS900'][0]);


		$row++;
		$letter="";
		$status_special="";
		$vendor_2G_GSM900="";
		$vendor_2G_GSM1800="";
		$vendor_3G="";
		$band_900="";
		$band_1800="";
		$band_UMTS="";

	}
}else{
	echo "NO RAF data found!";
}


$objPHPExcel->getActiveSheet()->getStyle('U4:U'.$row)->applyFromArray($styleArray_orange);
/*
$objPHPExcel->getActiveSheet()->getStyle('T4:T1500')->applyFromArray($style_BorderVerticallines);

$objPHPExcel->getActiveSheet()->setAutoFilter('A3:AV3');


$style_BorderVerticallines = array(
			'borders' => array(
				'vertical' => array(
					'style' => PHPExcel_Style_Border::BORDER_THIN,
					'color' => array('argb' => '00000000'),
				),
			),
		);

$objPHPExcel->getActiveSheet()->getStyle('A3:AV'.$row)->applyFromArray($style_BorderVerticallines);
*/
$objPHPExcel->getActiveSheet()->setTitle('RAF report LEAD TIMES');
$objPHPExcel->setActiveSheetIndex(0);

if ($filtetype=="html"){
	echo __FILE__;

	$objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'HTML');
	$objWriter->setSheetIndex(0);
	$objWriter->setImagesRoot('/var/www/html/infobase/files/infobase/images/');
	$objWriter->save('/var/www/html/bash_scripts/Temp/raf_report_'.$_GET['actionby'].'.html');
}else{
// Redirect output to a client’s web browser (Excel2007)
header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
header('Content-Disposition: attachment;filename="raf_report_'.$_GET['actionby'].'.xlsx"');
header('Cache-Control: max-age=0');

$objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel2007');
$objWriter->save('php://output');
exit;
}
