<?php
include_once($_SERVER['DOCUMENT_ROOT'].'/bsds/config.php');
require_once($config['sitepath_abs']."/bsds/PHPlibs/oci8_funcs.php");
require_once('raf_procedures.php');

$conn_Infobase = oci_connect($user_Infobase,$passwd_Infobase, $sid_Infobase);
$stmt = OCIParse($conn_Infobase,"ALTER SESSION SET nls_date_format='DD/MM/YYYY HH24:MI:SS'");
OCIExecute($stmt,OCI_DEFAULT);

require_once '/var/www/html/infobase/plugins/phpExcel/Classes/PHPExcel.php';
require_once '/var/www/html/infobase/plugins/phpExcel/Classes/PHPExcel/IOFactory.php';

// Create new PHPExcel object
$objPHPExcel = new PHPExcel();

// Set properties
$objPHPExcel->getProperties()->setCreator("Infobase")
							 ->setLastModifiedBy("Frederick Eyland")
							 ->setTitle("RAF REPORT XLS EXTENDED")
							 ->setSubject("RAF report xls extended")
							 ->setDescription("RAF report generated by Infobase base on selected filters.")
							 ->setKeywords("rafreport")
							 ->setCategory("Reporting");

$objPHPExcel->getActiveSheet()->getRowDimension('1')->setRowHeight(70);

$objDrawing = new PHPExcel_Worksheet_Drawing();
$objDrawing->setName('PHPExcel logo');
$objDrawing->setDescription('KPNGroup logo');
$objDrawing->setPath('/var/www/html/infobase/files/infobase/images/KPNGroupBelgium+5brands.gif');
$objDrawing->setHeight(70);
$objDrawing->setCoordinates('A1');
$objDrawing->setOffsetX(10);
$objDrawing->setOffsetY(10);
$objDrawing->setWorksheet($objPHPExcel->getActiveSheet());


$objDrawing = new PHPExcel_Worksheet_Drawing();
$objDrawing->setName('PHPExcel logo');
$objDrawing->setDescription('KPNGroup logo');
$objDrawing->setPath('/var/www/html/infobase/files/infobase/images/logo_infobase.png');
$objDrawing->setCoordinates('Z1');
$objDrawing->setOffsetY(10);
$objDrawing->setWorksheet($objPHPExcel->getActiveSheet());


$objPHPExcel->getActiveSheet()->mergeCells('E1:Y1');
			$objPHPExcel->setActiveSheetIndex(0)->setCellValue('E1', 'RAF TXMN REPORT ('.$_GET['actionby'].') GENERATED ON '.date('d-m-Y H:i:s'));
			$objPHPExcel->getActiveSheet()->getStyle('E1')->getFont()->setSize(20);
			-
$objPHPExcel->setActiveSheetIndex(0)
	->setCellValue('A3', 'RAF ID')
	->setCellValue('B3', 'REGION')
	->setCellValue('C3', 'SITEID')
	->setCellValue('D3', 'TYPE')
	->setCellValue('E3', 'OTHER INPUT')
	->setCellValue('F3', 'RF INPUT')
	->setCellValue('G3', 'TX INPUT')
	->setCellValue('H3', 'NET1 LINK')
	->setCellValue('I3', 'PARTNER INPUT')
	->setCellValue('J3', 'BCS STATUS')
	->setCellValue('K3', 'LS&BP OK')
	->setCellValue('L3', 'PARTNER ACQUIRED')
	->setCellValue('M3', 'TX ACQUIRED')
	->setCellValue('N3', 'RAF AQUIRED')
	->setCellValue('O3', 'FUND SITE')
	->setCellValue('P3', 'PO for Construction')
	->setCellValue('Q3', 'FUNDING DATE')
	->setCellValue('R3', 'PARTNER PAC')
	->setCellValue('S3', 'RF PAC')
	->setCellValue('T3', 'PAC DATE')
	->setCellValue('U3', 'ACTION BY')
	->setCellValue('V3', 'BAND')
	->setCellValue('W3', 'RFINFO')
	->setCellValue('X3', 'SAC')
	->setCellValue('Y3', 'CON')
	->setCellValue('Z3', 'STATUS')
	->setCellValue('AA3', 'PO for Acquisition')
	->setCellValue('AB3', 'Physical start')
	->setCellValue('AC3', 'Site Integrated')
	->setCellValue('AD3', 'Vendor GSM900')
	->setCellValue('AE3', 'Vendor GSM1800')
	->setCellValue('AF3', 'Vendor 3G')
	->setCellValue('AG3', 'BAND GSM900')
	->setCellValue('AH3', 'BAND GSM1800')
	->setCellValue('AI3', 'BAND UMTS')
	->setCellValue('AJ3', 'UPG_DATE')
	->setCellValue('AK3', 'UPG_BY')
	->setCellValue('AL3', 'GRANTED_BEARING1')
	->setCellValue('AM3', 'GRANTED_BEARING2')
	->setCellValue('AN3', 'GRANTED_BEARING3')
	->setCellValue('AO3', 'GRANTED_BEARING4')
	->setCellValue('AP3', 'GRANTED_BEARING5')
	->setCellValue('AQ3', 'GRANTED_BEARING6')
	->setCellValue('AR3', 'GRANTED_BEARING7')
	->setCellValue('AS3', 'GRANTED_BEARING8')
	->setCellValue('AT3', 'GRANTED_BEARING9')
	->setCellValue('AU3', 'GRANTED_BEARING10')
	->setCellValue('AV3', 'GRANTED_BEARING11')
	->setCellValue('AW3', 'GRANTED_BEARING12')
	->setCellValue('AX3', 'GRANTED_DIAMETER1')
	->setCellValue('AY3', 'GRANTED_DIAMETER2')
	->setCellValue('AZ3', 'GRANTED_DIAMETER3')
	->setCellValue('BA3', 'GRANTED_DIAMETER4')
	->setCellValue('BB3', 'GRANTED_DIAMETER5')
	->setCellValue('BC3', 'GRANTED_DIAMETER6')
	->setCellValue('BD3', 'GRANTED_DIAMETER7')
	->setCellValue('BE3', 'GRANTED_DIAMETER8')
	->setCellValue('BF3', 'GRANTED_DIAMETER9')
	->setCellValue('BG3', 'GRANTED_DIAMETER10')
	->setCellValue('BH3', 'GRANTED_DIAMETER11')
	->setCellValue('BI3', 'GRANTED_DIAMETER12')
	->setCellValue('BJ3', 'ADDITIONAL_BEARING1')
	->setCellValue('BK3', 'ADDITIONAL_BEARING2')
	->setCellValue('BL3', 'ADDITIONAL_BEARING3')
	->setCellValue('BM3', 'ADDITIONAL_BEARING4')
	->setCellValue('BN3', 'ADDITIONAL_BEARING5')
	->setCellValue('BO3', 'ADDITIONAL_BEARING6')
	->setCellValue('BP3', 'ADDITIONAL_BEARING7')
	->setCellValue('BQ3', 'ADDITIONAL_BEARING8')
	->setCellValue('BR3', 'ADDITIONAL_BEARING9')
	->setCellValue('BS3', 'ADDITIONAL_BEARING10')
	->setCellValue('BT3', 'ADDITIONAL_BEARING11')
	->setCellValue('BU3', 'ADDITIONAL_BEARING12')
	->setCellValue('BV3', 'ADDITIONAL_DIAMETER1')
	->setCellValue('BW3', 'ADDITIONAL_DIAMETER2')
	->setCellValue('BX3', 'ADDITIONAL_DIAMETER3')
	->setCellValue('BY3', 'ADDITIONAL_DIAMETER4')
	->setCellValue('BZ3', 'ADDITIONAL_DIAMETER5')
	->setCellValue('CA3', 'ADDITIONAL_DIAMETER6')
	->setCellValue('CB3', 'ADDITIONAL_DIAMETER7')
	->setCellValue('CD3', 'ADDITIONAL_DIAMETER8')
	->setCellValue('CE3', 'ADDITIONAL_DIAMETER9')
	->setCellValue('CF3', 'ADDITIONAL_DIAMETER10')
	->setCellValue('CG3', 'ADDITIONAL_DIAMETER11')
	->setCellValue('CI3', 'ADDITIONAL_DIAMETER12')
	->setCellValue('CX3', 'GRANTED_HEIGHT1')
	->setCellValue('CY3', 'GRANTED_HEIGHT2')
	->setCellValue('CZ3', 'GRANTED_HEIGHT3')
	->setCellValue('CA3', 'GRANTED_HEIGHT4')
	->setCellValue('CB3', 'GRANTED_HEIGHT5')
	->setCellValue('CC3', 'GRANTED_HEIGHT6')
	->setCellValue('CD3', 'GRANTED_HEIGHT7')
	->setCellValue('CE3', 'GRANTED_HEIGHT8')
	->setCellValue('CF3', 'GRANTED_HEIGHT9')
	->setCellValue('CG3', 'GRANTED_HEIGHT10')
	->setCellValue('CH3', 'GRANTED_HEIGHT11')
	->setCellValue('CI3', 'GRANTED_HEIGHT12')
	->setCellValue('CJ3', 'ADDITIONAL_HEIGHT1')
	->setCellValue('CK3', 'ADDITIONAL_HEIGHT2')
	->setCellValue('CL3', 'ADDITIONAL_HEIGHT3')
	->setCellValue('CM3', 'ADDITIONAL_HEIGHT4')
	->setCellValue('CN3', 'ADDITIONAL_HEIGHT5')
	->setCellValue('CO3', 'ADDITIONAL_HEIGHT6')
	->setCellValue('CP3', 'ADDITIONAL_HEIGHT7')
	->setCellValue('CQ3', 'ADDITIONAL_HEIGHT8')
	->setCellValue('CR3', 'ADDITIONAL_HEIGHT9')
	->setCellValue('CS3', 'ADDITIONAL_HEIGHT10')
	->setCellValue('CT3', 'ADDITIONAL_HEIGHT11')
	->setCellValue('CU3', 'ADDITIONAL_HEIGHT12')
	->setCellValue('CV3', 'EXISTING_CAB1')
	->setCellValue('CW3', 'EXISTING_AMOUNT1')
	->setCellValue('CX3', 'EXISTING_CAB2')
	->setCellValue('CY3', 'EXISTING_AMOUNT2')
	->setCellValue('CZ3', 'ADDITIONAL_CAB1')
	->setCellValue('DA3', 'ADDITIONAL_AMOUNT1')
	->setCellValue('DB3', 'ADDITIONAL_CAB2')
	->setCellValue('DC3', 'ADDITIONAL_AMOUNT2')
	->setCellValue('DD3', 'SPECIFIC_TXMN')
	->setCellValue('DE3', 'HMIN')
	->setCellValue('DF3', 'HMINDISH')
	->setCellValue('DG3', 'TXMNGUIDES')
	->setCellValue('DH3', 'BUDGET');

$styleArray = array(
	'font' => array(
		'bold' => true,
	),
	'alignment' => array(
		'horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_LEFT,
	),
	'borders' => array(
		'bottom' => array(
			'style' => PHPExcel_Style_Border::BORDER_THICK,
		),
	),
	'fill' => array(
		'type' => PHPExcel_Style_Fill::FILL_GRADIENT_LINEAR,
		'rotation' => 90,
		'startcolor' => array(
			'argb' => 'FFA0A0A0',
		),
		'endcolor' => array(
			'argb' => 'FFFFFFFF',
		),
	),
	);

$objPHPExcel->getActiveSheet()->getStyle('A3:AI3')->applyFromArray($styleArray);



$query=create_query($_GET['site_key'],$_GET['region'],$_GET['type'],$_GET['actionby'],$_GET['orderby'],$_GET['order'],"","",$_GET['phase'],$_GET['allocated']);
$query=str_replace("BSDS_RAF","BSDS_RAF a LEFT JOIN BSDS_RAF_TXMN b ON a.RAFID=b.RAFID",$query);
//echo $query."<br>";
//die;
$stmt = parse_exec_fetch($conn_Infobase, $query, $error_str, $res1);
if (!$stmt) {
	die_silently($conn_Infobase, $error_str);
 	exit;
} else {
	OCIFreeStatement($stmt);
	$amount_of_RAFS=count($res1['SITEID']);
}
//echo $amount_of_RAFS;

$styleArray_orange = array(
'alignment' => array(
	'horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_LEFT,
),
'fill' => array(
	'type' => PHPExcel_Style_Fill::FILL_SOLID,
	'color' => array(
		'argb' => 'FFFFFF00',
	)
),
);

$styleArray_green = array(
'alignment' => array(
	'horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_LEFT,
),
'fill' => array(
	'type' => PHPExcel_Style_Fill::FILL_SOLID,
	'color' => array(
		'argb' => 'FF00FF00',
	)
),
);

$output_raf="";
if ($amount_of_RAFS>=1){
	$row=4;
	for ($i = 0; $i <$amount_of_RAFS; $i++) {

		$TXMN_INP_SEL="";
		$NET1_CREATED_SEL="";
		$PARTNER_INP_SEL="";
		$RADIO_ACC_SEL="";
		$TXMN_ACC_SEL="";
		$status="";


		if ($res1['TYPE'][$i]=="New Indoor" || $res1['TYPE'][$i]=="Indoor Upgrade"  || $res1['TYPE'][$i]=="IND Upgrade"){
			$raf_type="indoor";
		}else{
			$raf_type="outdoor";
		}

		include('raf_color_analysis.php');

		$band="";
		$query2 = "select * FROM BSDS_RAF_RADIO WHERE RAFID='".$res1['RAFID'][$i]."'";
		//echo "<br><br>".$query1;
		$stmt2 = parse_exec_fetch($conn_Infobase, $query2, $error_str, $res2);
		if (!$stmt2) {
			die_silently($conn_Infobase, $error_str);
		 	exit;
		} else {
			OCIFreeStatement($stmt2);
			if($res2['BAND_900'][0]==1){
				$band.="GSM900 ";
				$vendor_2G_GSM900=$res2['VENDOR2G_GSM900'][0];
			}
			if($res2['BAND_1800'][0]==1){
				$band.="GSM1800 ";
				$vendor_2G_GSM1800=$res2['VENDOR2G_GSM1800'][0];
			}
			if($res2['BAND_UMTS'][0]==1){
				$band.="UMTS ";
				$vendor_3G=$res2['VENDOR3G'][0];
			}
		}


		if ($val1=="selected_RAF"){
			$letter="E";
		}else if ($val2=="selected_RAF"){
			$letter="F";
		}else if ($val3=="selected_RAF"){
			$letter="G";
		}else if ($val4=="selected_RAF"){
			$letter="H";
		}else if ($val5=="selected_RAF"){
			$letter="I";
		}else if ($val6=="selected_RAF"){
			$letter="J";
		}else if ($val7=="selected_RAF"){
			$letter="K";
		}else if ($val14=="selected_RAF"){
			$letter="L";
		}else if ($val15=="selected_RAF"){
			$letter="M";
		}else if ($val8=="selected_RAF"){
			$letter="N";
		}else if ($val9=="selected_RAF"){
			$letter="O";
		}else if ($val10=="selected_RAF"){
			$letter="Q";
		}else if ($val11=="selected_RAF"){
			$letter="R";
		}else if ($val12=="selected_RAF"){
			$letter="S";
		}else if ($val13=="selected_RAF"){
			$letter="T";
		}

		if ($status=="RAF ASBUILD"){
			$objPHPExcel->getActiveSheet()->getStyle('A'.$row.':AC'.$row)->applyFromArray($styleArray_green);
		}else{
			$objPHPExcel->getActiveSheet()->getStyle($letter.$row)->applyFromArray($styleArray_orange);
		}



		$objPHPExcel->setActiveSheetIndex(0)
		            ->setCellValue("A".$row, $res1['RAFID'][$i])
					->setCellValue("B".$row, substr($res1['SITEID'][$i],0,2))
					->setCellValue("C".$row, substr($res1['SITEID'][$i],2))
					->setCellValue("D".$row, $res1['TYPE'][$i]." ".$res1['CANDIDATE'][$i])
					->setCellValue("E".$row, $res1['OTHER_INP'][$i])
					->setCellValue("F".$row, $res1['RADIO_INP'][$i])
					->setCellValue("G".$row, $res1['TXMN_INP'][$i])
					->setCellValue("H".$row, $res1['NET1_LINK'][$i])
					->setCellValue("I".$row, $res1['ALU_INP'][$i])
					->setCellValue("J".$row, $res1['BCS_NET1'][$i])
					->setCellValue("K".$row, $res1['NET1_LBP'][$i])
					->setCellValue("L".$row, $res1['ALU_ACQUIRED'][$i])
					->setCellValue("M".$row, $res1['TXMN_ACQUIRED'][$i])
					->setCellValue("N".$row, $res1['NET1_AQUIRED'][$i])
					->setCellValue("O".$row, $res1['STATUS_FUND'][$i])
					->setCellValue("P".$row, $res1['UA503'][$i])
					->setCellValue("Q".$row, $res1['NET1_FUND'][$i])
					->setCellValue("R".$row, $res1['PAC_STATUS'][$i])
					->setCellValue("S".$row, $res1['RF_PAC'][$i])
					->setCellValue("T".$row, $res1['NET1_PAC'][$i])
					->setCellValue("U".$row, $status." ".$status_special)
					->setCellValue("V".$row, $band)
					->setCellValue("W".$row, $res1['RFINFO'][$i])
					->setCellValue("X".$row, $res1['SAC'][$i])
					->setCellValue("Y".$row, $res1['CON'][$i])
					->setCellValue("Z".$row, $res1['STATUS'][$i])
					->setCellValue("AA".$row, $res1['UA501'][$i])
					->setCellValue("AB".$row, $res1['U459A59'][$i])
					->setCellValue("AC".$row, $res1['U571A71'][$i])
					->setCellValue("AD".$row, $vendor_2G_GSM900)
					->setCellValue("AE".$row, $vendor_2G_GSM1800)
					->setCellValue("AF".$row, $vendor_3G)
					->setCellValue("AG".$row, $res2['BAND_900'][0])
					->setCellValue("AH".$row, $res2['BAND_1800'][0])
					->setCellValue("AI".$row, $res2['BAND_UMTS'][0])
					->setCellValue('AJ3'.$row, $res1['UPG_DATE'][$i])
					->setCellValue('AK3'.$row, $res1['UPG_BY'][$i])
					->setCellValue('AL3'.$row, $res1['GRANTED_BEARING1'][$i])
					->setCellValue('AM3'.$row, $res1['GRANTED_BEARING2'][$i])
					->setCellValue('AN3'.$row, $res1['GRANTED_BEARING3'][$i])
					->setCellValue('AO3'.$row, $res1['GRANTED_BEARING4'][$i])
					->setCellValue('AP3'.$row, $res1['GRANTED_BEARING5'][$i])
					->setCellValue('AQ3'.$row, $res1['GRANTED_BEARING6'][$i])
					->setCellValue('AR3'.$row, $res1['GRANTED_BEARING7'][$i])
					->setCellValue('AS3'.$row, $res1['GRANTED_BEARING8'][$i])
					->setCellValue('AT3'.$row, $res1['GRANTED_BEARING9'][$i])
					->setCellValue('AU3'.$row, $res1['GRANTED_BEARING10'][$i])
					->setCellValue('AV3'.$row, $res1['GRANTED_BEARING11'][$i])
					->setCellValue('AW3'.$row, $res1['GRANTED_BEARING12'][$i])
					->setCellValue('AX3'.$row, $res1['GRANTED_DIAMETER1'][$i])
					->setCellValue('AY3'.$row, $res1['GRANTED_DIAMETER2'][$i])
					->setCellValue('AZ3'.$row, $res1['GRANTED_DIAMETER3'][$i])
					->setCellValue('BA3'.$row, $res1['GRANTED_DIAMETER4'][$i])
					->setCellValue('BB3'.$row, $res1['GRANTED_DIAMETER5'][$i])
					->setCellValue('BC3'.$row, $res1['GRANTED_DIAMETER6'][$i])
					->setCellValue('BD3'.$row, $res1['GRANTED_DIAMETER7'][$i])
					->setCellValue('BE3'.$row, $res1['GRANTED_DIAMETER8'][$i])
					->setCellValue('BF3'.$row, $res1['GRANTED_DIAMETER9'][$i])
					->setCellValue('BG3'.$row, $res1['GRANTED_DIAMETER10'][$i])
					->setCellValue('BH3'.$row, $res1['GRANTED_DIAMETER11'][$i])
					->setCellValue('BI3'.$row, $res1['GRANTED_DIAMETER12'][$i])
					->setCellValue('BJ3'.$row, $res1['ADDITIONAL_BEARING1'][$i])
					->setCellValue('BK3'.$row, $res1['ADDITIONAL_BEARING2'][$i])
					->setCellValue('BL3'.$row, $res1['ADDITIONAL_BEARING3'][$i])
					->setCellValue('BM3'.$row, $res1['ADDITIONAL_BEARING4'][$i])
					->setCellValue('BN3'.$row, $res1['ADDITIONAL_BEARING5'][$i])
					->setCellValue('BO3'.$row, $res1['ADDITIONAL_BEARING6'][$i])
					->setCellValue('BP3'.$row, $res1['ADDITIONAL_BEARING7'][$i])
					->setCellValue('BQ3'.$row, $res1['ADDITIONAL_BEARING8'][$i])
					->setCellValue('BR3'.$row, $res1['ADDITIONAL_BEARING9'][$i])
					->setCellValue('BS3'.$row, $res1['ADDITIONAL_BEARING10'][$i])
					->setCellValue('BT3'.$row, $res1['ADDITIONAL_BEARING11'][$i])
					->setCellValue('BU3'.$row, $res1['ADDITIONAL_BEARING12'][$i])
					->setCellValue('BV3'.$row, $res1['ADDITIONAL_DIAMETER1'][$i])
					->setCellValue('BW3'.$row, $res1['ADDITIONAL_DIAMETER2'][$i])
					->setCellValue('BX3'.$row, $res1['ADDITIONAL_DIAMETER3'][$i])
					->setCellValue('BY3'.$row, $res1['ADDITIONAL_DIAMETER4'][$i])
					->setCellValue('BZ3'.$row, $res1['ADDITIONAL_DIAMETER5'][$i])
					->setCellValue('CA3'.$row, $res1['ADDITIONAL_DIAMETER6'][$i])
					->setCellValue('CB3'.$row, $res1['ADDITIONAL_DIAMETER7'][$i])
					->setCellValue('CD3'.$row, $res1['ADDITIONAL_DIAMETER8'][$i])
					->setCellValue('CE3'.$row, $res1['ADDITIONAL_DIAMETER9'][$i])
					->setCellValue('CF3'.$row, $res1['ADDITIONAL_DIAMETER10'][$i])
					->setCellValue('CG3'.$row, $res1['ADDITIONAL_DIAMETER11'][$i])
					->setCellValue('CI3'.$row, $res1['ADDITIONAL_DIAMETER12'][$i])
					->setCellValue('CX3'.$row, $res1['GRANTED_HEIGHT1'][$i])
					->setCellValue('CY3'.$row, $res1['GRANTED_HEIGHT2'][$i])
					->setCellValue('CZ3'.$row, $res1['GRANTED_HEIGHT3'][$i])
					->setCellValue('CA3'.$row, $res1['GRANTED_HEIGHT4'][$i])
					->setCellValue('CB3'.$row, $res1['GRANTED_HEIGHT5'][$i])
					->setCellValue('CC3'.$row, $res1['GRANTED_HEIGHT6'][$i])
					->setCellValue('CD3'.$row, $res1['GRANTED_HEIGHT7'][$i])
					->setCellValue('CE3'.$row, $res1['GRANTED_HEIGHT8'][$i])
					->setCellValue('CF3'.$row, $res1['GRANTED_HEIGHT9'][$i])
					->setCellValue('CG3'.$row, $res1['GRANTED_HEIGHT10'][$i])
					->setCellValue('CH3'.$row, $res1['GRANTED_HEIGHT11'][$i])
					->setCellValue('CI3'.$row, $res1['GRANTED_HEIGHT12'][$i])
					->setCellValue('CJ3'.$row, $res1['ADDITIONAL_HEIGHT1'][$i])
					->setCellValue('CK3'.$row, $res1['ADDITIONAL_HEIGHT2'][$i])
					->setCellValue('CL3'.$row, $res1['ADDITIONAL_HEIGHT3'][$i])
					->setCellValue('CM3'.$row, $res1['ADDITIONAL_HEIGHT4'][$i])
					->setCellValue('CN3'.$row, $res1['ADDITIONAL_HEIGHT5'][$i])
					->setCellValue('CO3'.$row, $res1['ADDITIONAL_HEIGHT6'][$i])
					->setCellValue('CP3'.$row, $res1['ADDITIONAL_HEIGHT7'][$i])
					->setCellValue('CQ3'.$row, $res1['ADDITIONAL_HEIGHT8'][$i])
					->setCellValue('CR3'.$row, $res1['ADDITIONAL_HEIGHT9'][$i])
					->setCellValue('CS3'.$row, $res1['ADDITIONAL_HEIGHT10'][$i])
					->setCellValue('CT3'.$row, $res1['ADDITIONAL_HEIGHT11'][$i])
					->setCellValue('CU3'.$row, $res1['ADDITIONAL_HEIGHT12'][$i]);
					/*
					->setCellValue('CV3'.$row, $res1['EXISTING_CAB1'][$i])
					->setCellValue('CW3'.$row, $res1['EXISTING_AMOUNT1'][$i])
					->setCellValue('CX3'.$row, $res1['EXISTING_CAB2'][$i])
					->setCellValue('CY3'.$row, $res1['EXISTING_AMOUNT2'][$i])
					->setCellValue('CZ3'.$row, $res1['ADDITIONAL_CAB1'][$i])
					->setCellValue('DA3'.$row, $res1['ADDITIONAL_AMOUNT1'][$i])
					->setCellValue('DB3'.$row, $res1['ADDITIONAL_CAB2'][$i])
					->setCellValue('DC3'.$row, $res1['ADDITIONAL_AMOUNT2'][$i])
					->setCellValue('DD3'.$row, $res1['SPECIFIC_TXMN'][$i])
					->setCellValue('DE3'.$row, $res1['HMIN'][$i])
					->setCellValue('DF3'.$row, $res1['HMINDISH'][$i])
					->setCellValue('DG3'.$row, $res1['TXMNGUIDES'][$i])
					->setCellValue('DH3'.$row, $res1['BUDGET'][$i]);*/


		$row++;
		$letter="";
		$status_special="";
		$vendor_2G_GSM900="";
		$vendor_2G_GSM1800="";
		$vendor_3G="";
		$band_900="";
		$band_1800="";
		$band_UMTS="";

	}
}else{
	echo "NO RAF data found!";
}


$objPHPExcel->getActiveSheet()->getStyle('U4:U'.$row)->applyFromArray($styleArray_orange);
//$objPHPExcel->getActiveSheet()->getStyle('T4:T1500')->applyFromArray($style_BorderVerticallines);

$objPHPExcel->getActiveSheet()->setAutoFilter('A3:AI3');


$style_BorderVerticallines = array(
			'borders' => array(
				'vertical' => array(
					'style' => PHPExcel_Style_Border::BORDER_THIN,
					'color' => array('argb' => '00000000'),
				),
			),
		);
$objPHPExcel->getActiveSheet()->getStyle('A3:AF'.$row)->applyFromArray($style_BorderVerticallines);

$objPHPExcel->getActiveSheet()->setTitle('RAF report');
$objPHPExcel->setActiveSheetIndex(0);

if ($filtetype=="html"){
	echo __FILE__;

	$objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'HTML');
	$objWriter->setSheetIndex(0);
	$objWriter->setImagesRoot('/var/www/html/infobase/files/infobase/images/');
	$objWriter->save('/var/www/html/bash_scripts/Temp/raf_report_'.$_GET['actionby'].'.html');
}else{
// Redirect output to a client’s web browser (Excel2007)
header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
header('Content-Disposition: attachment;filename="raf_report_'.$_GET['actionby'].'.xlsx"');
header('Cache-Control: max-age=0');

$objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel2007');
$objWriter->save('php://output');
exit;
}
