<?PHP

$query="SELECT
  z.REGION,
  RADIO_INP,
  TXMN_INP,
  ACQ_PARTNER,
  NET1_LINK,
  COF_ACQ_PARTNER,
  COF_ACQ_BASE,
  PO_ACQ,
  PARTNER_INP,
PARTNER_A304,
  BCS_RF_INP,
  BCS_TX_INP,
  BCS_A15,
  NET1_LBP,
  PARTNER_ACQUIRED,
  TXMN_ACQUIRED,
  NET1_ACQUIRED,
  RADIO_BLOCKED_FUND,
  RADIO_FUND,
  CON_PARTNER,
  NET1_FUND,
  COF_CON_PARTNER,
  COF_CON_BASE_TS,
  COF_CON_BASE_PM,
  PO_CON,
  PARTNER_RFPACK,
  RADIO_RFPAC,
  VALREQ_REJECTED,
  VALREQ_MIS_MS_PAC,
  VALREQ_MIS_DOCS_PAC,
  VALREQ_READY_PAC,
  VALREQ_MIS_MS_DOCS_PAC,
  VALREQ_MIS_MS_FAC,
  VALREQ_READY_FAC,
  VALREQ_READY_PAC_FAC,
  NET1_FAC,
  NET1_PAC
FROM
  (
    SELECT
      SUBSTR (SITEID, 0, 2) AS REGION
    FROM
      BSDS_RAFV2
    GROUP BY
      SUBSTR (SITEID, 0, 2)
    ORDER BY
      SUBSTR (SITEID, 0, 2)
  ) z
FULL OUTER JOIN (
  SELECT
    SUBSTR (SITEID, 0, 2) AS REGION,
    COUNT (RADIO_INP) AS RADIO_INP
  FROM
    BSDS_RAFV2
  WHERE
    RADIO_INP = 'NOT OK'
  AND LOWER (DELETED) != 'yes'
  AND LOWER (LOCKEDD) != 'yes'";
   if ($_POST['partner']=='benchmark') {
    $query.=" AND SAC='BENCHMARK'";
  }else  if ($_POST['partner']=='techm') {
    $query.=" AND SAC!='BENCHMARK'";
  }
  $query.=" GROUP BY
    SUBSTR (SITEID, 0, 2)
  ORDER BY
    SUBSTR (SITEID, 0, 2)
) A ON z.REGION = A .REGION
FULL OUTER JOIN (
  SELECT
    SUBSTR (SITEID, 0, 2) AS REGION,
    COUNT (TXMN_INP) AS TXMN_INP
  FROM
    BSDS_RAFV2
  WHERE
    TXMN_INP = 'NOT OK'
  AND RADIO_INP != 'NOT OK'
  AND LOWER (DELETED) != 'yes'
  AND LOWER (LOCKEDD) != 'yes'";
   if ($_POST['partner']=='benchmark') {
    $query.=" AND SAC='BENCHMARK'";
  }else  if ($_POST['partner']=='techm') {
    $query.=" AND SAC!='BENCHMARK'";
  }
  $query.=" GROUP BY
    SUBSTR (SITEID, 0, 2)
  ORDER BY
    SUBSTR (SITEID, 0, 2)
) b ON z.REGION = b.REGION
FULL OUTER JOIN (
  SELECT
    SUBSTR (SITEID, 0, 2) AS REGION,
    COUNT (ACQ_PARTNER) AS ACQ_PARTNER
  FROM
    BSDS_RAFV2
  WHERE
    ACQ_PARTNER = 'NOT OK'
  AND TXMN_INP != 'NOT OK'
  AND RADIO_INP!='REJECTED'
  AND BUFFER != 1
  AND LOWER (DELETED) != 'yes'
  AND LOWER (LOCKEDD) != 'yes'";
   if ($_POST['partner']=='benchmark') {
    $query.=" AND SAC='BENCHMARK'";
  }else  if ($_POST['partner']=='techm') {
    $query.=" AND SAC!='BENCHMARK'";
  }
  $query.=" GROUP BY
    SUBSTR (SITEID, 0, 2)
  ORDER BY
    SUBSTR (SITEID, 0, 2)
) c ON z.REGION = c.REGION
FULL OUTER JOIN (
  SELECT
    SUBSTR (SITEID, 0, 2) AS REGION,
    COUNT (NET1_LINK) AS NET1_LINK
  FROM
    BSDS_RAFV2
  WHERE
    (
      NET1_LINK = 'NOT OK'
      OR TRIM (NET1_LINK) IS NULL
      OR NET1_LINK = 'BCS CHANGE'
    )
  AND TXMN_INP != 'NOT OK'
  AND ACQ_PARTNER != 'NOT OK'
  AND LOWER (DELETED) != 'yes'
  AND LOWER (LOCKEDD) != 'yes'";
   if ($_POST['partner']=='benchmark') {
    $query.=" AND SAC='BENCHMARK'";
  }else  if ($_POST['partner']=='techm') {
    $query.=" AND SAC!='BENCHMARK'";
  }
  $query.=" GROUP BY
    SUBSTR (SITEID, 0, 2)
  ORDER BY
    SUBSTR (SITEID, 0, 2)
) D ON z.REGION = D .REGION
FULL OUTER JOIN (
  SELECT
    SUBSTR (SITEID, 0, 2) AS REGION,
    COUNT (SITEID) AS COF_ACQ_PARTNER
  FROM
    BSDS_RAFV2
  WHERE
    COF_ACQ = 'NOT OK'
    AND (
    TYPE = 'MOV Upgrade'
    OR TYPE = 'IND Upgrade'
    OR TYPE = 'RPT Upgrade'
    OR TYPE = 'CWK Upgrade'
    OR TYPE = 'New Indoor'
  )
  AND NET1_LINK != 'NOT OK'
  AND NET1_LINK != 'END'
  AND NET1_LINK != 'BCS CHANGE'
  AND TXMN_INP != 'NOT OK'
  AND RADIO_INP != 'NOT OK'
  AND ACQ_PARTNER != 'NOT OK'
  AND LOWER (DELETED) != 'yes'
  AND LOWER (LOCKEDD) != 'yes'";
   if ($_POST['partner']=='benchmark') {
    $query.=" AND SAC='BENCHMARK'";
  }else  if ($_POST['partner']=='techm') {
    $query.=" AND SAC!='BENCHMARK'";
  }
  $query.=" GROUP BY
    SUBSTR (SITEID, 0, 2)
  ORDER BY
    SUBSTR (SITEID, 0, 2)
) E ON z.REGION = E .REGION
FULL OUTER JOIN (
  SELECT
    SUBSTR (SITEID, 0, 2) AS REGION,
    COUNT (SITEID) AS COF_ACQ_BASE
  FROM
    BSDS_RAFV2
  WHERE
    (COF_ACQ='PARTNER OK' OR (COF_ACQ='NOT OK' AND TYPE!='MOV Upgrade' AND TYPE!='IND Upgrade' AND TYPE!='RPT Upgrade' AND TYPE!='CWK Upgrade' AND TYPE!='New Indoor'))
  AND NET1_LINK != 'NOT OK'
  AND NET1_LINK != 'END'
  AND NET1_LINK != 'BCS CHANGE'
  AND TXMN_INP != 'NOT OK'
  AND RADIO_INP != 'NOT OK'
  AND ACQ_PARTNER != 'NOT OK'
  AND LOWER (DELETED) != 'yes'
  AND LOWER (LOCKEDD) != 'yes'";
   if ($_POST['partner']=='benchmark') {
    $query.=" AND SAC='BENCHMARK'";
  }else  if ($_POST['partner']=='techm') {
    $query.=" AND SAC!='BENCHMARK'";
  }
  $query.=" GROUP BY
    SUBSTR (SITEID, 0, 2)
  ORDER BY
    SUBSTR (SITEID, 0, 2)
) f ON z.REGION = f.REGION
FULL OUTER JOIN (
  SELECT
    SUBSTR (SITEID, 0, 2) AS REGION,
    COUNT (PARTNER_INP) AS PO_ACQ
  FROM
    BSDS_RAFV2 T
  LEFT JOIN VW_POPR_ACQ ACQ ON T .RAFID = ACQ.RAFID
  WHERE
    (ACQ.POPR IS NULL AND BUFFER != 1 AND TYPE!='New Indoor')
  AND (
    COF_ACQ = 'BASE OK'
    OR COF_ACQ = 'NA'
  )
  AND NET1_LINK != 'NOT OK'
  AND NET1_LINK != 'END'
  AND NET1_LINK != 'BCS CHANGE'
  AND TXMN_INP != 'NOT OK'
  AND RADIO_INP != 'NOT OK'
  AND ACQ_PARTNER != 'NOT OK'
  AND LOWER (DELETED) != 'yes'
  AND LOWER (LOCKEDD) != 'yes'";
   if ($_POST['partner']=='benchmark') {
    $query.=" AND SAC='BENCHMARK'";
  }else  if ($_POST['partner']=='techm') {
    $query.=" AND SAC!='BENCHMARK'";
  }
  $query.=" GROUP BY
    SUBSTR (SITEID, 0, 2)
  ORDER BY
    SUBSTR (SITEID, 0, 2)
) az ON z.REGION = az.REGION
FULL OUTER JOIN (
  SELECT
    SUBSTR (SITEID, 0, 2) AS REGION,
    COUNT (PARTNER_INP) AS PARTNER_INP
  FROM
    BSDS_RAFV2 T
  LEFT JOIN VW_POPR_ACQ ACQ ON T .RAFID = ACQ.RAFID
  WHERE
    PARTNER_INP = 'NOT OK'
  AND (
    ACQ.POPR IS NOT NULL
    OR BUFFER = 1 OR TYPE='New Indoor'
  )
  AND (
    COF_ACQ = 'BASE OK'
    OR COF_ACQ = 'NA'
  )
  AND NET1_LINK != 'NOT OK'
  AND NET1_LINK != 'END'
  AND NET1_LINK != 'BCS CHANGE'
  AND TXMN_INP != 'NOT OK'
  AND RADIO_INP != 'NOT OK'
  AND ACQ_PARTNER != 'NOT OK'
  AND LOWER (DELETED) != 'yes'
  AND LOWER (LOCKEDD) != 'yes'";
   if ($_POST['partner']=='benchmark') {
    $query.=" AND SAC='BENCHMARK'";
  }else  if ($_POST['partner']=='techm') {
    $query.=" AND SAC!='BENCHMARK'";
  }
  $query.=" GROUP BY
    SUBSTR (SITEID, 0, 2)
  ORDER BY
    SUBSTR (SITEID, 0, 2)
) G ON z.REGION = G .REGION
FULL OUTER JOIN (
  SELECT
    SUBSTR (SITEID, 0, 2) AS REGION,
    COUNT (NET1_A304) AS PARTNER_A304
  FROM
    BSDS_RAFV2 T
  LEFT JOIN VW_POPR_ACQ ACQ ON T .RAFID = ACQ.RAFID
  WHERE
    NET1_A304 ='NOT OK'
  AND (
    ACQ.POPR IS NOT NULL
    OR BUFFER = 1 OR TYPE='New Indoor'
  )
  AND (
    COF_ACQ = 'BASE OK'
    OR COF_ACQ = 'NA'
  )
  AND NET1_LINK != 'NOT OK'
  AND NET1_LINK != 'END'
  AND NET1_LINK != 'BCS CHANGE'
  AND TXMN_INP != 'NOT OK'
  AND RADIO_INP != 'NOT OK'
  AND PARTNER_INP = 'OK'
  AND ACQ_PARTNER != 'NOT OK'
  AND LOWER (DELETED) != 'yes'
  AND LOWER (LOCKEDD) != 'yes'";
   if ($_POST['partner']=='benchmark') {
    $query.=" AND SAC='BENCHMARK'";
  }else  if ($_POST['partner']=='techm') {
    $query.=" AND SAC!='BENCHMARK'";
  }
  $query.=" GROUP BY
    SUBSTR (SITEID, 0, 2)
  ORDER BY
    SUBSTR (SITEID, 0, 2)
) Ga ON z.REGION = Ga .REGION
FULL OUTER JOIN (
  SELECT
    SUBSTR (SITEID, 0, 2) AS REGION,
    COUNT (SITEID) AS BCS_RF_INP
  FROM
    BSDS_RAFV2 T
  LEFT JOIN VW_POPR_ACQ ACQ ON T .RAFID = ACQ.RAFID
  WHERE
    BCS_RF_INP = 'NOT OK'
  AND PARTNER_INP != 'NOT OK'
AND NET1_A304 !='NOT OK'
  AND (
    ACQ.POPR IS NOT NULL
    OR BUFFER = 1 OR TYPE='New Indoor'
  )
  AND PARTNER_INP != 'REJECTED'
  AND (
    COF_ACQ = 'BASE OK'
    OR COF_ACQ = 'NA'
  )
  AND NET1_LINK != 'NOT OK'
  AND NET1_LINK != 'END'
  AND NET1_LINK != 'BCS CHANGE'
  AND TXMN_INP != 'NOT OK'
  AND RADIO_INP != 'NOT OK'
  AND ACQ_PARTNER != 'NOT OK'
  AND LOWER (DELETED) != 'yes'
  AND LOWER (LOCKEDD) != 'yes'";
   if ($_POST['partner']=='benchmark') {
    $query.=" AND SAC='BENCHMARK'";
  }else  if ($_POST['partner']=='techm') {
    $query.=" AND SAC!='BENCHMARK'";
  }
  $query.=" GROUP BY
    SUBSTR (SITEID, 0, 2)
  ORDER BY
    SUBSTR (SITEID, 0, 2)
) i ON z.REGION = i.REGION
FULL OUTER JOIN (
  SELECT
    SUBSTR (SITEID, 0, 2) AS REGION,
    COUNT (SITEID) AS BCS_TX_INP
  FROM
    BSDS_RAFV2 T
  LEFT JOIN VW_POPR_ACQ ACQ ON T .RAFID = ACQ.RAFID
  WHERE
    BCS_TX_INP = 'NOT OK'
  AND PARTNER_INP != 'NOT OK'
  AND PARTNER_INP != 'REJECTED'
AND NET1_A304 !='NOT OK'
  AND (
    ACQ.POPR IS NOT NULL
    OR BUFFER = 1 OR TYPE='New Indoor'
  )
  AND (
    COF_ACQ = 'BASE OK'
    OR COF_ACQ = 'NA'
  )
  AND NET1_LINK != 'NOT OK'
  AND NET1_LINK != 'END'
  AND NET1_LINK != 'BCS CHANGE'
  AND TXMN_INP != 'NOT OK'
  AND RADIO_INP != 'NOT OK'
  AND ACQ_PARTNER != 'NOT OK'
  AND LOWER (DELETED) != 'yes'
  AND LOWER (LOCKEDD) != 'yes'";
   if ($_POST['partner']=='benchmark') {
    $query.=" AND SAC='BENCHMARK'";
  }else  if ($_POST['partner']=='techm') {
    $query.=" AND SAC!='BENCHMARK'";
  }
  $query.=" GROUP BY
    SUBSTR (SITEID, 0, 2)
  ORDER BY
    SUBSTR (SITEID, 0, 2)
) i2 ON z.REGION = i2.REGION
FULL OUTER JOIN (
  SELECT
    SUBSTR (SITEID, 0, 2) AS REGION,
    COUNT (SITEID) AS BCS_A15
  FROM
    BSDS_RAFV2 T
  LEFT JOIN VW_POPR_ACQ ACQ ON T .RAFID = ACQ.RAFID
  WHERE
    (
      BCS_NET1 = 'NOT OK'
      OR BCS_NET1 = 'AWAIT SYNC'
      OR BCS_NET1 = 'A304'
    )
  AND BCS_RF_INP != 'NOT OK'
  AND BCS_TX_INP != 'NOT OK'
  AND PARTNER_INP != 'NOT OK'
  AND PARTNER_INP != 'REJECTED'
AND NET1_A304 !='NOT OK'
  AND (
    ACQ.POPR IS NOT NULL
    OR BUFFER = 1 OR TYPE='New Indoor'
  )
  AND (
    COF_ACQ = 'BASE OK'
    OR COF_ACQ = 'NA'
  )
  AND NET1_LINK != 'NOT OK'
  AND NET1_LINK != 'END'
  AND NET1_LINK != 'BCS CHANGE'
  AND TXMN_INP != 'NOT OK'
  AND RADIO_INP != 'NOT OK'
  AND ACQ_PARTNER != 'NOT OK'
  AND LOWER (DELETED) != 'yes'
  AND LOWER (LOCKEDD) != 'yes'";
   if ($_POST['partner']=='benchmark') {
    $query.=" AND SAC='BENCHMARK'";
  }else  if ($_POST['partner']=='techm') {
    $query.=" AND SAC!='BENCHMARK'";
  }
  $query.=" GROUP BY
    SUBSTR (SITEID, 0, 2)
  ORDER BY
    SUBSTR (SITEID, 0, 2)
) j ON z.REGION = j.REGION
FULL OUTER JOIN (
  SELECT
    SUBSTR (SITEID, 0, 2) AS REGION,
    COUNT (SITEID) AS NET1_LBP
  FROM
    BSDS_RAFV2 T
  LEFT JOIN VW_POPR_ACQ ACQ ON T .RAFID = ACQ.RAFID
  WHERE
    NET1_LBP = 'NOT OK'
  AND BUFFER = 0
  AND BCS_NET1 != 'NOT OK'
  AND BCS_NET1 != 'AWAIT SYNC'
  AND BCS_NET1 != 'A304'
  AND BCS_RF_INP != 'NOT OK'
  AND BCS_TX_INP != 'NOT OK'
  AND PARTNER_INP != 'NOT OK'
  AND PARTNER_INP != 'REJECTED'
AND NET1_A304 !='NOT OK'
  AND (
    ACQ.POPR IS NOT NULL
    OR BUFFER = 1 OR TYPE='New Indoor'
  )
  AND (
    COF_ACQ = 'BASE OK'
    OR COF_ACQ = 'NA'
  )
  AND NET1_LINK != 'NOT OK'
  AND NET1_LINK != 'END'
  AND NET1_LINK != 'BCS CHANGE'
  AND TXMN_INP != 'NOT OK'
  AND RADIO_INP != 'NOT OK'
  AND RADIO_INP != 'NOT OK'
  AND ACQ_PARTNER != 'NOT OK'
  AND RADIO_FUND != 'END'
  AND NET1_LINK != 'BCS CHANGE'
  AND LOWER (DELETED) != 'yes'
  AND LOWER (LOCKEDD) != 'yes'";
   if ($_POST['partner']=='benchmark') {
    $query.=" AND SAC='BENCHMARK'";
  }else  if ($_POST['partner']=='techm') {
    $query.=" AND SAC!='BENCHMARK'";
  }
  $query.=" GROUP BY
    SUBSTR (SITEID, 0, 2)
  ORDER BY
    SUBSTR (SITEID, 0, 2)
) K ON z.REGION = K .REGION
FULL OUTER JOIN (
  SELECT
    SUBSTR (SITEID, 0, 2) AS REGION,
    COUNT (SITEID) AS PARTNER_ACQUIRED
  FROM
    BSDS_RAFV2 T
  LEFT JOIN VW_POPR_ACQ ACQ ON T .RAFID = ACQ.RAFID
  WHERE
    (
      PARTNER_ACQUIRED = 'NOT OK'
      OR PARTNER_ACQUIRED = 'REJECTED'
      OR PARTNER_ACQUIRED = 'AWAITING NET1'
    )
  AND NET1_LBP != 'NOT OK'
  AND BCS_NET1 != 'NOT OK'
  AND BCS_NET1 != 'AWAIT SYNC'
  AND BCS_NET1 != 'A304'
  AND BCS_RF_INP != 'NOT OK'
  AND BCS_TX_INP != 'NOT OK'
  AND PARTNER_INP != 'NOT OK'
  AND PARTNER_INP != 'REJECTED'
  AND NET1_A304 !='NOT OK'

  AND (
    ACQ.POPR IS NOT NULL
    OR BUFFER = 1 OR TYPE='New Indoor'
  )
  AND (
    COF_ACQ = 'BASE OK'
    OR COF_ACQ = 'NA'
  )
  AND NET1_LINK != 'NOT OK'
  AND NET1_LINK != 'END'
  AND NET1_LINK != 'BCS CHANGE'
  AND TXMN_INP != 'NOT OK'
  AND RADIO_INP != 'NOT OK'
  AND ACQ_PARTNER != 'NOT OK'
  AND RADIO_FUND != 'END'
  AND NET1_LINK != 'BCS CHANGE'
  AND LOWER (DELETED) != 'yes'
  AND LOWER (LOCKEDD) != 'yes'
  AND BUFFER != 1";
   if ($_POST['partner']=='benchmark') {
    $query.=" AND SAC='BENCHMARK'";
  }else  if ($_POST['partner']=='techm') {
    $query.=" AND SAC!='BENCHMARK'";
  }
  $query.=" GROUP BY
    SUBSTR (SITEID, 0, 2)
  ORDER BY
    SUBSTR (SITEID, 0, 2)
) l ON z.REGION = l.REGION
FULL OUTER JOIN (
  SELECT
    SUBSTR (SITEID, 0, 2) AS REGION,
    COUNT (SITEID) AS TXMN_ACQUIRED
  FROM
    BSDS_RAFV2 T
  LEFT JOIN VW_POPR_ACQ ACQ ON T .RAFID = ACQ.RAFID
  WHERE
    TXMN_ACQUIRED = 'NOT OK'
  AND PARTNER_ACQUIRED != 'NOT OK'
  AND PARTNER_ACQUIRED != 'REJECTED'
  AND NET1_LBP != 'NOT OK'
  AND BCS_NET1 != 'NOT OK'
  AND BCS_NET1 != 'AWAIT SYNC'
  AND BCS_NET1 != 'A304'
  AND BCS_RF_INP != 'NOT OK'
  AND BCS_TX_INP != 'NOT OK'
  AND PARTNER_INP != 'NOT OK'
  AND PARTNER_INP != 'REJECTED'
AND NET1_A304 !='NOT OK'
  AND (
    ACQ.POPR IS NOT NULL
    OR BUFFER = 1 OR TYPE='New Indoor'
  )
  AND (
    COF_ACQ = 'BASE OK'
    OR COF_ACQ = 'NA'
  )
  AND NET1_LINK != 'NOT OK'
  AND NET1_LINK != 'END'
  AND NET1_LINK != 'BCS CHANGE'
  AND TXMN_INP != 'NOT OK'
  AND RADIO_INP != 'NOT OK'
  AND ACQ_PARTNER != 'NOT OK'
  AND RADIO_FUND != 'END'
  AND NET1_LINK != 'BCS CHANGE'
  AND LOWER (DELETED) != 'yes'
  AND LOWER (LOCKEDD) != 'yes'";
   if ($_POST['partner']=='benchmark') {
    $query.=" AND SAC='BENCHMARK'";
  }else  if ($_POST['partner']=='techm') {
    $query.=" AND SAC!='BENCHMARK'";
  }
  $query.=" GROUP BY
    SUBSTR (SITEID, 0, 2)
  ORDER BY
    SUBSTR (SITEID, 0, 2)
) M ON z.REGION = M .REGION
FULL OUTER JOIN (
  SELECT
    SUBSTR (SITEID, 0, 2) AS REGION,
    COUNT (SITEID) AS NET1_ACQUIRED
  FROM
    BSDS_RAFV2 T
  LEFT JOIN VW_POPR_ACQ ACQ ON T .RAFID = ACQ.RAFID
  WHERE
    NET1_ACQUIRED = 'NOT OK'
  AND TXMN_ACQUIRED != 'NOT OK'
  AND PARTNER_ACQUIRED != 'NOT OK'
  AND PARTNER_ACQUIRED != 'REJECTED'
  AND NET1_LBP != 'NOT OK'
  AND BCS_NET1 != 'NOT OK'
  AND BCS_NET1 != 'AWAIT SYNC'
  AND BCS_NET1 != 'A304'
  AND BCS_RF_INP != 'NOT OK'
  AND BCS_TX_INP != 'NOT OK'
  AND PARTNER_INP != 'NOT OK'
  AND PARTNER_INP != 'REJECTED'
AND NET1_A304 !='NOT OK'
  AND (
    ACQ.POPR IS NOT NULL
    OR BUFFER = 1 OR TYPE='New Indoor'
  )
  AND (
    COF_ACQ = 'BASE OK'
    OR COF_ACQ = 'NA'
  )
  AND NET1_LINK != 'NOT OK'
  AND NET1_LINK != 'END'
  AND NET1_LINK != 'BCS CHANGE'
  AND TXMN_INP != 'NOT OK'
  AND ACQ_PARTNER != 'NOT OK'
  AND RADIO_FUND != 'END'
  AND LOWER (DELETED) != 'yes'
  AND LOWER (LOCKEDD) != 'yes'";
   if ($_POST['partner']=='benchmark') {
    $query.=" AND SAC='BENCHMARK'";
  }else  if ($_POST['partner']=='techm') {
    $query.=" AND SAC!='BENCHMARK'";
  }
  $query.=" GROUP BY
    SUBSTR (SITEID, 0, 2)
  ORDER BY
    SUBSTR (SITEID, 0, 2)
) n ON z.REGION = n.REGION
FULL OUTER JOIN (
  SELECT
    SUBSTR (SITEID, 0, 2) AS REGION,
    COUNT (SITEID) AS RADIO_BLOCKED_FUND
  FROM
    BSDS_RAFV2
  WHERE
    (
      RADIO_FUND = 'NO BUDGET'
      OR RADIO_FUND = 'ON HOLD'
    )
  AND TXMN_ACQUIRED != 'NOT OK'
  AND PARTNER_ACQUIRED != 'NOT OK'
  AND PARTNER_ACQUIRED != 'REJECTED'
  AND NET1_LBP != 'NOT OK'
  AND BCS_NET1 != 'NOT OK'
  AND BCS_NET1 != 'AWAIT SYNC'
  AND BCS_NET1 != 'A304'
  AND BCS_RF_INP != 'NOT OK'
  AND BCS_TX_INP != 'NOT OK'
  AND PARTNER_INP != 'NOT OK'
  AND PARTNER_INP != 'REJECTED'
AND NET1_A304 !='NOT OK'
  AND (
    COF_ACQ = 'BASE OK'
    OR COF_ACQ = 'NA'
  )
  AND NET1_LINK != 'NOT OK'
  AND NET1_LINK != 'END'
  AND NET1_LINK != 'BCS CHANGE'
  AND TXMN_INP != 'NOT OK'
  AND RADIO_INP != 'NOT OK'
  AND ACQ_PARTNER != 'NOT OK'
  AND RADIO_FUND != 'END'
  AND LOWER (DELETED) != 'yes'
  AND LOWER (LOCKEDD) != 'yes'";
  if ($_POST['partner']=='benchmark') {
    $query.=" AND CON='BENCHMARK'";
  }else if ($_POST['partner']=='techm') {
    $query.=" AND CON!='BENCHMARK'";
  }
  $query.=" GROUP BY
    SUBSTR (SITEID, 0, 2)
  ORDER BY
    SUBSTR (SITEID, 0, 2)
) o2 ON z.REGION = o2.REGION
FULL OUTER JOIN (
  SELECT
    SUBSTR (SITEID, 0, 2) AS REGION,
    COUNT (SITEID) AS RADIO_FUND
  FROM
    BSDS_RAFV2
  WHERE
    RADIO_FUND = 'NOT OK'
  AND TXMN_ACQUIRED != 'NOT OK'
  AND PARTNER_ACQUIRED != 'NOT OK'
  AND PARTNER_ACQUIRED != 'REJECTED'
  AND NET1_LBP != 'NOT OK'
  AND BCS_NET1 != 'NOT OK'
  AND BCS_NET1 != 'AWAIT SYNC'
  AND BCS_NET1 != 'A304'
  AND BCS_RF_INP != 'NOT OK'
  AND BCS_TX_INP != 'NOT OK'
  AND PARTNER_INP != 'NOT OK'
  AND PARTNER_INP != 'REJECTED'
AND NET1_A304 !='NOT OK'
  AND (
    COF_ACQ = 'BASE OK'
    OR COF_ACQ = 'NA'
  )
  AND NET1_LINK != 'NOT OK'
  AND NET1_LINK != 'END'
  AND NET1_LINK != 'BCS CHANGE'
  AND TXMN_INP != 'NOT OK'
  AND RADIO_INP != 'NOT OK'
  AND ACQ_PARTNER != 'NOT OK'
  AND RADIO_FUND != 'END'
  AND LOWER (DELETED) != 'yes'
  AND LOWER (LOCKEDD) != 'yes'";
  if ($_POST['partner']=='benchmark') {
    $query.=" AND CON='BENCHMARK'";
  }else if ($_POST['partner']=='techm') {
    $query.=" AND CON!='BENCHMARK'";
  }
  $query.=" GROUP BY
    SUBSTR (SITEID, 0, 2)
  ORDER BY
    SUBSTR (SITEID, 0, 2)
) o ON z.REGION = o.REGION
FULL OUTER JOIN (
  SELECT
    SUBSTR (SITEID, 0, 2) AS REGION,
    COUNT (SITEID) AS CON_PARTNER
  FROM
    BSDS_RAFV2
  WHERE
    CON_PARTNER = 'NOT OK'
  AND RADIO_FUND != 'NOT OK'
  AND RADIO_FUND != 'ON HOLD'
  AND RADIO_FUND != 'NO BUDGET'
  AND RADIO_FUND != 'END'
  AND RADIO_FUND != 'NOT FUNDED'
  AND TXMN_ACQUIRED != 'NOT OK'
  AND PARTNER_ACQUIRED != 'NOT OK'
  AND PARTNER_ACQUIRED != 'REJECTED'
  AND NET1_LBP != 'NOT OK'
  AND BCS_NET1 != 'NOT OK'
  AND BCS_NET1 != 'AWAIT SYNC'
  AND BCS_NET1 != 'A304'
  AND BCS_RF_INP != 'NOT OK'
  AND BCS_TX_INP != 'NOT OK'
  AND PARTNER_INP != 'NOT OK'
  AND PARTNER_INP != 'REJECTED'
AND NET1_A304 !='NOT OK'
  AND (
    COF_ACQ = 'BASE OK'
    OR COF_ACQ = 'NA'
  )
  AND NET1_LINK != 'NOT OK'
  AND NET1_LINK != 'END'
  AND NET1_LINK != 'BCS CHANGE'
  AND TXMN_INP != 'NOT OK'
  AND RADIO_INP != 'NOT OK'
  AND ACQ_PARTNER != 'NOT OK'
  AND RADIO_FUND != 'END'
  AND LOWER (DELETED) != 'yes'
  AND LOWER (LOCKEDD) != 'yes'";
  if ($_POST['partner']=='benchmark') {
    $query.=" AND CON='BENCHMARK'";
  }else if ($_POST['partner']=='techm') {
    $query.=" AND CON!='BENCHMARK'";
  }
  $query.=" GROUP BY
    SUBSTR (SITEID, 0, 2)
  ORDER BY
    SUBSTR (SITEID, 0, 2)
) P ON z.REGION = P .REGION
FULL OUTER JOIN (
  SELECT
    SUBSTR (SITEID, 0, 2) AS REGION,
    COUNT (SITEID) AS NET1_FUND
  FROM
    BSDS_RAFV2
  WHERE
    NET1_FUND = 'NOT OK'
  AND CON_PARTNER != 'NOT OK'
  AND RADIO_FUND != 'NOT OK'
  AND RADIO_FUND != 'ON HOLD'
  AND RADIO_FUND != 'NO BUDGET'
  AND RADIO_FUND != 'NOT FUNDED'
  AND RADIO_FUND != 'END'
  AND TXMN_ACQUIRED != 'NOT OK'
  AND PARTNER_ACQUIRED != 'NOT OK'
  AND PARTNER_ACQUIRED != 'REJECTED'
  AND NET1_LBP != 'NOT OK'
  AND BCS_NET1 != 'NOT OK'
  AND BCS_NET1 != 'AWAIT SYNC'
  AND BCS_NET1 != 'A304'
  AND BCS_RF_INP != 'NOT OK'
  AND BCS_TX_INP != 'NOT OK'
  AND PARTNER_INP != 'NOT OK'
  AND PARTNER_INP != 'REJECTED'
AND NET1_A304 !='NOT OK'
  AND (
    COF_ACQ = 'BASE OK'
    OR COF_ACQ = 'NA'
  )
  AND NET1_LINK != 'NOT OK'
  AND NET1_LINK != 'END'
  AND NET1_LINK != 'BCS CHANGE'
  AND TXMN_INP != 'NOT OK'
  AND RADIO_INP != 'NOT OK'
  AND ACQ_PARTNER != 'NOT OK'
  AND RADIO_FUND != 'END'
  AND LOWER (DELETED) != 'yes'
  AND LOWER (LOCKEDD) != 'yes'";
  if ($_POST['partner']=='benchmark') {
    $query.=" AND CON='BENCHMARK'";
  }else if ($_POST['partner']=='techm') {
    $query.=" AND CON!='BENCHMARK'";
  }
  $query.=" GROUP BY
    SUBSTR (SITEID, 0, 2)
  ORDER BY
    SUBSTR (SITEID, 0, 2)
) q ON z.REGION = q.REGION
FULL OUTER JOIN (
  SELECT
    SUBSTR (SITEID, 0, 2) AS REGION,
    COUNT (SITEID) AS COF_CON_PARTNER
  FROM
    BSDS_RAFV2 T
  LEFT JOIN VW_POPR_CON ACQ ON T .RAFID = ACQ.RAFID
  WHERE
    COF_CON = 'NOT OK'
  AND CON_PARTNER != 'NOT OK'
  AND RADIO_FUND != 'NOT OK'
  AND RADIO_FUND != 'ON HOLD'
  AND RADIO_FUND != 'NO BUDGET'
  AND RADIO_FUND != 'NOT FUNDED'
  AND RADIO_FUND != 'END'
  AND NET1_FUND != 'NOT OK'
  AND TXMN_ACQUIRED != 'NOT OK'
  AND PARTNER_ACQUIRED != 'NOT OK'
  AND PARTNER_ACQUIRED != 'REJECTED'
  AND NET1_LBP != 'NOT OK'
  AND BCS_NET1 != 'NOT OK'
  AND BCS_NET1 != 'AWAIT SYNC'
  AND BCS_NET1 != 'A304'
  AND BCS_RF_INP != 'NOT OK'
  AND BCS_TX_INP != 'NOT OK'
  AND PARTNER_INP != 'NOT OK'
  AND PARTNER_INP != 'REJECTED'
AND NET1_A304 !='NOT OK'
  AND (ACQ.POPR IS NOT NULL OR BUFFER=1 OR TYPE='New Indoor')
  AND (
    COF_ACQ = 'BASE OK'
    OR COF_ACQ = 'NA'
  )
  AND NET1_LINK != 'NOT OK'
  AND NET1_LINK != 'END'
  AND NET1_LINK != 'BCS CHANGE'
  AND TXMN_INP != 'NOT OK'
  AND RADIO_INP != 'NOT OK'
  AND ACQ_PARTNER != 'NOT OK'
  AND RADIO_FUND != 'END'
  AND LOWER (DELETED) != 'yes'
  AND LOWER (LOCKEDD) != 'yes'";
  if ($_POST['partner']=='benchmark') {
    $query.=" AND CON='BENCHMARK'";
  }else if ($_POST['partner']=='techm') {
    $query.=" AND CON!='BENCHMARK'";
  }
  $query.=" GROUP BY
    SUBSTR (SITEID, 0, 2)
  ORDER BY
    SUBSTR (SITEID, 0, 2)
) r ON z.REGION = r.REGION
FULL OUTER JOIN (
  SELECT
    SUBSTR (SITEID, 0, 2) AS REGION,
    COUNT (SITEID) AS COF_CON_BASE_TS
  FROM
      BSDS_RAFV2 T
      LEFT JOIN VW_POPR_CON ACQ ON T.RAFID = ACQ.RAFID
      LEFT JOIN RAF_HAS_BOQ BOQ ON BOQ.BOQ_RAFID=T.RAFID
      WHERE
  COF_CON = 'PARTNER OK' AND BOQ_RAFID IS NOT NULL
  AND CON_PARTNER != 'NOT OK'
  AND RADIO_FUND != 'NOT OK'
  AND RADIO_FUND != 'ON HOLD'
  AND RADIO_FUND != 'NOT FUNDED'
  AND RADIO_FUND != 'NO BUDGET'
  AND RADIO_FUND != 'END'
  AND TXMN_ACQUIRED != 'NOT OK'
  AND PARTNER_ACQUIRED != 'NOT OK'
  AND PARTNER_ACQUIRED != 'REJECTED'
  AND NET1_LBP != 'NOT OK'
  AND BCS_NET1 != 'NOT OK'
  AND BCS_NET1 != 'AWAIT SYNC'
  AND BCS_NET1 != 'A304'
  AND BCS_RF_INP != 'NOT OK'
  AND BCS_TX_INP != 'NOT OK'
  AND PARTNER_INP != 'NOT OK'
  AND PARTNER_INP != 'REJECTED'
  AND NET1_A304 !='NOT OK'
  AND (ACQ.POPR IS NOT NULL OR BUFFER=1 OR TYPE='New Indoor')
  AND (
    COF_ACQ = 'BASE OK'
    OR COF_ACQ = 'NA'
  )
  AND NET1_LINK != 'NOT OK'
  AND NET1_LINK != 'END'
  AND NET1_LINK != 'BCS CHANGE'
  AND TXMN_INP != 'NOT OK'
  AND RADIO_INP != 'NOT OK'
  AND ACQ_PARTNER != 'NOT OK'
  AND RADIO_FUND != 'END'
  AND LOWER (DELETED) != 'yes'
  AND LOWER (LOCKEDD) != 'yes'";
  if ($_POST['partner']=='benchmark') {
    $query.=" AND CON='BENCHMARK'";
  }else if ($_POST['partner']=='techm') {
    $query.=" AND CON!='BENCHMARK'";
  }
  $query.=" GROUP BY
    SUBSTR (SITEID, 0, 2)
  ORDER BY
    SUBSTR (SITEID, 0, 2)
) sBOQ ON z.REGION = sBOQ.REGION
FULL OUTER JOIN (
  SELECT
    SUBSTR (SITEID, 0, 2) AS REGION,
    COUNT (SITEID) AS COF_CON_BASE_PM
   FROM
        BSDS_RAFV2 T
      LEFT JOIN VW_POPR_CON ACQ ON T .RAFID = ACQ.RAFID
      LEFT JOIN RAF_HAS_BOQ BOQ ON BOQ.BOQ_RAFID=T.RAFID
      WHERE
  ((COF_CON = 'PARTNER OK' AND BOQ_RAFID IS NULL) OR COF_CON = 'BASE TS OK')
  AND CON_PARTNER != 'NOT OK'
  AND RADIO_FUND != 'NOT OK'
  AND RADIO_FUND != 'ON HOLD'
  AND RADIO_FUND != 'NOT FUNDED'
  AND RADIO_FUND != 'NO BUDGET'
  AND RADIO_FUND != 'END'
  AND TXMN_ACQUIRED != 'NOT OK'
  AND PARTNER_ACQUIRED != 'NOT OK'
  AND PARTNER_ACQUIRED != 'REJECTED'
  AND NET1_LBP != 'NOT OK'
  AND BCS_NET1 != 'NOT OK'
  AND BCS_NET1 != 'AWAIT SYNC'
  AND BCS_NET1 != 'A304'
  AND BCS_RF_INP != 'NOT OK'
  AND BCS_TX_INP != 'NOT OK'
  AND PARTNER_INP != 'NOT OK'
  AND PARTNER_INP != 'REJECTED'
AND NET1_A304 !='NOT OK'
  AND (ACQ.POPR IS NOT NULL OR BUFFER=1 OR TYPE='New Indoor')
  AND (
    COF_ACQ = 'BASE OK'
    OR COF_ACQ = 'NA'
  )
  AND NET1_LINK != 'NOT OK'
  AND NET1_LINK != 'END'
  AND NET1_LINK != 'BCS CHANGE'
  AND TXMN_INP != 'NOT OK'
  AND RADIO_INP != 'NOT OK'
  AND ACQ_PARTNER != 'NOT OK'
  AND RADIO_FUND != 'END'
  AND LOWER (DELETED) != 'yes'
  AND LOWER (LOCKEDD) != 'yes'";
  if ($_POST['partner']=='benchmark') {
    $query.=" AND CON='BENCHMARK'";
  }else if ($_POST['partner']=='techm') {
    $query.=" AND CON!='BENCHMARK'";
  }
  $query.=" GROUP BY
    SUBSTR (SITEID, 0, 2)
  ORDER BY
    SUBSTR (SITEID, 0, 2)
) s ON z.REGION = s.REGION
FULL OUTER JOIN (
  SELECT
    SUBSTR (T .SITEID, 0, 2) AS REGION,
    COUNT (SITEID) AS PO_CON
  FROM
    BSDS_RAFV2 T
  LEFT JOIN VW_POPR_CON CON ON T .RAFID = CON.RAFID
  WHERE
    POPR IS NULL
  AND COF_CON = 'BASE OK'
  AND NET1_FUND != 'NOT OK' /*AND NET1_ACQUIRED!='NOT OK'*/
  AND CON_PARTNER != 'NOT OK'
  AND RADIO_FUND != 'NOT OK'
  AND RADIO_FUND != 'ON HOLD'
  AND RADIO_FUND != 'NO BUDGET'
  AND RADIO_FUND != 'NOT FUNDED'
  AND RADIO_FUND != 'END'
  AND TXMN_ACQUIRED != 'NOT OK'
  AND PARTNER_ACQUIRED != 'NOT OK'
  AND PARTNER_ACQUIRED != 'REJECTED'
  AND NET1_LBP != 'NOT OK'
  AND BCS_NET1 != 'NOT OK'
  AND BCS_NET1 != 'AWAIT SYNC'
  AND BCS_NET1 != 'A304'
  AND BCS_RF_INP != 'NOT OK'
  AND BCS_TX_INP != 'NOT OK'
  AND PARTNER_INP != 'NOT OK'
  AND PARTNER_INP != 'REJECTED'
AND NET1_A304 !='NOT OK'
  AND (
    COF_ACQ = 'BASE OK'
    OR COF_ACQ = 'NA'
  )
  AND NET1_LINK != 'NOT OK'
  AND NET1_LINK != 'END'
  AND NET1_LINK != 'BCS CHANGE'
  AND TXMN_INP != 'NOT OK'
  AND RADIO_INP != 'NOT OK'
  AND ACQ_PARTNER != 'NOT OK'
  AND RADIO_FUND != 'END'
  AND LOWER (DELETED) != 'yes'
  AND LOWER (LOCKEDD) != 'yes'";
  if ($_POST['partner']=='benchmark') {
    $query.=" AND CON='BENCHMARK'";
  }else if ($_POST['partner']=='techm') {
    $query.=" AND CON!='BENCHMARK'";
  }
  $query.=" GROUP BY
    SUBSTR (SITEID, 0, 2)
  ORDER BY
    SUBSTR (SITEID, 0, 2)
) T ON z.REGION = T .REGION
FULL OUTER JOIN (
  SELECT
    SUBSTR (T .SITEID, 0, 2) AS REGION,
    COUNT (SITEID) AS PARTNER_RFPAC
  FROM
    BSDS_RAFV2 T
  LEFT JOIN VW_POPR_CON CON ON T .RAFID = CON.RAFID
  WHERE
    (
      PARTNER_RFPACK = 'NOT OK'
      OR PARTNER_RFPACK = 'REJECTED'
      OR PARTNER_RFPACK = 'AWAITING NET1'
      OR PARTNER_RFPACK = 'AWAITING SYNC'
    )
  AND POPR IS NOT NULL
  AND COF_CON = 'BASE OK'
  AND NET1_FUND != 'NOT OK' /* AND NET1_ACQUIRED!='NOT OK'*/
  AND CON_PARTNER != 'NOT OK'
  AND RADIO_FUND != 'NOT OK'
  AND RADIO_FUND != 'ON HOLD'
  AND RADIO_FUND != 'NO BUDGET'
  AND RADIO_FUND != 'NOT FUNDED'
  AND RADIO_FUND != 'END'
  AND TXMN_ACQUIRED != 'NOT OK'
  AND PARTNER_ACQUIRED != 'NOT OK'
  AND PARTNER_ACQUIRED != 'REJECTED'
  AND NET1_LBP != 'NOT OK'
  AND BCS_NET1 != 'NOT OK'
  AND BCS_NET1 != 'AWAIT SYNC'
  AND BCS_NET1 != 'A304'
  AND BCS_RF_INP != 'NOT OK'
  AND BCS_TX_INP != 'NOT OK'
  AND PARTNER_INP != 'NOT OK'
  AND PARTNER_INP != 'REJECTED'
AND NET1_A304 !='NOT OK'
  AND (
    COF_ACQ = 'BASE OK'
    OR COF_ACQ = 'NA'
  )
  AND NET1_LINK != 'NOT OK'
  AND NET1_LINK != 'END'
  AND NET1_LINK != 'BCS CHANGE'
  AND TXMN_INP != 'NOT OK'
  AND RADIO_INP != 'NOT OK'
  AND ACQ_PARTNER != 'NOT OK'
  AND RADIO_FUND != 'END'
  AND LOWER (DELETED) != 'yes'
  AND LOWER (LOCKEDD) != 'yes'";
  if ($_POST['partner']=='benchmark') {
    $query.=" AND CON='BENCHMARK'";
  }else if ($_POST['partner']=='techm') {
    $query.=" AND CON!='BENCHMARK'";
  }
  $query.=" GROUP BY
    SUBSTR (SITEID, 0, 2)
  ORDER BY
    SUBSTR (SITEID, 0, 2)
) U ON z.REGION = U .REGION
FULL OUTER JOIN (
  SELECT
    SUBSTR (T .SITEID, 0, 2) AS REGION,
    COUNT (SITEID) AS RADIO_RFPAC
  FROM
    BSDS_RAFV2 T
  LEFT JOIN VW_POPR_CON CON ON T .RAFID = CON.RAFID
  WHERE
    (
      RF_PAC = 'NOT OK'
      OR RF_PAC = 'AWAITING SYNC'
    OR RF_PAC = 'OK'
    )
  AND PARTNER_RFPACK != 'NOT OK'
  AND PARTNER_RFPACK != 'REJECTED'
  AND POPR IS NOT NULL
  AND COF_CON = 'BASE OK'
  AND NET1_FUND != 'NOT OK' /* AND NET1_ACQUIRED!='NOT OK'*/
  AND CON_PARTNER != 'NOT OK'
  AND RADIO_FUND != 'NOT OK'
  AND RADIO_FUND != 'ON HOLD'
  AND RADIO_FUND != 'NO BUDGET'
  AND RADIO_FUND != 'NOT FUNDED'
  AND RADIO_FUND != 'END'
  AND TXMN_ACQUIRED != 'NOT OK'
  AND PARTNER_ACQUIRED != 'NOT OK'
  AND PARTNER_ACQUIRED != 'REJECTED'
  AND NET1_LBP != 'NOT OK'
  AND BCS_NET1 != 'NOT OK'
  AND BCS_NET1 != 'AWAIT SYNC'
  AND BCS_NET1 != 'A304'
  AND BCS_RF_INP != 'NOT OK'
  AND BCS_TX_INP != 'NOT OK'
  AND PARTNER_INP != 'NOT OK'
  AND PARTNER_INP != 'REJECTED'
AND NET1_A304 !='NOT OK'
  AND (
    COF_ACQ = 'BASE OK'
    OR COF_ACQ = 'NA'
  )
  AND NET1_LINK != 'NOT OK'
  AND NET1_LINK != 'END'
  AND NET1_LINK != 'BCS CHANGE'
  AND TXMN_INP != 'NOT OK'
  AND RADIO_INP != 'NOT OK'
  AND ACQ_PARTNER != 'NOT OK'
  AND RADIO_FUND != 'END'
  AND LOWER (DELETED) != 'yes'
  AND LOWER (LOCKEDD) != 'yes'";
  if ($_POST['partner']=='benchmark') {
    $query.=" AND CON='BENCHMARK'";
  }else if ($_POST['partner']=='techm') {
    $query.=" AND CON!='BENCHMARK'";
  }
  $query.=" GROUP BY
    SUBSTR (SITEID, 0, 2)
  ORDER BY
    SUBSTR (SITEID, 0, 2)
) v ON z.REGION = v.REGION
FULL OUTER JOIN (
  SELECT
    SUBSTR (T .SITEID, 0, 2) AS REGION,
    COUNT (SITEID) AS VALREQ_REJECTED
  FROM
    BSDS_RAFV2 T
  LEFT JOIN VW_POPR_CON CON ON T .RAFID = CON.RAFID
  WHERE
    PARTNER_VALREQ = 'REJECTED'
  AND RF_PAC = 'OK'
  AND PARTNER_RFPACK != 'NOT OK'
  AND PARTNER_RFPACK != 'REJECTED'
  AND POPR IS NOT NULL
  AND COF_CON = 'BASE OK'
  AND NET1_FUND != 'NOT OK' /* AND NET1_ACQUIRED!='NOT OK'*/
  AND CON_PARTNER != 'NOT OK'
  AND RADIO_FUND != 'NOT OK'
  AND RADIO_FUND != 'ON HOLD'
  AND RADIO_FUND != 'NO BUDGET'
  AND RADIO_FUND != 'NOT FUNDED'
  AND RADIO_FUND != 'END'
  AND TXMN_ACQUIRED != 'NOT OK'
  AND PARTNER_ACQUIRED != 'NOT OK'
  AND PARTNER_ACQUIRED != 'REJECTED'
  AND NET1_LBP != 'NOT OK'
  AND BCS_NET1 != 'NOT OK'
  AND BCS_NET1 != 'AWAIT SYNC'
  AND BCS_NET1 != 'A304'
  AND BCS_RF_INP != 'NOT OK'
  AND BCS_TX_INP != 'NOT OK'
  AND PARTNER_INP != 'NOT OK'
  AND PARTNER_INP != 'REJECTED'
AND NET1_A304 !='NOT OK'
  AND (
    COF_ACQ = 'BASE OK'
    OR COF_ACQ = 'NA'
  )
  AND NET1_LINK != 'NOT OK'
  AND NET1_LINK != 'END'
  AND NET1_LINK != 'BCS CHANGE'
  AND TXMN_INP != 'NOT OK'
  AND RADIO_INP != 'NOT OK'
  AND ACQ_PARTNER != 'NOT OK'
  AND RADIO_FUND != 'END'
  AND LOWER (DELETED) != 'yes'
  AND LOWER (LOCKEDD) != 'yes'
 AND (NET1_PAC!='NOT OK' OR NET1_FAC!='NOT OK')";
  if ($_POST['partner']=='benchmark') {
    $query.=" AND CON='BENCHMARK'";
  }else if ($_POST['partner']=='techm') {
    $query.=" AND CON!='BENCHMARK'";
  }
  $query.=" GROUP BY
    SUBSTR (SITEID, 0, 2)
  ORDER BY
    SUBSTR (SITEID, 0, 2)
) w ON z.REGION = w.REGION
FULL OUTER JOIN (
  SELECT
    SUBSTR (T .SITEID, 0, 2) AS REGION,
    COUNT (SITEID) AS VALREQ_MIS_MS_PAC
  FROM
    BSDS_RAFV2 T
  LEFT JOIN VW_POPR_CON CON ON T .RAFID = CON.RAFID
  WHERE
    PARTNER_VALREQ = 'MISSING MS FOR PAC'
  AND RF_PAC = 'OK'
  AND PARTNER_RFPACK != 'NOT OK'
  AND PARTNER_RFPACK != 'REJECTED'
  AND POPR IS NOT NULL
  AND COF_CON = 'BASE OK'
  AND NET1_FUND != 'NOT OK' /* AND NET1_ACQUIRED!='NOT OK'*/
  AND CON_PARTNER != 'NOT OK'
  AND RADIO_FUND != 'NOT OK'
  AND RADIO_FUND != 'ON HOLD'
  AND RADIO_FUND != 'NO BUDGET'
  AND RADIO_FUND != 'NOT FUNDED'
  AND RADIO_FUND != 'END'
  AND TXMN_ACQUIRED != 'NOT OK'
  AND PARTNER_ACQUIRED != 'NOT OK'
  AND PARTNER_ACQUIRED != 'REJECTED'
  AND NET1_LBP != 'NOT OK'
  AND BCS_NET1 != 'NOT OK'
  AND BCS_NET1 != 'AWAIT SYNC'
  AND BCS_NET1 != 'A304'
  AND BCS_RF_INP != 'NOT OK'
  AND BCS_TX_INP != 'NOT OK'
  AND PARTNER_INP != 'NOT OK'
  AND PARTNER_INP != 'REJECTED'
AND NET1_A304 !='NOT OK'
  AND (
    COF_ACQ = 'BASE OK'
    OR COF_ACQ = 'NA'
  )
  AND NET1_LINK != 'NOT OK'
  AND NET1_LINK != 'END'
  AND NET1_LINK != 'BCS CHANGE'
  AND TXMN_INP != 'NOT OK'
  AND RADIO_INP != 'NOT OK'
  AND ACQ_PARTNER != 'NOT OK'
  AND RADIO_FUND != 'END'
 AND (NET1_PAC!='NOT OK' OR NET1_FAC!='NOT OK')
  AND LOWER (DELETED) != 'yes'
  AND LOWER (LOCKEDD) != 'yes'";
  if ($_POST['partner']=='benchmark') {
    $query.=" AND CON='BENCHMARK'";
  }else if ($_POST['partner']=='techm') {
    $query.=" AND CON!='BENCHMARK'";
  }
  $query.=" GROUP BY
    SUBSTR (SITEID, 0, 2)
  ORDER BY
    SUBSTR (SITEID, 0, 2)
) x ON z.REGION = x.REGION
FULL OUTER JOIN (
  SELECT
    SUBSTR (T .SITEID, 0, 2) AS REGION,
    COUNT (SITEID) AS VALREQ_MIS_DOCS_PAC
  FROM
    BSDS_RAFV2 T
  LEFT JOIN VW_POPR_CON CON ON T .RAFID = CON.RAFID
  WHERE
    PARTNER_VALREQ = 'MISSING DOCS FOR PAC'
  AND RF_PAC = 'OK'
  AND PARTNER_RFPACK != 'NOT OK'
  AND PARTNER_RFPACK != 'REJECTED'
  AND POPR IS NOT NULL
  AND COF_CON = 'BASE OK'
  AND NET1_FUND != 'NOT OK' /* AND NET1_ACQUIRED!='NOT OK'*/
  AND CON_PARTNER != 'NOT OK'
  AND RADIO_FUND != 'NOT OK'
  AND RADIO_FUND != 'ON HOLD'
  AND RADIO_FUND != 'NO BUDGET'
  AND RADIO_FUND != 'NOT FUNDED'
  AND RADIO_FUND != 'END'
  AND TXMN_ACQUIRED != 'NOT OK'
  AND PARTNER_ACQUIRED != 'NOT OK'
  AND PARTNER_ACQUIRED != 'REJECTED'
  AND NET1_LBP != 'NOT OK'
  AND BCS_NET1 != 'NOT OK'
  AND BCS_NET1 != 'AWAIT SYNC'
  AND BCS_NET1 != 'A304'
  AND BCS_RF_INP != 'NOT OK'
  AND BCS_TX_INP != 'NOT OK'
  AND PARTNER_INP != 'NOT OK'
  AND PARTNER_INP != 'REJECTED'
AND NET1_A304 !='NOT OK'
  AND (
    COF_ACQ = 'BASE OK'
    OR COF_ACQ = 'NA'
  )
  AND NET1_LINK != 'NOT OK'
  AND NET1_LINK != 'END'
  AND NET1_LINK != 'BCS CHANGE'
  AND TXMN_INP != 'NOT OK'
  AND RADIO_INP != 'NOT OK'
  AND ACQ_PARTNER != 'NOT OK'
  AND RADIO_FUND != 'END'
 AND (NET1_PAC!='NOT OK' OR NET1_FAC!='NOT OK')
  AND LOWER (DELETED) != 'yes'
  AND LOWER (LOCKEDD) != 'yes'";
  if ($_POST['partner']=='benchmark') {
    $query.=" AND CON='BENCHMARK'";
  }else if ($_POST['partner']=='techm') {
    $query.=" AND CON!='BENCHMARK'";
  }
  $query.=" GROUP BY
    SUBSTR (SITEID, 0, 2)
  ORDER BY
    SUBSTR (SITEID, 0, 2)
) y ON z.REGION = y.REGION
FULL OUTER JOIN (
  SELECT
    SUBSTR (T .SITEID, 0, 2) AS REGION,
    COUNT (SITEID) AS VALREQ_READY_PAC
  FROM
    BSDS_RAFV2 T
  LEFT JOIN VW_POPR_CON CON ON T .RAFID = CON.RAFID
  WHERE
    PARTNER_VALREQ = 'READY FOR PAC'
  AND RF_PAC = 'OK'
  AND PARTNER_RFPACK != 'NOT OK'
  AND PARTNER_RFPACK != 'REJECTED'
  AND POPR IS NOT NULL
  AND COF_CON = 'BASE OK'
  AND NET1_FUND != 'NOT OK' /* AND NET1_ACQUIRED!='NOT OK'*/
  AND CON_PARTNER != 'NOT OK'
  AND RADIO_FUND != 'NOT OK'
  AND RADIO_FUND != 'ON HOLD'
  AND RADIO_FUND != 'NO BUDGET'
  AND RADIO_FUND != 'NOT FUNDED'
  AND RADIO_FUND != 'END'
  AND TXMN_ACQUIRED != 'NOT OK'
  AND PARTNER_ACQUIRED != 'NOT OK'
  AND PARTNER_ACQUIRED != 'REJECTED'
  AND NET1_LBP != 'NOT OK'
  AND BCS_NET1 != 'NOT OK'
  AND BCS_NET1 != 'AWAIT SYNC'
  AND BCS_NET1 != 'A304'
  AND BCS_RF_INP != 'NOT OK'
  AND BCS_TX_INP != 'NOT OK'
  AND PARTNER_INP != 'NOT OK'
  AND PARTNER_INP != 'REJECTED'
AND NET1_A304 !='NOT OK'
  AND (
    COF_ACQ = 'BASE OK'
    OR COF_ACQ = 'NA'
  )
  AND NET1_LINK != 'NOT OK'
  AND NET1_LINK != 'END'
  AND NET1_LINK != 'BCS CHANGE'
  AND TXMN_INP != 'NOT OK'
  AND RADIO_INP != 'NOT OK'
  AND ACQ_PARTNER != 'NOT OK'
  AND RADIO_FUND != 'END'
 AND (NET1_PAC!='NOT OK' OR NET1_FAC!='NOT OK')
  AND LOWER (DELETED) != 'yes'
  AND LOWER (LOCKEDD) != 'yes'";
  if ($_POST['partner']=='benchmark') {
    $query.=" AND CON='BENCHMARK'";
  }else if ($_POST['partner']=='techm') {
    $query.=" AND CON!='BENCHMARK'";
  }
  $query.=" GROUP BY
    SUBSTR (SITEID, 0, 2)
  ORDER BY
    SUBSTR (SITEID, 0, 2)
) aa ON z.REGION = aa.REGION
FULL OUTER JOIN (
  SELECT
    SUBSTR (T .SITEID, 0, 2) AS REGION,
    COUNT (SITEID) AS VALREQ_MIS_MS_DOCS_PAC
  FROM
    BSDS_RAFV2 T
  LEFT JOIN VW_POPR_CON CON ON T .RAFID = CON.RAFID
  WHERE
    PARTNER_VALREQ = 'MISSING MS&DOCS FOR PAC'
  AND RF_PAC = 'OK'
  AND PARTNER_RFPACK != 'NOT OK'
  AND PARTNER_RFPACK != 'REJECTED'
  AND POPR IS NOT NULL
  AND COF_CON = 'BASE OK'
  AND NET1_FUND != 'NOT OK' /* AND NET1_ACQUIRED!='NOT OK'*/
  AND CON_PARTNER != 'NOT OK'
  AND RADIO_FUND != 'NOT OK'
  AND RADIO_FUND != 'ON HOLD'
  AND RADIO_FUND != 'NO BUDGET'
  AND RADIO_FUND != 'NOT FUNDED'
  AND RADIO_FUND != 'END'
  AND TXMN_ACQUIRED != 'NOT OK'
  AND PARTNER_ACQUIRED != 'NOT OK'
  AND PARTNER_ACQUIRED != 'REJECTED'
  AND NET1_LBP != 'NOT OK'
  AND BCS_NET1 != 'NOT OK'
  AND BCS_NET1 != 'AWAIT SYNC'
  AND BCS_NET1 != 'A304'
  AND BCS_RF_INP != 'NOT OK'
  AND BCS_TX_INP != 'NOT OK'
  AND PARTNER_INP != 'NOT OK'
  AND PARTNER_INP != 'REJECTED'
AND NET1_A304 !='NOT OK'
  AND (
    COF_ACQ = 'BASE OK'
    OR COF_ACQ = 'NA'
  )
  AND NET1_LINK != 'NOT OK'
  AND NET1_LINK != 'END'
  AND NET1_LINK != 'BCS CHANGE'
  AND TXMN_INP != 'NOT OK'
  AND RADIO_INP != 'NOT OK'
  AND ACQ_PARTNER != 'NOT OK'
  AND RADIO_FUND != 'END'
 AND (NET1_PAC!='NOT OK' OR NET1_FAC!='NOT OK')
  AND LOWER (DELETED) != 'yes'
  AND LOWER (LOCKEDD) != 'yes'";
  if ($_POST['partner']=='benchmark') {
    $query.=" AND CON='BENCHMARK'";
  }else if ($_POST['partner']=='techm') {
    $query.=" AND CON!='BENCHMARK'";
  }
  $query.=" GROUP BY
    SUBSTR (SITEID, 0, 2)
  ORDER BY
    SUBSTR (SITEID, 0, 2)
) ab ON z.REGION = ab.REGION
FULL OUTER JOIN (
  SELECT
    SUBSTR (T .SITEID, 0, 2) AS REGION,
    COUNT (SITEID) AS VALREQ_MIS_MS_FAC
  FROM
    BSDS_RAFV2 T
  LEFT JOIN VW_POPR_CON CON ON T .RAFID = CON.RAFID
  WHERE
    PARTNER_VALREQ = 'MISSING MS FOR FAC'
  AND RF_PAC = 'OK'
  AND PARTNER_RFPACK != 'NOT OK'
  AND PARTNER_RFPACK != 'REJECTED'
  AND POPR IS NOT NULL
  AND COF_CON = 'BASE OK'
  AND NET1_FUND != 'NOT OK' /* AND NET1_ACQUIRED!='NOT OK'*/
  AND CON_PARTNER != 'NOT OK'
  AND RADIO_FUND != 'NOT OK'
  AND RADIO_FUND != 'ON HOLD'
  AND RADIO_FUND != 'NO BUDGET'
  AND RADIO_FUND != 'NOT FUNDED'
  AND RADIO_FUND != 'END'
  AND TXMN_ACQUIRED != 'NOT OK'
  AND PARTNER_ACQUIRED != 'NOT OK'
  AND PARTNER_ACQUIRED != 'REJECTED'
  AND NET1_LBP != 'NOT OK'
  AND BCS_NET1 != 'NOT OK'
  AND BCS_NET1 != 'AWAIT SYNC'
  AND BCS_NET1 != 'A304'
  AND BCS_RF_INP != 'NOT OK'
  AND BCS_TX_INP != 'NOT OK'
  AND PARTNER_INP != 'NOT OK'
  AND PARTNER_INP != 'REJECTED'
AND NET1_A304 !='NOT OK'
  AND (
    COF_ACQ = 'BASE OK'
    OR COF_ACQ = 'NA'
  )
  AND NET1_LINK != 'NOT OK'
  AND NET1_LINK != 'END'
  AND NET1_LINK != 'BCS CHANGE'
  AND TXMN_INP != 'NOT OK'
  AND RADIO_INP != 'NOT OK'
  AND ACQ_PARTNER != 'NOT OK'
  AND RADIO_FUND != 'END'
  AND LOWER (DELETED) != 'yes'
  AND LOWER (LOCKEDD) != 'yes'
 AND (NET1_PAC!='NOT OK' OR NET1_FAC!='NOT OK')";
  if ($_POST['partner']=='benchmark') {
    $query.=" AND CON='BENCHMARK'";
  }else if ($_POST['partner']=='techm') {
    $query.=" AND CON!='BENCHMARK'";
  }
  $query.=" GROUP BY
    SUBSTR (SITEID, 0, 2)
  ORDER BY
    SUBSTR (SITEID, 0, 2)
) ac ON z.REGION = ac.REGION
FULL OUTER JOIN (
  SELECT
    SUBSTR (T .SITEID, 0, 2) AS REGION,
    COUNT (SITEID) AS VALREQ_MIS_DOCS_FAC
  FROM
    BSDS_RAFV2 T
  LEFT JOIN VW_POPR_CON CON ON T .RAFID = CON.RAFID
  WHERE
    PARTNER_VALREQ = 'MISSING DOCS FOR FAC'
  AND RF_PAC = 'OK'
  AND PARTNER_RFPACK != 'NOT OK'
  AND PARTNER_RFPACK != 'REJECTED'
  AND POPR IS NOT NULL
  AND COF_CON = 'BASE OK'
  AND NET1_FUND != 'NOT OK' /* AND NET1_ACQUIRED!='NOT OK'*/
  AND CON_PARTNER != 'NOT OK'
  AND RADIO_FUND != 'NOT OK'
  AND RADIO_FUND != 'ON HOLD'
  AND RADIO_FUND != 'NO BUDGET'
  AND RADIO_FUND != 'NOT FUNDED'
  AND RADIO_FUND != 'END'
  AND TXMN_ACQUIRED != 'NOT OK'
  AND PARTNER_ACQUIRED != 'NOT OK'
  AND PARTNER_ACQUIRED != 'REJECTED'
  AND NET1_LBP != 'NOT OK'
  AND BCS_NET1 != 'NOT OK'
  AND BCS_NET1 != 'AWAIT SYNC'
  AND BCS_NET1 != 'A304'
  AND BCS_RF_INP != 'NOT OK'
  AND BCS_TX_INP != 'NOT OK'
  AND PARTNER_INP != 'NOT OK'
  AND PARTNER_INP != 'REJECTED'
AND NET1_A304 !='NOT OK'
  AND (
    COF_ACQ = 'BASE OK'
    OR COF_ACQ = 'NA'
  )
  AND NET1_LINK != 'NOT OK'
  AND NET1_LINK != 'END'
  AND NET1_LINK != 'BCS CHANGE'
  AND TXMN_INP != 'NOT OK'
  AND RADIO_INP != 'NOT OK'
  AND ACQ_PARTNER != 'NOT OK'
  AND RADIO_FUND != 'END'
 AND (NET1_PAC!='NOT OK' OR NET1_FAC!='NOT OK')
  AND LOWER (DELETED) != 'yes'
  AND LOWER (LOCKEDD) != 'yes'";
  if ($_POST['partner']=='benchmark') {
    $query.=" AND CON='BENCHMARK'";
  }else if ($_POST['partner']=='techm') {
    $query.=" AND CON!='BENCHMARK'";
  }
  $query.=" GROUP BY
    SUBSTR (SITEID, 0, 2)
  ORDER BY
    SUBSTR (SITEID, 0, 2)
) ad ON z.REGION = ad.REGION
FULL OUTER JOIN (
  SELECT
    SUBSTR (T .SITEID, 0, 2) AS REGION,
    COUNT (SITEID) AS VALREQ_READY_FAC
  FROM
    BSDS_RAFV2 T
  LEFT JOIN VW_POPR_CON CON ON T .RAFID = CON.RAFID
  WHERE
    PARTNER_VALREQ = 'READY FOR FAC'
  AND RF_PAC = 'OK'
  AND PARTNER_RFPACK != 'NOT OK'
  AND PARTNER_RFPACK != 'REJECTED'
  AND POPR IS NOT NULL
  AND COF_CON = 'BASE OK'
  AND NET1_FUND != 'NOT OK' /* AND NET1_ACQUIRED!='NOT OK'*/
  AND CON_PARTNER != 'NOT OK'
  AND RADIO_FUND != 'NOT OK'
  AND RADIO_FUND != 'ON HOLD'
  AND RADIO_FUND != 'NO BUDGET'
  AND RADIO_FUND != 'NOT FUNDED'
  AND RADIO_FUND != 'END'
  AND TXMN_ACQUIRED != 'NOT OK'
  AND PARTNER_ACQUIRED != 'NOT OK'
  AND PARTNER_ACQUIRED != 'REJECTED'
  AND NET1_LBP != 'NOT OK'
  AND BCS_NET1 != 'NOT OK'
  AND BCS_NET1 != 'AWAIT SYNC'
  AND BCS_NET1 != 'A304'
  AND BCS_RF_INP != 'NOT OK'
  AND BCS_TX_INP != 'NOT OK'
  AND PARTNER_INP != 'NOT OK'
  AND PARTNER_INP != 'REJECTED'
AND NET1_A304 !='NOT OK'
  AND (
    COF_ACQ = 'BASE OK'
    OR COF_ACQ = 'NA'
  )
  AND NET1_LINK != 'NOT OK'
  AND NET1_LINK != 'END'
  AND NET1_LINK != 'BCS CHANGE'
  AND TXMN_INP != 'NOT OK'
  AND RADIO_INP != 'NOT OK'
  AND ACQ_PARTNER != 'NOT OK'
  AND RADIO_FUND != 'END'
  AND LOWER (DELETED) != 'yes'
  AND LOWER (LOCKEDD) != 'yes'";
  if ($_POST['partner']=='benchmark') {
    $query.=" AND CON='BENCHMARK'";
  }else if ($_POST['partner']=='techm') {
    $query.=" AND CON!='BENCHMARK'";
  }
  $query.=" GROUP BY
    SUBSTR (SITEID, 0, 2)
  ORDER BY
    SUBSTR (SITEID, 0, 2)
) ae ON z.REGION = ae.REGION
FULL OUTER JOIN (
  SELECT
    SUBSTR (T .SITEID, 0, 2) AS REGION,
    COUNT (SITEID) AS VALREQ_READY_PAC_FAC
  FROM
    BSDS_RAFV2 T
  LEFT JOIN VW_POPR_CON CON ON T .RAFID = CON.RAFID
  WHERE
    PARTNER_VALREQ = 'READY FOR PAC&FAC'
  AND RF_PAC = 'OK'
  AND PARTNER_RFPACK != 'NOT OK'
  AND PARTNER_RFPACK != 'REJECTED'
  AND POPR IS NOT NULL
  AND COF_CON = 'BASE OK'
  AND NET1_FUND != 'NOT OK' /* AND NET1_ACQUIRED!='NOT OK'*/
  AND CON_PARTNER != 'NOT OK'
  AND RADIO_FUND != 'NOT OK'
  AND RADIO_FUND != 'ON HOLD'
  AND RADIO_FUND != 'NO BUDGET'
  AND RADIO_FUND != 'NOT FUNDED'
  AND RADIO_FUND != 'END'
  AND TXMN_ACQUIRED != 'NOT OK'
  AND PARTNER_ACQUIRED != 'NOT OK'
  AND PARTNER_ACQUIRED != 'REJECTED'
  AND NET1_LBP != 'NOT OK'
  AND BCS_NET1 != 'NOT OK'
  AND BCS_NET1 != 'AWAIT SYNC'
  AND BCS_NET1 != 'A304'
  AND BCS_RF_INP != 'NOT OK'
  AND BCS_TX_INP != 'NOT OK'
  AND PARTNER_INP != 'NOT OK'
  AND PARTNER_INP != 'REJECTED'
AND NET1_A304 !='NOT OK'
  AND (
    COF_ACQ = 'BASE OK'
    OR COF_ACQ = 'NA'
  )
  AND NET1_LINK != 'NOT OK'
  AND NET1_LINK != 'END'
  AND NET1_LINK != 'BCS CHANGE'
  AND TXMN_INP != 'NOT OK'
  AND RADIO_INP != 'NOT OK'
  AND ACQ_PARTNER != 'NOT OK'
  AND RADIO_FUND != 'END'
  AND LOWER (DELETED) != 'yes'
  AND LOWER (LOCKEDD) != 'yes'";
  if ($_POST['partner']=='benchmark') {
    $query.=" AND CON='BENCHMARK'";
  }else if ($_POST['partner']=='techm') {
    $query.=" AND CON!='BENCHMARK'";
  }
  $query.=" GROUP BY
    SUBSTR (SITEID, 0, 2)
  ORDER BY
    SUBSTR (SITEID, 0, 2)
) af ON z.REGION = af.REGION
FULL OUTER JOIN (
  SELECT
    SUBSTR (T .SITEID, 0, 2) AS REGION,
    COUNT (SITEID) AS NET1_FAC
  FROM
    BSDS_RAFV2 T
  LEFT JOIN VW_POPR_CON CON ON T .RAFID = CON.RAFID
  WHERE
    NET1_FAC = 'NOT OK'
  AND (
    PARTNER_VALREQ = 'READY FOR PAC&FAC'
    OR PARTNER_VALREQ = 'READY FOR FAC'
  )
  AND RF_PAC = 'OK'
  AND PARTNER_RFPACK != 'NOT OK'
  AND PARTNER_RFPACK != 'REJECTED'
  AND POPR IS NOT NULL
  AND COF_CON = 'BASE OK'
  AND NET1_FUND != 'NOT OK' /* AND NET1_ACQUIRED!='NOT OK'*/
  AND CON_PARTNER != 'NOT OK'
  AND RADIO_FUND != 'NOT OK'
  AND RADIO_FUND != 'ON HOLD'
  AND RADIO_FUND != 'NO BUDGET'
  AND RADIO_FUND != 'NOT FUNDED'
  AND RADIO_FUND != 'END'
  AND TXMN_ACQUIRED != 'NOT OK'
  AND PARTNER_ACQUIRED != 'NOT OK'
  AND PARTNER_ACQUIRED != 'REJECTED'
  AND NET1_LBP != 'NOT OK'
  AND BCS_NET1 != 'NOT OK'
  AND BCS_NET1 != 'AWAIT SYNC'
  AND BCS_NET1 != 'A304'
  AND BCS_RF_INP != 'NOT OK'
  AND BCS_TX_INP != 'NOT OK'
  AND PARTNER_INP != 'NOT OK'
  AND PARTNER_INP != 'REJECTED'
AND NET1_A304 !='NOT OK'
  AND (
    COF_ACQ = 'BASE OK'
    OR COF_ACQ = 'NA'
  )
  AND NET1_LINK != 'NOT OK'
  AND NET1_LINK != 'END'
  AND NET1_LINK != 'BCS CHANGE'
  AND TXMN_INP != 'NOT OK'
  AND RADIO_INP != 'NOT OK'
  AND ACQ_PARTNER != 'NOT OK'
  AND RADIO_FUND != 'END'
  AND LOWER (DELETED) != 'yes'
  AND LOWER (LOCKEDD) != 'yes'";
  if ($_POST['partner']=='benchmark') {
    $query.=" AND CON='BENCHMARK'";
  }else if ($_POST['partner']=='techm') {
    $query.=" AND CON!='BENCHMARK'";
  }
  $query.=" GROUP BY
    SUBSTR (SITEID, 0, 2)
  ORDER BY
    SUBSTR (SITEID, 0, 2)
) ag ON z.REGION = ag.REGION
FULL OUTER JOIN (
  SELECT
    SUBSTR (T .SITEID, 0, 2) AS REGION,
    COUNT (SITEID) AS NET1_PAC
  FROM
    BSDS_RAFV2 T
  LEFT JOIN VW_POPR_CON CON ON T .RAFID = CON.RAFID
  WHERE
    NET1_PAC = 'NOT OK'
  AND (
    PARTNER_VALREQ = 'READY FOR PAC&FAC'
    OR PARTNER_VALREQ = 'READY FOR PAC'
  )
  AND RF_PAC = 'OK'
  AND PARTNER_RFPACK != 'NOT OK'
  AND PARTNER_RFPACK != 'REJECTED'
  AND POPR IS NOT NULL
  AND COF_CON = 'BASE OK'
  AND NET1_FUND != 'NOT OK' /* AND NET1_ACQUIRED!='NOT OK'*/
  AND CON_PARTNER != 'NOT OK'
  AND RADIO_FUND != 'NOT OK'
  AND RADIO_FUND != 'ON HOLD'
  AND RADIO_FUND != 'NO BUDGET'
  AND RADIO_FUND != 'NOT FUNDED'
  AND RADIO_FUND != 'END'
  AND TXMN_ACQUIRED != 'NOT OK'
  AND PARTNER_ACQUIRED != 'NOT OK'
  AND PARTNER_ACQUIRED != 'REJECTED'
  AND NET1_LBP != 'NOT OK'
  AND BCS_NET1 != 'NOT OK'
  AND BCS_NET1 != 'AWAIT SYNC'
  AND BCS_NET1 != 'A304'
  AND BCS_RF_INP != 'NOT OK'
  AND BCS_TX_INP != 'NOT OK'
  AND PARTNER_INP != 'NOT OK'
  AND PARTNER_INP != 'REJECTED'
AND NET1_A304 !='NOT OK'
  AND (
    COF_ACQ = 'BASE OK'
    OR COF_ACQ = 'NA'
  )
  AND NET1_LINK != 'NOT OK'
  AND NET1_LINK != 'END'
  AND NET1_LINK != 'BCS CHANGE'
  AND TXMN_INP != 'NOT OK'
  AND RADIO_INP != 'NOT OK'
  AND ACQ_PARTNER != 'NOT OK'
  AND RADIO_FUND != 'END'
  AND LOWER (DELETED) != 'yes'
  AND LOWER (LOCKEDD) != 'yes'";
  if ($_POST['partner']=='benchmark') {
    $query.=" AND CON='BENCHMARK'";
  }else if ($_POST['partner']=='techm') {
    $query.=" AND CON!='BENCHMARK'";
  }
  $query.=" GROUP BY
    SUBSTR (SITEID, 0, 2)
  ORDER BY
    SUBSTR (SITEID, 0, 2)
) ah ON z.REGION = ah.REGION
UNION ALL
  (
    SELECT
      'TOTALS' AS TOTALS,
      RADIO_INP,
      TXMN_INP,
      ACQ_PARTNER,
      NET1_LINK,
      COF_ACQ_PARTNER,
      COF_ACQ_BASE,
      PO_ACQ,
      PARTNER_INP,
      PARTNER_A304,
      BCS_RF_INP,
      BCS_TX_INP,
      BCS_A15,
      NET1_LBP,
      PARTNER_ACQUIRED,
      TXMN_ACQUIRED,
      NET1_ACQUIRED,
      RADIO_BLOCKED_FUND,
      RADIO_FUND,
      CON_PARTNER,
      NET1_FUND,
      COF_CON_PARTNER,
      COF_CON_BASE_TS,
      COF_CON_BASE_PM,
      PO_CON,
      PARTNER_RFPACK,
      RADIO_RFPAC,
      VALREQ_REJECTED,
      VALREQ_MIS_MS_PAC,
      VALREQ_MIS_DOCS_PAC,
      VALREQ_READY_PAC,
      VALREQ_MIS_MS_DOCS_PAC,
      VALREQ_MIS_MS_FAC,
      VALREQ_READY_FAC,
      VALREQ_READY_PAC_FAC,
      NET1_FAC,
      NET1_PAC
    FROM
      (
        SELECT
          'TOTALS' AS TOTALS,
          COUNT (RADIO_INP) AS RADIO_INP
        FROM
          BSDS_RAFV2
        WHERE
          RADIO_INP = 'NOT OK'
        AND LOWER (DELETED) != 'yes'
        AND LOWER (LOCKEDD) != 'yes'
      ) z
    FULL OUTER JOIN (
      SELECT
        'TOTALS' AS TOTALS,
        COUNT (TXMN_INP) AS TXMN_INP
      FROM
        BSDS_RAFV2
      WHERE
        TXMN_INP = 'NOT OK'
      AND RADIO_INP != 'NOT OK'
      AND LOWER (DELETED) != 'yes'
      AND LOWER (LOCKEDD) != 'yes'";
   if ($_POST['partner']=='benchmark') {
    $query.=" AND SAC='BENCHMARK'";
  }else  if ($_POST['partner']=='techm') {
    $query.=" AND SAC!='BENCHMARK'";
  }
  $query.=" 
    ) b ON z.TOTALS = b.TOTALS
    FULL OUTER JOIN (
      SELECT
        'TOTALS' AS TOTALS,
        COUNT (ACQ_PARTNER) AS ACQ_PARTNER
      FROM
        BSDS_RAFV2
      WHERE
        ACQ_PARTNER = 'NOT OK'
      AND TXMN_INP != 'NOT OK'
      AND RADIO_INP!='REJECTED'
      AND BUFFER != 1
      AND LOWER (DELETED) != 'yes'
      AND LOWER (LOCKEDD) != 'yes'";
   if ($_POST['partner']=='benchmark') {
    $query.=" AND SAC='BENCHMARK'";
  }else  if ($_POST['partner']=='techm') {
    $query.=" AND SAC!='BENCHMARK'";
  }
  $query.="
    ) c ON z.TOTALS = c.TOTALS
    FULL OUTER JOIN (
      SELECT
        'TOTALS' AS TOTALS,
        COUNT (NET1_LINK) AS NET1_LINK
      FROM
        BSDS_RAFV2
      WHERE
        (
          NET1_LINK = 'NOT OK'
          OR TRIM (NET1_LINK) IS NULL
          OR NET1_LINK = 'BCS CHANGE'
        )
      AND TXMN_INP != 'NOT OK'
      AND ACQ_PARTNER != 'NOT OK'
      AND LOWER (DELETED) != 'yes'
      AND LOWER (LOCKEDD) != 'yes'";
   if ($_POST['partner']=='benchmark') {
    $query.=" AND SAC='BENCHMARK'";
  }else  if ($_POST['partner']=='techm') {
    $query.=" AND SAC!='BENCHMARK'";
  }
  $query.="
    ) D ON z.TOTALS = D .TOTALS
    FULL OUTER JOIN (
      SELECT
        'TOTALS' AS TOTALS,
        COUNT (SITEID) AS COF_ACQ_PARTNER
      FROM
        BSDS_RAFV2
      WHERE
        COF_ACQ = 'NOT OK'
      AND NET1_LINK != 'NOT OK'
      AND NET1_LINK != 'END'
      AND NET1_LINK != 'BCS CHANGE'
      AND TXMN_INP != 'NOT OK'
      AND RADIO_INP != 'NOT OK'
      AND ACQ_PARTNER != 'NOT OK'
      AND (
        TYPE = 'MOV Upgrade'
        OR TYPE = 'IND Upgrade'
        OR TYPE = 'RPT Upgrade'
        OR TYPE = 'CWK Upgrade'
        OR TYPE = 'New Indoor'
      )
      AND LOWER (DELETED) != 'yes'
      AND LOWER (LOCKEDD) != 'yes'";
   if ($_POST['partner']=='benchmark') {
    $query.=" AND SAC='BENCHMARK'";
  }else  if ($_POST['partner']=='techm') {
    $query.=" AND SAC!='BENCHMARK'";
  }
  $query.="
    ) E ON z.TOTALS = E .TOTALS
    FULL OUTER JOIN (
      SELECT
        'TOTALS' AS TOTALS,
        COUNT (SITEID) AS COF_ACQ_BASE
      FROM
        BSDS_RAFV2
      WHERE
        (COF_ACQ='PARTNER OK' OR (COF_ACQ='NOT OK' AND TYPE!='MOV Upgrade' AND TYPE!='IND Upgrade' AND TYPE!='RPT Upgrade' AND TYPE!='CWK Upgrade' AND TYPE!='New Indoor'))
      AND NET1_LINK != 'NOT OK'
      AND NET1_LINK != 'END'
      AND NET1_LINK != 'BCS CHANGE'
      AND TXMN_INP != 'NOT OK'
      AND RADIO_INP != 'NOT OK'
      AND ACQ_PARTNER != 'NOT OK'
      AND LOWER (DELETED) != 'yes'
      AND LOWER (LOCKEDD) != 'yes'";
   if ($_POST['partner']=='benchmark') {
    $query.=" AND SAC='BENCHMARK'";
  }else  if ($_POST['partner']=='techm') {
    $query.=" AND SAC!='BENCHMARK'";
  }
  $query.="
    ) f ON z.TOTALS = f.TOTALS
    FULL OUTER JOIN (
      SELECT
        'TOTALS' AS TOTALS,
        COUNT (PARTNER_INP) AS PO_ACQ
      FROM
        BSDS_RAFV2 T
      LEFT JOIN VW_POPR_ACQ ACQ ON T .RAFID = ACQ.RAFID
      WHERE
        (ACQ.POPR IS NULL AND BUFFER != 1  AND TYPE!='New Indoor')
      AND (
        COF_ACQ = 'BASE OK'
        OR COF_ACQ = 'NA'
      )
      AND NET1_LINK != 'NOT OK'
      AND NET1_LINK != 'END'
      AND NET1_LINK != 'BCS CHANGE'
      AND TXMN_INP != 'NOT OK'
      AND RADIO_INP != 'NOT OK'
      AND ACQ_PARTNER != 'NOT OK'
      AND LOWER (DELETED) != 'yes'
      AND LOWER (LOCKEDD) != 'yes'";
   if ($_POST['partner']=='benchmark') {
    $query.=" AND SAC='BENCHMARK'";
  }else  if ($_POST['partner']=='techm') {
    $query.=" AND SAC!='BENCHMARK'";
  }
  $query.="
    ) az ON z.TOTALS = az.TOTALS
    FULL OUTER JOIN (
      SELECT
        'TOTALS' AS TOTALS,
        COUNT (PARTNER_INP) AS PARTNER_INP
      FROM
        BSDS_RAFV2 T
      LEFT JOIN VW_POPR_ACQ ACQ ON T .RAFID = ACQ.RAFID
      WHERE
        PARTNER_INP = 'NOT OK'
      AND (
        ACQ.POPR IS NOT NULL
        OR BUFFER = 1 OR TYPE='New Indoor'
      )
      AND (
        COF_ACQ = 'BASE OK'
        OR COF_ACQ = 'NA'
      )
      AND NET1_LINK != 'NOT OK'
      AND NET1_LINK != 'END'
      AND NET1_LINK != 'BCS CHANGE'
      AND TXMN_INP != 'NOT OK'
      AND RADIO_INP != 'NOT OK'
      AND ACQ_PARTNER != 'NOT OK'
      AND LOWER (DELETED) != 'yes'
      AND LOWER (LOCKEDD) != 'yes'";
   if ($_POST['partner']=='benchmark') {
    $query.=" AND SAC='BENCHMARK'";
  }else  if ($_POST['partner']=='techm') {
    $query.=" AND SAC!='BENCHMARK'";
  }
  $query.="
    ) G ON z.TOTALS = G .TOTALS
FULL OUTER JOIN (
      SELECT
        'TOTALS' AS TOTALS,
        COUNT (NET1_A304) AS PARTNER_A304
      FROM
        BSDS_RAFV2 T
      LEFT JOIN VW_POPR_ACQ ACQ ON T .RAFID = ACQ.RAFID
      WHERE
        NET1_A304 = 'NOT OK'
      AND (
        ACQ.POPR IS NOT NULL
        OR BUFFER = 1 OR TYPE='New Indoor'
      )
      AND (
        COF_ACQ = 'BASE OK'
        OR COF_ACQ = 'NA'
      )
      AND NET1_LINK != 'NOT OK'
      AND NET1_LINK != 'END'
      AND NET1_LINK != 'BCS CHANGE'
      AND TXMN_INP != 'NOT OK'
      AND RADIO_INP != 'NOT OK'
AND PARTNER_INP = 'OK'
      AND ACQ_PARTNER != 'NOT OK'
      AND LOWER (DELETED) != 'yes'
      AND LOWER (LOCKEDD) != 'yes'";
   if ($_POST['partner']=='benchmark') {
    $query.=" AND SAC='BENCHMARK'";
  }else  if ($_POST['partner']=='techm') {
    $query.=" AND SAC!='BENCHMARK'";
  }
  $query.="
    ) Ga ON z.TOTALS = Ga .TOTALS
    FULL OUTER JOIN (
      SELECT
        'TOTALS' AS TOTALS,
        COUNT (SITEID) AS BCS_RF_INP
      FROM
        BSDS_RAFV2 T
      LEFT JOIN VW_POPR_ACQ ACQ ON T .RAFID = ACQ.RAFID
      WHERE
        BCS_RF_INP = 'NOT OK'
      AND PARTNER_INP != 'NOT OK'
      AND (
        ACQ.POPR IS NOT NULL
        OR BUFFER = 1 OR TYPE='New Indoor'
      )
      AND PARTNER_INP != 'REJECTED'
AND NET1_A304 !='NOT OK'
      AND (
        COF_ACQ = 'BASE OK'
        OR COF_ACQ = 'NA'
      )
      AND NET1_LINK != 'NOT OK'
      AND NET1_LINK != 'END'
      AND NET1_LINK != 'BCS CHANGE'
      AND TXMN_INP != 'NOT OK'
      AND RADIO_INP != 'NOT OK'
      AND ACQ_PARTNER != 'NOT OK'
      AND LOWER (DELETED) != 'yes'
      AND LOWER (LOCKEDD) != 'yes'";
   if ($_POST['partner']=='benchmark') {
    $query.=" AND SAC='BENCHMARK'";
  }else  if ($_POST['partner']=='techm') {
    $query.=" AND SAC!='BENCHMARK'";
  }
  $query.="
    ) i ON z.TOTALS = i.TOTALS
    FULL OUTER JOIN (
      SELECT
        'TOTALS' AS TOTALS,
        COUNT (SITEID) AS BCS_TX_INP
      FROM
        BSDS_RAFV2 T
      LEFT JOIN VW_POPR_ACQ ACQ ON T .RAFID = ACQ.RAFID
      WHERE
        BCS_TX_INP = 'NOT OK'
      AND PARTNER_INP != 'NOT OK'
      AND PARTNER_INP != 'REJECTED'
AND NET1_A304 !='NOT OK'
      AND (
        ACQ.POPR IS NOT NULL
        OR BUFFER = 1 OR TYPE='New Indoor'
      )
      AND (
        COF_ACQ = 'BASE OK'
        OR COF_ACQ = 'NA'
      )
      AND NET1_LINK != 'NOT OK'
      AND NET1_LINK != 'END'
      AND NET1_LINK != 'BCS CHANGE'
      AND TXMN_INP != 'NOT OK'
      AND RADIO_INP != 'NOT OK'
      AND ACQ_PARTNER != 'NOT OK'
      AND LOWER (DELETED) != 'yes'
      AND LOWER (LOCKEDD) != 'yes'";
   if ($_POST['partner']=='benchmark') {
    $query.=" AND SAC='BENCHMARK'";
  }else  if ($_POST['partner']=='techm') {
    $query.=" AND SAC!='BENCHMARK'";
  }
  $query.="
    ) i2 ON z.TOTALS = i2.TOTALS
    FULL OUTER JOIN (
      SELECT
        'TOTALS' AS TOTALS,
        COUNT (SITEID) AS BCS_A15
      FROM
        BSDS_RAFV2 T
      LEFT JOIN VW_POPR_ACQ ACQ ON T .RAFID = ACQ.RAFID
      WHERE
        (
          BCS_NET1 = 'NOT OK'
          OR BCS_NET1 = 'AWAIT SYNC'
          OR BCS_NET1 = 'A304'
        )
      AND BCS_RF_INP != 'NOT OK'
      AND BCS_TX_INP != 'NOT OK'
      AND PARTNER_INP != 'NOT OK'
      AND PARTNER_INP != 'REJECTED'
AND NET1_A304 !='NOT OK'
      AND (
        ACQ.POPR IS NOT NULL
        OR BUFFER = 1 OR TYPE='New Indoor'
      )
      AND (
        COF_ACQ = 'BASE OK'
        OR COF_ACQ = 'NA'
      )
      AND NET1_LINK != 'NOT OK'
      AND NET1_LINK != 'END'
      AND NET1_LINK != 'BCS CHANGE'
      AND TXMN_INP != 'NOT OK'
      AND RADIO_INP != 'NOT OK'
      AND ACQ_PARTNER != 'NOT OK'
      AND LOWER (DELETED) != 'yes'
      AND LOWER (LOCKEDD) != 'yes'";
   if ($_POST['partner']=='benchmark') {
    $query.=" AND SAC='BENCHMARK'";
  }else  if ($_POST['partner']=='techm') {
    $query.=" AND SAC!='BENCHMARK'";
  }
  $query.="
    ) j ON z.TOTALS = j.TOTALS
    FULL OUTER JOIN (
      SELECT
        'TOTALS' AS TOTALS,
        COUNT (SITEID) AS NET1_LBP
      FROM
        BSDS_RAFV2 T
      LEFT JOIN VW_POPR_ACQ ACQ ON T .RAFID = ACQ.RAFID
      WHERE
        NET1_LBP = 'NOT OK'
      AND BUFFER = 0
      AND BCS_NET1 != 'NOT OK'
      AND BCS_NET1 != 'AWAIT SYNC'
      AND BCS_NET1 != 'A304'
      AND BCS_RF_INP != 'NOT OK'
      AND BCS_TX_INP != 'NOT OK'
      AND PARTNER_INP != 'NOT OK'
      AND PARTNER_INP != 'REJECTED'
AND NET1_A304 !='NOT OK'
      AND (
        ACQ.POPR IS NOT NULL
        OR BUFFER = 1 OR TYPE='New Indoor'
      )
      AND (
        COF_ACQ = 'BASE OK'
        OR COF_ACQ = 'NA'
      )
      AND NET1_LINK != 'NOT OK'
      AND NET1_LINK != 'END'
      AND NET1_LINK != 'BCS CHANGE'
      AND TXMN_INP != 'NOT OK'
      AND RADIO_INP != 'NOT OK'
      AND RADIO_INP != 'NOT OK'
      AND ACQ_PARTNER != 'NOT OK'
      AND RADIO_FUND != 'END'
      AND NET1_LINK != 'BCS CHANGE'
      AND LOWER (DELETED) != 'yes'
      AND LOWER (LOCKEDD) != 'yes'";
   if ($_POST['partner']=='benchmark') {
    $query.=" AND SAC='BENCHMARK'";
  }else  if ($_POST['partner']=='techm') {
    $query.=" AND SAC!='BENCHMARK'";
  }
  $query.="
    ) K ON z.TOTALS = K .TOTALS
    FULL OUTER JOIN (
      SELECT
        'TOTALS' AS TOTALS,
        COUNT (SITEID) AS PARTNER_ACQUIRED
      FROM
        BSDS_RAFV2 T
      LEFT JOIN VW_POPR_ACQ ACQ ON T .RAFID = ACQ.RAFID
      WHERE
        (
          PARTNER_ACQUIRED = 'NOT OK'
          OR PARTNER_ACQUIRED = 'REJECTED'
          OR PARTNER_ACQUIRED = 'AWAITING NET1'
        )
      AND NET1_LBP != 'NOT OK'
      AND BCS_NET1 != 'NOT OK'
      AND BCS_NET1 != 'AWAIT SYNC'
      AND BCS_NET1 != 'A304'
      AND BCS_RF_INP != 'NOT OK'
      AND BCS_TX_INP != 'NOT OK'
      AND PARTNER_INP != 'NOT OK'
      AND PARTNER_INP != 'REJECTED'
AND NET1_A304 !='NOT OK'
      AND (
        ACQ.POPR IS NOT NULL
        OR BUFFER = 1 OR TYPE='New Indoor'
      )
      AND (
        COF_ACQ = 'BASE OK'
        OR COF_ACQ = 'NA'
      )
      AND NET1_LINK != 'NOT OK'
      AND NET1_LINK != 'END'
      AND NET1_LINK != 'BCS CHANGE'
      AND TXMN_INP != 'NOT OK'
      AND RADIO_INP != 'NOT OK'
      AND ACQ_PARTNER != 'NOT OK'
      AND RADIO_FUND != 'END'
      AND NET1_LINK != 'BCS CHANGE'
      AND LOWER (DELETED) != 'yes'
      AND LOWER (LOCKEDD) != 'yes'";
   if ($_POST['partner']=='benchmark') {
    $query.=" AND SAC='BENCHMARK'";
  }else  if ($_POST['partner']=='techm') {
    $query.=" AND SAC!='BENCHMARK'";
  }
  $query.="
      AND BUFFER != 1
    ) l ON z.TOTALS = l.TOTALS
    FULL OUTER JOIN (
      SELECT
        'TOTALS' AS TOTALS,
        COUNT (SITEID) AS TXMN_ACQUIRED
      FROM
        BSDS_RAFV2 T
      LEFT JOIN VW_POPR_ACQ ACQ ON T .RAFID = ACQ.RAFID
      WHERE
        TXMN_ACQUIRED = 'NOT OK'
      AND PARTNER_ACQUIRED != 'NOT OK'
      AND PARTNER_ACQUIRED != 'REJECTED'
      AND NET1_LBP != 'NOT OK'
      AND BCS_NET1 != 'NOT OK'
      AND BCS_NET1 != 'AWAIT SYNC'
      AND BCS_NET1 != 'A304'
      AND BCS_RF_INP != 'NOT OK'
      AND BCS_TX_INP != 'NOT OK'
      AND PARTNER_INP != 'NOT OK'
      AND PARTNER_INP != 'REJECTED'
AND NET1_A304 !='NOT OK'
      AND (
        ACQ.POPR IS NOT NULL
        OR BUFFER = 1 OR TYPE='New Indoor'
      )
      AND (
        COF_ACQ = 'BASE OK'
        OR COF_ACQ = 'NA'
      )
      AND NET1_LINK != 'NOT OK'
      AND NET1_LINK != 'END'
      AND NET1_LINK != 'BCS CHANGE'
      AND TXMN_INP != 'NOT OK'
      AND RADIO_INP != 'NOT OK'
      AND ACQ_PARTNER != 'NOT OK'
      AND RADIO_FUND != 'END'
      AND NET1_LINK != 'BCS CHANGE'
      AND LOWER (DELETED) != 'yes'
      AND LOWER (LOCKEDD) != 'yes'";
   if ($_POST['partner']=='benchmark') {
    $query.=" AND SAC='BENCHMARK'";
  }else  if ($_POST['partner']=='techm') {
    $query.=" AND SAC!='BENCHMARK'";
  }
  $query.="
    ) M ON z.TOTALS = M .TOTALS
    FULL OUTER JOIN (
      SELECT
        'TOTALS' AS TOTALS,
        COUNT (SITEID) AS NET1_ACQUIRED
      FROM
        BSDS_RAFV2 T
      LEFT JOIN VW_POPR_ACQ ACQ ON T .RAFID = ACQ.RAFID
      WHERE
        NET1_ACQUIRED = 'NOT OK'
      AND TXMN_ACQUIRED != 'NOT OK'
      AND PARTNER_ACQUIRED != 'NOT OK'
      AND PARTNER_ACQUIRED != 'REJECTED'
      AND NET1_LBP != 'NOT OK'
      AND BCS_NET1 != 'NOT OK'
      AND BCS_NET1 != 'AWAIT SYNC'
      AND BCS_NET1 != 'A304'
      AND BCS_RF_INP != 'NOT OK'
      AND BCS_TX_INP != 'NOT OK'
      AND PARTNER_INP != 'NOT OK'
      AND PARTNER_INP != 'REJECTED'
AND NET1_A304 !='NOT OK'
      AND (
        ACQ.POPR IS NOT NULL
        OR BUFFER = 1 OR TYPE='New Indoor'
      )
      AND (
        COF_ACQ = 'BASE OK'
        OR COF_ACQ = 'NA'
      )
      AND NET1_LINK != 'NOT OK'
      AND NET1_LINK != 'END'
      AND NET1_LINK != 'BCS CHANGE'
      AND TXMN_INP != 'NOT OK'
      AND ACQ_PARTNER != 'NOT OK'
      AND RADIO_FUND != 'END'
      AND LOWER (DELETED) != 'yes'
      AND LOWER (LOCKEDD) != 'yes'";
   if ($_POST['partner']=='benchmark') {
    $query.=" AND SAC='BENCHMARK'";
  }else  if ($_POST['partner']=='techm') {
    $query.=" AND SAC!='BENCHMARK'";
  }
  $query.="
    ) n ON z.TOTALS = n.TOTALS
    FULL OUTER JOIN (
      SELECT
        'TOTALS' AS TOTALS,
        COUNT (SITEID) AS RADIO_BLOCKED_FUND
      FROM
        BSDS_RAFV2
      WHERE
        (
          RADIO_FUND = 'NO BUDGET'
          OR RADIO_FUND = 'ON HOLD'
        )
      AND TXMN_ACQUIRED != 'NOT OK'
      AND PARTNER_ACQUIRED != 'NOT OK'
      AND PARTNER_ACQUIRED != 'REJECTED'
      AND NET1_LBP != 'NOT OK'
      AND BCS_NET1 != 'NOT OK'
      AND BCS_NET1 != 'AWAIT SYNC'
      AND BCS_NET1 != 'A304'
      AND BCS_RF_INP != 'NOT OK'
      AND BCS_TX_INP != 'NOT OK'
      AND PARTNER_INP != 'NOT OK'
      AND PARTNER_INP != 'REJECTED'
AND NET1_A304 !='NOT OK'
      AND (
        COF_ACQ = 'BASE OK'
        OR COF_ACQ = 'NA'
      )
      AND NET1_LINK != 'NOT OK'
      AND NET1_LINK != 'END'
      AND NET1_LINK != 'BCS CHANGE'
      AND TXMN_INP != 'NOT OK'
      AND RADIO_INP != 'NOT OK'
      AND ACQ_PARTNER != 'NOT OK'
      AND RADIO_FUND != 'END'
      AND LOWER (DELETED) != 'yes'
      AND LOWER (LOCKEDD) != 'yes'";
  if ($_POST['partner']=='benchmark') {
    $query.=" AND CON='BENCHMARK'";
  }else if ($_POST['partner']=='techm') {
    $query.=" AND CON!='BENCHMARK'";
  }
  $query.="
    ) o2 ON z.TOTALS = o2.TOTALS
    FULL OUTER JOIN (
      SELECT
        'TOTALS' AS TOTALS,
        COUNT (SITEID) AS RADIO_FUND
      FROM
        BSDS_RAFV2
      WHERE
        RADIO_FUND = 'NOT OK'
      AND TXMN_ACQUIRED != 'NOT OK'
      AND PARTNER_ACQUIRED != 'NOT OK'
      AND PARTNER_ACQUIRED != 'REJECTED'
      AND NET1_LBP != 'NOT OK'
      AND BCS_NET1 != 'NOT OK'
      AND BCS_NET1 != 'AWAIT SYNC'
      AND BCS_NET1 != 'A304'
      AND BCS_RF_INP != 'NOT OK'
      AND BCS_TX_INP != 'NOT OK'
      AND PARTNER_INP != 'NOT OK'
      AND PARTNER_INP != 'REJECTED'
AND NET1_A304 !='NOT OK'
      AND (
        COF_ACQ = 'BASE OK'
        OR COF_ACQ = 'NA'
      )
      AND NET1_LINK != 'NOT OK'
      AND NET1_LINK != 'END'
      AND NET1_LINK != 'BCS CHANGE'
      AND TXMN_INP != 'NOT OK'
      AND RADIO_INP != 'NOT OK'
      AND ACQ_PARTNER != 'NOT OK'
      AND RADIO_FUND != 'END'
      AND LOWER (DELETED) != 'yes'
      AND LOWER (LOCKEDD) != 'yes'";
  if ($_POST['partner']=='benchmark') {
    $query.=" AND CON='BENCHMARK'";
  }else if ($_POST['partner']=='techm') {
    $query.=" AND CON!='BENCHMARK'";
  }
  $query.="
    ) o ON z.TOTALS = o.TOTALS
    FULL OUTER JOIN (
      SELECT
        'TOTALS' AS TOTALS,
        COUNT (SITEID) AS CON_PARTNER
      FROM
        BSDS_RAFV2
      WHERE
        CON_PARTNER = 'NOT OK'
      AND RADIO_FUND != 'NOT OK'
      AND RADIO_FUND != 'ON HOLD'
      AND RADIO_FUND != 'NO BUDGET'
      AND RADIO_FUND != 'END'
      AND RADIO_FUND != 'NOT FUNDED'
      AND TXMN_ACQUIRED != 'NOT OK'
      AND PARTNER_ACQUIRED != 'NOT OK'
      AND PARTNER_ACQUIRED != 'REJECTED'
      AND NET1_LBP != 'NOT OK'
      AND BCS_NET1 != 'NOT OK'
      AND BCS_NET1 != 'AWAIT SYNC'
      AND BCS_NET1 != 'A304'
      AND BCS_RF_INP != 'NOT OK'
      AND BCS_TX_INP != 'NOT OK'
      AND PARTNER_INP != 'NOT OK'
      AND PARTNER_INP != 'REJECTED'
AND NET1_A304 !='NOT OK'
      AND (
        COF_ACQ = 'BASE OK'
        OR COF_ACQ = 'NA' 
      )
      AND NET1_LINK != 'NOT OK'
      AND NET1_LINK != 'END'
      AND NET1_LINK != 'BCS CHANGE'
      AND TXMN_INP != 'NOT OK'
      AND RADIO_INP != 'NOT OK'
      AND ACQ_PARTNER != 'NOT OK'
      AND RADIO_FUND != 'END'
      AND LOWER (DELETED) != 'yes'
      AND LOWER (LOCKEDD) != 'yes'";
  if ($_POST['partner']=='benchmark') {
    $query.=" AND CON='BENCHMARK'";
  }else if ($_POST['partner']=='techm') {
    $query.=" AND CON!='BENCHMARK'";
  }
  $query.="
    ) P ON z.TOTALS = P .TOTALS
    FULL OUTER JOIN (
      SELECT
        'TOTALS' AS TOTALS,
        COUNT (SITEID) AS NET1_FUND
      FROM
        BSDS_RAFV2
      WHERE
        NET1_FUND = 'NOT OK'
      AND CON_PARTNER != 'NOT OK'
      AND RADIO_FUND != 'NOT OK'
      AND RADIO_FUND != 'ON HOLD'
      AND RADIO_FUND != 'NO BUDGET'
      AND RADIO_FUND != 'NOT FUNDED'
      AND RADIO_FUND != 'END'
      AND TXMN_ACQUIRED != 'NOT OK'
      AND PARTNER_ACQUIRED != 'NOT OK'
      AND PARTNER_ACQUIRED != 'REJECTED'
      AND NET1_LBP != 'NOT OK'
      AND BCS_NET1 != 'NOT OK'
      AND BCS_NET1 != 'AWAIT SYNC'
      AND BCS_NET1 != 'A304'
      AND BCS_RF_INP != 'NOT OK'
      AND BCS_TX_INP != 'NOT OK'
      AND PARTNER_INP != 'NOT OK'
      AND PARTNER_INP != 'REJECTED'
AND NET1_A304 !='NOT OK'
      AND (
        COF_ACQ = 'BASE OK'
        OR COF_ACQ = 'NA'
      )
      AND NET1_LINK != 'NOT OK'
      AND NET1_LINK != 'END'
      AND NET1_LINK != 'BCS CHANGE'
      AND TXMN_INP != 'NOT OK'
      AND RADIO_INP != 'NOT OK'
      AND ACQ_PARTNER != 'NOT OK'
      AND RADIO_FUND != 'END'
      AND LOWER (DELETED) != 'yes'
      AND LOWER (LOCKEDD) != 'yes'";
  if ($_POST['partner']=='benchmark') {
    $query.=" AND CON='BENCHMARK'";
  }else if ($_POST['partner']=='techm') {
    $query.=" AND CON!='BENCHMARK'";
  }
  $query.="
    ) q ON z.TOTALS = q.TOTALS
    FULL OUTER JOIN (
      SELECT
        'TOTALS' AS TOTALS,
        COUNT (SITEID) AS COF_CON_PARTNER
      FROM
        BSDS_RAFV2 T
      LEFT JOIN VW_POPR_CON ACQ ON T .RAFID = ACQ.RAFID
      WHERE
        COF_CON = 'NOT OK'
      AND (ACQ.POPR IS NOT NULL OR BUFFER=1 OR TYPE='New Indoor')
      AND CON_PARTNER != 'NOT OK'
      AND RADIO_FUND != 'NOT OK'
      AND RADIO_FUND != 'ON HOLD'
      AND RADIO_FUND != 'NO BUDGET'
      AND RADIO_FUND != 'NOT FUNDED'
      AND RADIO_FUND != 'END'
      AND NET1_FUND != 'NOT OK'
      AND TXMN_ACQUIRED != 'NOT OK'
      AND PARTNER_ACQUIRED != 'NOT OK'
      AND PARTNER_ACQUIRED != 'REJECTED'
      AND NET1_LBP != 'NOT OK'
      AND BCS_NET1 != 'NOT OK'
      AND BCS_NET1 != 'AWAIT SYNC'
      AND BCS_NET1 != 'A304'
      AND BCS_RF_INP != 'NOT OK'
      AND BCS_TX_INP != 'NOT OK'
      AND PARTNER_INP != 'NOT OK'
      AND PARTNER_INP != 'REJECTED'
AND NET1_A304 !='NOT OK'
      AND (
        COF_ACQ = 'BASE OK'
        OR COF_ACQ = 'NA'
      )
      AND NET1_LINK != 'NOT OK'
      AND NET1_LINK != 'END'
      AND NET1_LINK != 'BCS CHANGE'
      AND TXMN_INP != 'NOT OK'
      AND RADIO_INP != 'NOT OK'
      AND ACQ_PARTNER != 'NOT OK'
      AND RADIO_FUND != 'END'
      AND LOWER (DELETED) != 'yes'
      AND LOWER (LOCKEDD) != 'yes'";
  if ($_POST['partner']=='benchmark') {
    $query.=" AND CON='BENCHMARK'";
  }else if ($_POST['partner']=='techm') {
    $query.=" AND CON!='BENCHMARK'";
  }
  $query.="
    ) r ON z.TOTALS = r.TOTALS
    FULL OUTER JOIN (
      SELECT
        'TOTALS' AS TOTALS,
        COUNT (SITEID) AS COF_CON_BASE_TS
      FROM
        BSDS_RAFV2 T
      LEFT JOIN VW_POPR_CON ACQ ON T.RAFID = ACQ.RAFID
      LEFT JOIN RAF_HAS_BOQ BOQ ON BOQ.BOQ_RAFID=T.RAFID
      WHERE
        COF_CON = 'PARTNER OK' AND BOQ_RAFID IS NOT NULL
      AND (ACQ.POPR IS NOT NULL OR BUFFER=1 OR TYPE='New Indoor')
      AND CON_PARTNER != 'NOT OK'
      AND RADIO_FUND != 'NOT OK'
      AND RADIO_FUND != 'ON HOLD'
      AND RADIO_FUND != 'NOT FUNDED'
      AND RADIO_FUND != 'NO BUDGET'
      AND RADIO_FUND != 'END'
      AND TXMN_ACQUIRED != 'NOT OK'
      AND PARTNER_ACQUIRED != 'NOT OK'
      AND PARTNER_ACQUIRED != 'REJECTED'
      AND NET1_LBP != 'NOT OK'
      AND BCS_NET1 != 'NOT OK'
      AND BCS_NET1 != 'AWAIT SYNC'
      AND BCS_NET1 != 'A304'
      AND BCS_RF_INP != 'NOT OK'
      AND BCS_TX_INP != 'NOT OK'
      AND PARTNER_INP != 'NOT OK'
      AND PARTNER_INP != 'REJECTED'
      AND NET1_A304 !='NOT OK'
      AND (
        COF_ACQ = 'BASE OK'
        OR COF_ACQ = 'NA'
      )
      AND NET1_LINK != 'NOT OK'
      AND NET1_LINK != 'END'
      AND NET1_LINK != 'BCS CHANGE'
      AND TXMN_INP != 'NOT OK'
      AND RADIO_INP != 'NOT OK'
      AND ACQ_PARTNER != 'NOT OK'
      AND RADIO_FUND != 'END'
      AND LOWER (DELETED) != 'yes'
      AND LOWER (LOCKEDD) != 'yes'";
  if ($_POST['partner']=='benchmark') {
    $query.=" AND CON='BENCHMARK'";
  }else if ($_POST['partner']=='techm') {
    $query.=" AND CON!='BENCHMARK'";
  }
  $query.="
    ) sCOF ON z.TOTALS = sCOF.TOTALS
    FULL OUTER JOIN (
      SELECT
        'TOTALS' AS TOTALS,
        COUNT (SITEID) AS COF_CON_BASE_PM
      FROM
        BSDS_RAFV2 T
      LEFT JOIN VW_POPR_CON ACQ ON T .RAFID = ACQ.RAFID
      LEFT JOIN RAF_HAS_BOQ BOQ ON BOQ.BOQ_RAFID=T.RAFID
      WHERE
        ((COF_CON = 'PARTNER OK' AND BOQ_RAFID IS NULL) OR COF_CON = 'BASE TS OK')
      AND (ACQ.POPR IS NOT NULL OR BUFFER=1 OR TYPE='New Indoor')
      AND CON_PARTNER != 'NOT OK'
      AND RADIO_FUND != 'NOT OK'
      AND RADIO_FUND != 'ON HOLD'
      AND RADIO_FUND != 'NOT FUNDED'
      AND RADIO_FUND != 'NO BUDGET'
      AND RADIO_FUND != 'END'
      AND TXMN_ACQUIRED != 'NOT OK'
      AND PARTNER_ACQUIRED != 'NOT OK'
      AND PARTNER_ACQUIRED != 'REJECTED'
      AND NET1_LBP != 'NOT OK'
      AND BCS_NET1 != 'NOT OK'
      AND BCS_NET1 != 'AWAIT SYNC'
      AND BCS_NET1 != 'A304'
      AND BCS_RF_INP != 'NOT OK'
      AND BCS_TX_INP != 'NOT OK'
      AND PARTNER_INP != 'NOT OK'
      AND PARTNER_INP != 'REJECTED'
      AND NET1_A304 !='NOT OK'
      AND (
        COF_ACQ = 'BASE OK'
        OR COF_ACQ = 'NA'
      )
      AND NET1_LINK != 'NOT OK'
      AND NET1_LINK != 'END'
      AND NET1_LINK != 'BCS CHANGE'
      AND TXMN_INP != 'NOT OK'
      AND RADIO_INP != 'NOT OK'
      AND ACQ_PARTNER != 'NOT OK'
      AND RADIO_FUND != 'END'
      AND LOWER (DELETED) != 'yes'
      AND LOWER (LOCKEDD) != 'yes'";
  if ($_POST['partner']=='benchmark') {
    $query.=" AND CON='BENCHMARK'";
  }else if ($_POST['partner']=='techm') {
    $query.=" AND CON!='BENCHMARK'";
  }
  $query.="
    ) s ON z.TOTALS = s.TOTALS
    FULL OUTER JOIN (
      SELECT
        'TOTALS' AS TOTALS,
        COUNT (SITEID) AS PO_CON
      FROM
        BSDS_RAFV2 T
      LEFT JOIN VW_POPR_CON CON ON T .RAFID = CON.RAFID
      WHERE
        POPR IS NULL
      AND COF_CON = 'BASE OK'
      AND NET1_FUND != 'NOT OK' /*AND NET1_ACQUIRED!='NOT OK'*/
      AND CON_PARTNER != 'NOT OK'
      AND RADIO_FUND != 'NOT OK'
      AND RADIO_FUND != 'ON HOLD'
      AND RADIO_FUND != 'NO BUDGET'
      AND RADIO_FUND != 'NOT FUNDED'
      AND RADIO_FUND != 'END'
      AND TXMN_ACQUIRED != 'NOT OK'
      AND PARTNER_ACQUIRED != 'NOT OK'
      AND PARTNER_ACQUIRED != 'REJECTED'
      AND NET1_LBP != 'NOT OK'
      AND BCS_NET1 != 'NOT OK'
      AND BCS_NET1 != 'AWAIT SYNC'
      AND BCS_NET1 != 'A304'
      AND BCS_RF_INP != 'NOT OK'
      AND BCS_TX_INP != 'NOT OK'
      AND PARTNER_INP != 'NOT OK'
      AND PARTNER_INP != 'REJECTED'
AND NET1_A304 !='NOT OK'
      AND (
        COF_ACQ = 'BASE OK'
        OR COF_ACQ = 'NA'
      )
      AND NET1_LINK != 'NOT OK'
      AND NET1_LINK != 'END'
      AND NET1_LINK != 'BCS CHANGE'
      AND TXMN_INP != 'NOT OK'
      AND RADIO_INP != 'NOT OK'
      AND ACQ_PARTNER != 'NOT OK'
      AND RADIO_FUND != 'END'
      AND LOWER (DELETED) != 'yes'
      AND LOWER (LOCKEDD) != 'yes'";
  if ($_POST['partner']=='benchmark') {
    $query.=" AND CON='BENCHMARK'";
  }else if ($_POST['partner']=='techm') {
    $query.=" AND CON!='BENCHMARK'";
  }
  $query.="
    ) T ON z.TOTALS = T .TOTALS
    FULL OUTER JOIN (
      SELECT
        'TOTALS' AS TOTALS,
        COUNT (SITEID) AS PARTNER_RFPAC
      FROM
        BSDS_RAFV2 T
      LEFT JOIN VW_POPR_CON CON ON T .RAFID = CON.RAFID
      WHERE
        (
          PARTNER_RFPACK = 'NOT OK'
          OR PARTNER_RFPACK = 'REJECTED'
          OR PARTNER_RFPACK = 'AWAITING NET1'
          OR PARTNER_RFPACK = 'AWAITING SYNC'
        )
      AND POPR IS NOT NULL
      AND COF_CON = 'BASE OK'
      AND NET1_FUND != 'NOT OK' /* AND NET1_ACQUIRED!='NOT OK'*/
      AND CON_PARTNER != 'NOT OK'
      AND RADIO_FUND != 'NOT OK'
      AND RADIO_FUND != 'ON HOLD'
      AND RADIO_FUND != 'NO BUDGET'
      AND RADIO_FUND != 'NOT FUNDED'
      AND RADIO_FUND != 'END'
      AND TXMN_ACQUIRED != 'NOT OK'
      AND PARTNER_ACQUIRED != 'NOT OK'
      AND PARTNER_ACQUIRED != 'REJECTED'
      AND NET1_LBP != 'NOT OK'
      AND BCS_NET1 != 'NOT OK'
      AND BCS_NET1 != 'AWAIT SYNC'
      AND BCS_NET1 != 'A304'
      AND BCS_RF_INP != 'NOT OK'
      AND BCS_TX_INP != 'NOT OK'
      AND PARTNER_INP != 'NOT OK'
      AND PARTNER_INP != 'REJECTED'
AND NET1_A304 !='NOT OK'
      AND (
        COF_ACQ = 'BASE OK'
        OR COF_ACQ = 'NA'
      )
      AND NET1_LINK != 'NOT OK'
      AND NET1_LINK != 'END'
      AND NET1_LINK != 'BCS CHANGE'
      AND TXMN_INP != 'NOT OK'
      AND RADIO_INP != 'NOT OK'
      AND ACQ_PARTNER != 'NOT OK'
      AND RADIO_FUND != 'END'
      AND LOWER (DELETED) != 'yes'
      AND LOWER (LOCKEDD) != 'yes'";
  if ($_POST['partner']=='benchmark') {
    $query.=" AND CON='BENCHMARK'";
  }else if ($_POST['partner']=='techm') {
    $query.=" AND CON!='BENCHMARK'";
  }
  $query.="
    ) U ON z.TOTALS = U .TOTALS
    FULL OUTER JOIN (
      SELECT
        'TOTALS' AS TOTALS,
        COUNT (SITEID) AS RADIO_RFPAC
      FROM
        BSDS_RAFV2 T
      LEFT JOIN VW_POPR_CON CON ON T .RAFID = CON.RAFID
      WHERE
        (
          RF_PAC = 'NOT OK'
          OR RF_PAC = 'AWAITING SYNC'
          OR RF_PAC = 'OK'
        )
      AND PARTNER_RFPACK != 'NOT OK'
      AND PARTNER_RFPACK != 'REJECTED'
      AND POPR IS NOT NULL
      AND COF_CON = 'BASE OK'
      AND NET1_FUND != 'NOT OK' /* AND NET1_ACQUIRED!='NOT OK'*/
      AND CON_PARTNER != 'NOT OK'
      AND RADIO_FUND != 'NOT OK'
      AND RADIO_FUND != 'ON HOLD'
      AND RADIO_FUND != 'NO BUDGET'
      AND RADIO_FUND != 'NOT FUNDED'
      AND RADIO_FUND != 'END'
      AND TXMN_ACQUIRED != 'NOT OK'
      AND PARTNER_ACQUIRED != 'NOT OK'
      AND PARTNER_ACQUIRED != 'REJECTED'
      AND NET1_LBP != 'NOT OK'
      AND BCS_NET1 != 'NOT OK'
      AND BCS_NET1 != 'AWAIT SYNC'
      AND BCS_NET1 != 'A304'
      AND BCS_RF_INP != 'NOT OK'
      AND BCS_TX_INP != 'NOT OK'
      AND PARTNER_INP != 'NOT OK'
      AND PARTNER_INP != 'REJECTED'
AND NET1_A304 !='NOT OK'
      AND (
        COF_ACQ = 'BASE OK'
        OR COF_ACQ = 'NA'
      )
      AND NET1_LINK != 'NOT OK'
      AND NET1_LINK != 'END'
      AND NET1_LINK != 'BCS CHANGE'
      AND TXMN_INP != 'NOT OK'
      AND RADIO_INP != 'NOT OK'
      AND ACQ_PARTNER != 'NOT OK'
      AND RADIO_FUND != 'END'
      AND LOWER (DELETED) != 'yes'
      AND LOWER (LOCKEDD) != 'yes'";
  if ($_POST['partner']=='benchmark') {
    $query.=" AND CON='BENCHMARK'";
  }else if ($_POST['partner']=='techm') {
    $query.=" AND CON!='BENCHMARK'";
  }
  $query.="
    ) v ON z.TOTALS = v.TOTALS
    FULL OUTER JOIN (
      SELECT
        'TOTALS' AS TOTALS,
        COUNT (SITEID) AS VALREQ_REJECTED
      FROM
        BSDS_RAFV2 T
      LEFT JOIN VW_POPR_CON CON ON T .RAFID = CON.RAFID
      WHERE
        PARTNER_VALREQ = 'REJECTED'
      AND RF_PAC = 'OK'
      AND PARTNER_RFPACK != 'NOT OK'
      AND PARTNER_RFPACK != 'REJECTED'
      AND POPR IS NOT NULL
      AND COF_CON = 'BASE OK'
      AND NET1_FUND != 'NOT OK' /* AND NET1_ACQUIRED!='NOT OK'*/
      AND CON_PARTNER != 'NOT OK'
      AND RADIO_FUND != 'NOT OK'
      AND RADIO_FUND != 'ON HOLD'
      AND RADIO_FUND != 'NO BUDGET'
      AND RADIO_FUND != 'NOT FUNDED'
      AND RADIO_FUND != 'END'
      AND TXMN_ACQUIRED != 'NOT OK'
      AND PARTNER_ACQUIRED != 'NOT OK'
      AND PARTNER_ACQUIRED != 'REJECTED'
      AND NET1_LBP != 'NOT OK'
      AND BCS_NET1 != 'NOT OK'
      AND BCS_NET1 != 'AWAIT SYNC'
      AND BCS_NET1 != 'A304'
      AND BCS_RF_INP != 'NOT OK'
      AND BCS_TX_INP != 'NOT OK'
      AND PARTNER_INP != 'NOT OK'
      AND PARTNER_INP != 'REJECTED'
AND NET1_A304 !='NOT OK'
      AND (
        COF_ACQ = 'BASE OK'
        OR COF_ACQ = 'NA'
      )
      AND NET1_LINK != 'NOT OK'
      AND NET1_LINK != 'END'
      AND NET1_LINK != 'BCS CHANGE'
      AND TXMN_INP != 'NOT OK'
      AND RADIO_INP != 'NOT OK'
      AND ACQ_PARTNER != 'NOT OK'
      AND RADIO_FUND != 'END'
 AND (NET1_PAC!='NOT OK' OR NET1_FAC!='NOT OK')
      AND LOWER (DELETED) != 'yes'
      AND LOWER (LOCKEDD) != 'yes'";
  if ($_POST['partner']=='benchmark') {
    $query.=" AND CON='BENCHMARK'";
  }else if ($_POST['partner']=='techm') {
    $query.=" AND CON!='BENCHMARK'";
  }
  $query.="
    ) w ON z.TOTALS = w.TOTALS
    FULL OUTER JOIN (
      SELECT
        'TOTALS' AS TOTALS,
        COUNT (SITEID) AS VALREQ_MIS_MS_PAC
      FROM
        BSDS_RAFV2 T
      LEFT JOIN VW_POPR_CON CON ON T .RAFID = CON.RAFID
      WHERE
        PARTNER_VALREQ = 'MISSING MS FOR PAC'
      AND RF_PAC = 'OK'
      AND PARTNER_RFPACK != 'NOT OK'
      AND PARTNER_RFPACK != 'REJECTED'
      AND POPR IS NOT NULL
      AND COF_CON = 'BASE OK'
      AND NET1_FUND != 'NOT OK' /* AND NET1_ACQUIRED!='NOT OK'*/
      AND CON_PARTNER != 'NOT OK'
      AND RADIO_FUND != 'NOT OK'
      AND RADIO_FUND != 'ON HOLD'
      AND RADIO_FUND != 'NO BUDGET'
      AND RADIO_FUND != 'NOT FUNDED'
      AND RADIO_FUND != 'END'
      AND TXMN_ACQUIRED != 'NOT OK'
      AND PARTNER_ACQUIRED != 'NOT OK'
      AND PARTNER_ACQUIRED != 'REJECTED'
      AND NET1_LBP != 'NOT OK'
      AND BCS_NET1 != 'NOT OK'
      AND BCS_NET1 != 'AWAIT SYNC'
      AND BCS_NET1 != 'A304'
      AND BCS_RF_INP != 'NOT OK'
      AND BCS_TX_INP != 'NOT OK'
      AND PARTNER_INP != 'NOT OK'
      AND PARTNER_INP != 'REJECTED'
AND NET1_A304 !='NOT OK'
      AND (
        COF_ACQ = 'BASE OK'
        OR COF_ACQ = 'NA'
      )
      AND NET1_LINK != 'NOT OK'
      AND NET1_LINK != 'END'
      AND NET1_LINK != 'BCS CHANGE'
      AND TXMN_INP != 'NOT OK'
      AND RADIO_INP != 'NOT OK'
      AND ACQ_PARTNER != 'NOT OK'
      AND RADIO_FUND != 'END'
 AND (NET1_PAC!='NOT OK' OR NET1_FAC!='NOT OK')
      AND LOWER (DELETED) != 'yes'
      AND LOWER (LOCKEDD) != 'yes'";
  if ($_POST['partner']=='benchmark') {
    $query.=" AND CON='BENCHMARK'";
  }else if ($_POST['partner']=='techm') {
    $query.=" AND CON!='BENCHMARK'";
  }
  $query.="
    ) x ON z.TOTALS = x.TOTALS
    FULL OUTER JOIN (
      SELECT
        'TOTALS' AS TOTALS,
        COUNT (SITEID) AS VALREQ_MIS_DOCS_PAC
      FROM
        BSDS_RAFV2 T
      LEFT JOIN VW_POPR_CON CON ON T .RAFID = CON.RAFID
      WHERE
        PARTNER_VALREQ = 'MISSING DOCS FOR PAC'
      AND RF_PAC = 'OK'
      AND PARTNER_RFPACK != 'NOT OK'
      AND PARTNER_RFPACK != 'REJECTED'
      AND POPR IS NOT NULL
      AND COF_CON = 'BASE OK'
      AND NET1_FUND != 'NOT OK' /* AND NET1_ACQUIRED!='NOT OK'*/
      AND CON_PARTNER != 'NOT OK'
      AND RADIO_FUND != 'NOT OK'
      AND RADIO_FUND != 'ON HOLD'
      AND RADIO_FUND != 'NO BUDGET'
      AND RADIO_FUND != 'NOT FUNDED'
      AND RADIO_FUND != 'END'
      AND TXMN_ACQUIRED != 'NOT OK'
      AND PARTNER_ACQUIRED != 'NOT OK'
      AND PARTNER_ACQUIRED != 'REJECTED'
      AND NET1_LBP != 'NOT OK'
      AND BCS_NET1 != 'NOT OK'
      AND BCS_NET1 != 'AWAIT SYNC'
      AND BCS_NET1 != 'A304'
      AND BCS_RF_INP != 'NOT OK'
      AND BCS_TX_INP != 'NOT OK'
      AND PARTNER_INP != 'NOT OK'
      AND PARTNER_INP != 'REJECTED'
AND NET1_A304 !='NOT OK'
      AND (
        COF_ACQ = 'BASE OK'
        OR COF_ACQ = 'NA'
      )
      AND NET1_LINK != 'NOT OK'
      AND NET1_LINK != 'END'
      AND NET1_LINK != 'BCS CHANGE'
      AND TXMN_INP != 'NOT OK'
      AND RADIO_INP != 'NOT OK'
      AND ACQ_PARTNER != 'NOT OK'
      AND RADIO_FUND != 'END'
 AND (NET1_PAC!='NOT OK' OR NET1_FAC!='NOT OK')
      AND LOWER (DELETED) != 'yes'";
  if ($_POST['partner']=='benchmark') {
    $query.=" AND CON='BENCHMARK'";
  }else if ($_POST['partner']=='techm') {
    $query.=" AND CON!='BENCHMARK'";
  }
  $query.="
      AND LOWER (LOCKEDD) != 'yes'
    ) y ON z.TOTALS = y.TOTALS
    FULL OUTER JOIN (
      SELECT
        'TOTALS' AS TOTALS,
        COUNT (SITEID) AS VALREQ_READY_PAC
      FROM
        BSDS_RAFV2 T
      LEFT JOIN VW_POPR_CON CON ON T .RAFID = CON.RAFID
      WHERE
        PARTNER_VALREQ = 'READY FOR PAC'
      AND RF_PAC = 'OK'
      AND PARTNER_RFPACK != 'NOT OK'
      AND PARTNER_RFPACK != 'REJECTED'
      AND POPR IS NOT NULL
      AND COF_CON = 'BASE OK'
      AND NET1_FUND != 'NOT OK' /* AND NET1_ACQUIRED!='NOT OK'*/
      AND CON_PARTNER != 'NOT OK'
      AND RADIO_FUND != 'NOT OK'
      AND RADIO_FUND != 'ON HOLD'
      AND RADIO_FUND != 'NO BUDGET'
      AND RADIO_FUND != 'NOT FUNDED'
      AND RADIO_FUND != 'END'
      AND TXMN_ACQUIRED != 'NOT OK'
      AND PARTNER_ACQUIRED != 'NOT OK'
      AND PARTNER_ACQUIRED != 'REJECTED'
      AND NET1_LBP != 'NOT OK'
      AND BCS_NET1 != 'NOT OK'
      AND BCS_NET1 != 'AWAIT SYNC'
      AND BCS_NET1 != 'A304'
      AND BCS_RF_INP != 'NOT OK'
      AND BCS_TX_INP != 'NOT OK'
      AND PARTNER_INP != 'NOT OK'
      AND PARTNER_INP != 'REJECTED'
AND NET1_A304 !='NOT OK'
      AND (
        COF_ACQ = 'BASE OK'
        OR COF_ACQ = 'NA'
      )
      AND NET1_LINK != 'NOT OK'
      AND NET1_LINK != 'END'
      AND NET1_LINK != 'BCS CHANGE'
      AND TXMN_INP != 'NOT OK'
      AND RADIO_INP != 'NOT OK'
      AND ACQ_PARTNER != 'NOT OK'
      AND RADIO_FUND != 'END'
 AND (NET1_PAC!='NOT OK' OR NET1_FAC!='NOT OK')
      AND LOWER (DELETED) != 'yes'
      AND LOWER (LOCKEDD) != 'yes'";
  if ($_POST['partner']=='benchmark') {
    $query.=" AND CON='BENCHMARK'";
  }else if ($_POST['partner']=='techm') {
    $query.=" AND CON!='BENCHMARK'";
  }
  $query.="
    ) aa ON z.TOTALS = aa.TOTALS
    FULL OUTER JOIN (
      SELECT
        'TOTALS' AS TOTALS,
        COUNT (SITEID) AS VALREQ_MIS_MS_DOCS_PAC
      FROM
        BSDS_RAFV2 T
      LEFT JOIN VW_POPR_CON CON ON T .RAFID = CON.RAFID
      WHERE
        PARTNER_VALREQ = 'MISSING MS&DOCS FOR PAC'
      AND RF_PAC = 'OK'
      AND PARTNER_RFPACK != 'NOT OK'
      AND PARTNER_RFPACK != 'REJECTED'
      AND POPR IS NOT NULL
      AND COF_CON = 'BASE OK'
      AND NET1_FUND != 'NOT OK' /* AND NET1_ACQUIRED!='NOT OK'*/
      AND CON_PARTNER != 'NOT OK'
      AND RADIO_FUND != 'NOT OK'
      AND RADIO_FUND != 'ON HOLD'
      AND RADIO_FUND != 'NO BUDGET'
      AND RADIO_FUND != 'NOT FUNDED'
      AND RADIO_FUND != 'END'
      AND TXMN_ACQUIRED != 'NOT OK'
      AND PARTNER_ACQUIRED != 'NOT OK'
      AND PARTNER_ACQUIRED != 'REJECTED'
      AND NET1_LBP != 'NOT OK'
      AND BCS_NET1 != 'NOT OK'
      AND BCS_NET1 != 'AWAIT SYNC'
      AND BCS_NET1 != 'A304'
      AND BCS_RF_INP != 'NOT OK'
      AND BCS_TX_INP != 'NOT OK'
      AND PARTNER_INP != 'NOT OK'
      AND PARTNER_INP != 'REJECTED'
AND NET1_A304 !='NOT OK'
      AND (
        COF_ACQ = 'BASE OK'
        OR COF_ACQ = 'NA'
      )
      AND NET1_LINK != 'NOT OK'
      AND NET1_LINK != 'END'
      AND NET1_LINK != 'BCS CHANGE'
      AND TXMN_INP != 'NOT OK'
      AND RADIO_INP != 'NOT OK'
      AND ACQ_PARTNER != 'NOT OK'
      AND RADIO_FUND != 'END'
 AND (NET1_PAC!='NOT OK' OR NET1_FAC!='NOT OK')
      AND LOWER (DELETED) != 'yes'
      AND LOWER (LOCKEDD) != 'yes'";
  if ($_POST['partner']=='benchmark') {
    $query.=" AND CON='BENCHMARK'";
  }else if ($_POST['partner']=='techm') {
    $query.=" AND CON!='BENCHMARK'";
  }
  $query.="
    ) ab ON z.TOTALS = ab.TOTALS
    FULL OUTER JOIN (
      SELECT
        'TOTALS' AS TOTALS,
        COUNT (SITEID) AS VALREQ_MIS_MS_FAC
      FROM
        BSDS_RAFV2 T
      LEFT JOIN VW_POPR_CON CON ON T .RAFID = CON.RAFID
      WHERE
        PARTNER_VALREQ = 'MISSING MS FOR FAC'
      AND RF_PAC = 'OK'
      AND PARTNER_RFPACK != 'NOT OK'
      AND PARTNER_RFPACK != 'REJECTED'
      AND POPR IS NOT NULL
      AND COF_CON = 'BASE OK'
      AND NET1_FUND != 'NOT OK' /* AND NET1_ACQUIRED!='NOT OK'*/
      AND CON_PARTNER != 'NOT OK'
      AND RADIO_FUND != 'NOT OK'
      AND RADIO_FUND != 'ON HOLD'
      AND RADIO_FUND != 'NO BUDGET'
      AND RADIO_FUND != 'NOT FUNDED'
      AND RADIO_FUND != 'END'
      AND TXMN_ACQUIRED != 'NOT OK'
      AND PARTNER_ACQUIRED != 'NOT OK'
      AND PARTNER_ACQUIRED != 'REJECTED'
      AND NET1_LBP != 'NOT OK'
      AND BCS_NET1 != 'NOT OK'
      AND BCS_NET1 != 'AWAIT SYNC'
      AND BCS_NET1 != 'A304'
      AND BCS_RF_INP != 'NOT OK'
      AND BCS_TX_INP != 'NOT OK'
      AND PARTNER_INP != 'NOT OK'
      AND PARTNER_INP != 'REJECTED'
AND NET1_A304 !='NOT OK'
      AND (
        COF_ACQ = 'BASE OK'
        OR COF_ACQ = 'NA'
      )
      AND NET1_LINK != 'NOT OK'
      AND NET1_LINK != 'END'
      AND NET1_LINK != 'BCS CHANGE'
      AND TXMN_INP != 'NOT OK'
      AND RADIO_INP != 'NOT OK'
      AND ACQ_PARTNER != 'NOT OK'
      AND RADIO_FUND != 'END'
 AND (NET1_PAC!='NOT OK' OR NET1_FAC!='NOT OK')
      AND LOWER (DELETED) != 'yes'
      AND LOWER (LOCKEDD) != 'yes'";
  if ($_POST['partner']=='benchmark') {
    $query.=" AND CON='BENCHMARK'";
  }else if ($_POST['partner']=='techm') {
    $query.=" AND CON!='BENCHMARK'";
  }
  $query.="
    ) ac ON z.TOTALS = ac.TOTALS
    FULL OUTER JOIN (
      SELECT
        'TOTALS' AS TOTALS,
        COUNT (SITEID) AS VALREQ_MIS_DOCS_FAC
      FROM
        BSDS_RAFV2 T
      LEFT JOIN VW_POPR_CON CON ON T .RAFID = CON.RAFID
      WHERE
        PARTNER_VALREQ = 'MISSING DOCS FOR FAC'
      AND RF_PAC = 'OK'
      AND PARTNER_RFPACK != 'NOT OK'
      AND PARTNER_RFPACK != 'REJECTED'
      AND POPR IS NOT NULL
      AND COF_CON = 'BASE OK'
      AND NET1_FUND != 'NOT OK' /* AND NET1_ACQUIRED!='NOT OK'*/
      AND CON_PARTNER != 'NOT OK'
      AND RADIO_FUND != 'NOT OK'
      AND RADIO_FUND != 'ON HOLD'
      AND RADIO_FUND != 'NO BUDGET'
      AND RADIO_FUND != 'NOT FUNDED'
      AND RADIO_FUND != 'END'
      AND TXMN_ACQUIRED != 'NOT OK'
      AND PARTNER_ACQUIRED != 'NOT OK'
      AND PARTNER_ACQUIRED != 'REJECTED'
      AND NET1_LBP != 'NOT OK'
      AND BCS_NET1 != 'NOT OK'
      AND BCS_NET1 != 'AWAIT SYNC'
      AND BCS_NET1 != 'A304'
      AND BCS_RF_INP != 'NOT OK'
      AND BCS_TX_INP != 'NOT OK'
      AND PARTNER_INP != 'NOT OK'
      AND PARTNER_INP != 'REJECTED'
AND NET1_A304 !='NOT OK'
      AND (
        COF_ACQ = 'BASE OK'
        OR COF_ACQ = 'NA'
      )
      AND NET1_LINK != 'NOT OK'
      AND NET1_LINK != 'END'
      AND NET1_LINK != 'BCS CHANGE'
      AND TXMN_INP != 'NOT OK'
      AND RADIO_INP != 'NOT OK'
      AND ACQ_PARTNER != 'NOT OK'
      AND RADIO_FUND != 'END'
 AND (NET1_PAC!='NOT OK' OR NET1_FAC!='NOT OK')
      AND LOWER (DELETED) != 'yes'
      AND LOWER (LOCKEDD) != 'yes'";
  if ($_POST['partner']=='benchmark') {
    $query.=" AND CON='BENCHMARK'";
  }else if ($_POST['partner']=='techm') {
    $query.=" AND CON!='BENCHMARK'";
  }
  $query.="
    ) ad ON z.TOTALS = ad.TOTALS
    FULL OUTER JOIN (
      SELECT
        'TOTALS' AS TOTALS,
        COUNT (SITEID) AS VALREQ_READY_FAC
      FROM
        BSDS_RAFV2 T
      LEFT JOIN VW_POPR_CON CON ON T .RAFID = CON.RAFID
      WHERE
        PARTNER_VALREQ = 'READY FOR FAC'
      AND RF_PAC = 'OK'
      AND PARTNER_RFPACK != 'NOT OK'
      AND PARTNER_RFPACK != 'REJECTED'
      AND POPR IS NOT NULL
      AND COF_CON = 'BASE OK'
      AND NET1_FUND != 'NOT OK' /* AND NET1_ACQUIRED!='NOT OK'*/
      AND CON_PARTNER != 'NOT OK'
      AND RADIO_FUND != 'NOT OK'
      AND RADIO_FUND != 'ON HOLD'
      AND RADIO_FUND != 'NO BUDGET'
      AND RADIO_FUND != 'NOT FUNDED'
      AND RADIO_FUND != 'END'
      AND TXMN_ACQUIRED != 'NOT OK'
      AND PARTNER_ACQUIRED != 'NOT OK'
      AND PARTNER_ACQUIRED != 'REJECTED'
      AND NET1_LBP != 'NOT OK'
      AND BCS_NET1 != 'NOT OK'
      AND BCS_NET1 != 'AWAIT SYNC'
      AND BCS_NET1 != 'A304'
      AND BCS_RF_INP != 'NOT OK'
      AND BCS_TX_INP != 'NOT OK'
      AND PARTNER_INP != 'NOT OK'
      AND PARTNER_INP != 'REJECTED'
AND NET1_A304 !='NOT OK'
      AND (
        COF_ACQ = 'BASE OK'
        OR COF_ACQ = 'NA'
      )
      AND NET1_LINK != 'NOT OK'
      AND NET1_LINK != 'END'
      AND NET1_LINK != 'BCS CHANGE'
      AND TXMN_INP != 'NOT OK'
      AND RADIO_INP != 'NOT OK'
      AND ACQ_PARTNER != 'NOT OK'
      AND RADIO_FUND != 'END'
      AND LOWER (DELETED) != 'yes'
      AND LOWER (LOCKEDD) != 'yes'";
  if ($_POST['partner']=='benchmark') {
    $query.=" AND CON='BENCHMARK'";
  }else if ($_POST['partner']=='techm') {
    $query.=" AND CON!='BENCHMARK'";
  }
  $query.="
    ) ae ON z.TOTALS = ae.TOTALS
    FULL OUTER JOIN (
      SELECT
        'TOTALS' AS TOTALS,
        COUNT (SITEID) AS VALREQ_READY_PAC_FAC
      FROM
        BSDS_RAFV2 T
      LEFT JOIN VW_POPR_CON CON ON T .RAFID = CON.RAFID
      WHERE
        PARTNER_VALREQ = 'READY FOR PAC&FAC'
      AND RF_PAC = 'OK'
      AND PARTNER_RFPACK != 'NOT OK'
      AND PARTNER_RFPACK != 'REJECTED'
      AND POPR IS NOT NULL
      AND COF_CON = 'BASE OK'
      AND NET1_FUND != 'NOT OK' /* AND NET1_ACQUIRED!='NOT OK'*/
      AND CON_PARTNER != 'NOT OK'
      AND RADIO_FUND != 'NOT OK'
      AND RADIO_FUND != 'ON HOLD'
      AND RADIO_FUND != 'NO BUDGET'
      AND RADIO_FUND != 'NOT FUNDED'
      AND RADIO_FUND != 'END'
      AND TXMN_ACQUIRED != 'NOT OK'
      AND PARTNER_ACQUIRED != 'NOT OK'
      AND PARTNER_ACQUIRED != 'REJECTED'
      AND NET1_LBP != 'NOT OK'
      AND BCS_NET1 != 'NOT OK'
      AND BCS_NET1 != 'AWAIT SYNC'
      AND BCS_NET1 != 'A304'
      AND BCS_RF_INP != 'NOT OK'
      AND BCS_TX_INP != 'NOT OK'
      AND PARTNER_INP != 'NOT OK'
      AND PARTNER_INP != 'REJECTED'
AND NET1_A304 !='NOT OK'
      AND (
        COF_ACQ = 'BASE OK'
        OR COF_ACQ = 'NA'
      )
      AND NET1_LINK != 'NOT OK'
      AND NET1_LINK != 'END'
      AND NET1_LINK != 'BCS CHANGE'
      AND TXMN_INP != 'NOT OK'
      AND RADIO_INP != 'NOT OK'
      AND ACQ_PARTNER != 'NOT OK'
      AND RADIO_FUND != 'END'
      AND LOWER (DELETED) != 'yes'
      AND LOWER (LOCKEDD) != 'yes'";
  if ($_POST['partner']=='benchmark') {
    $query.=" AND CON='BENCHMARK'";
  }else if ($_POST['partner']=='techm') {
    $query.=" AND CON!='BENCHMARK'";
  }
  $query.="
    ) af ON z.TOTALS = af.TOTALS
    FULL OUTER JOIN (
      SELECT
        'TOTALS' AS TOTALS,
        COUNT (SITEID) AS NET1_FAC
      FROM
        BSDS_RAFV2 T
      LEFT JOIN VW_POPR_CON CON ON T .RAFID = CON.RAFID
      WHERE
        NET1_FAC = 'NOT OK'
      AND (
        PARTNER_VALREQ = 'READY FOR PAC&FAC'
        OR PARTNER_VALREQ = 'READY FOR FAC'
      )
      AND RF_PAC = 'OK'
      AND PARTNER_RFPACK != 'NOT OK'
      AND PARTNER_RFPACK != 'REJECTED'
      AND POPR IS NOT NULL
      AND COF_CON = 'BASE OK'
      AND NET1_FUND != 'NOT OK' /* AND NET1_ACQUIRED!='NOT OK'*/
      AND CON_PARTNER != 'NOT OK'
      AND RADIO_FUND != 'NOT OK'
      AND RADIO_FUND != 'ON HOLD'
      AND RADIO_FUND != 'NO BUDGET'
      AND RADIO_FUND != 'NOT FUNDED'
      AND RADIO_FUND != 'END'
      AND TXMN_ACQUIRED != 'NOT OK'
      AND PARTNER_ACQUIRED != 'NOT OK'
      AND PARTNER_ACQUIRED != 'REJECTED'
      AND NET1_LBP != 'NOT OK'
      AND BCS_NET1 != 'NOT OK'
      AND BCS_NET1 != 'AWAIT SYNC'
      AND BCS_NET1 != 'A304'
      AND BCS_RF_INP != 'NOT OK'
      AND BCS_TX_INP != 'NOT OK'
      AND PARTNER_INP != 'NOT OK'
      AND PARTNER_INP != 'REJECTED'
AND NET1_A304 !='NOT OK'
      AND (
        COF_ACQ = 'BASE OK'
        OR COF_ACQ = 'NA'
      )
      AND NET1_LINK != 'NOT OK'
      AND NET1_LINK != 'END'
      AND NET1_LINK != 'BCS CHANGE'
      AND TXMN_INP != 'NOT OK'
      AND RADIO_INP != 'NOT OK'
      AND ACQ_PARTNER != 'NOT OK'
      AND RADIO_FUND != 'END'
      AND LOWER (DELETED) != 'yes'
      AND LOWER (LOCKEDD) != 'yes'";
  if ($_POST['partner']=='benchmark') {
    $query.=" AND CON='BENCHMARK'";
  }else if ($_POST['partner']=='techm') {
    $query.=" AND CON!='BENCHMARK'";
  }
  $query.="
    ) ag ON z.TOTALS = ag.TOTALS
    FULL OUTER JOIN (
      SELECT
        'TOTALS' AS TOTALS,
        COUNT (SITEID) AS NET1_PAC
      FROM
        BSDS_RAFV2 T
      LEFT JOIN VW_POPR_CON CON ON T .RAFID = CON.RAFID
      WHERE
        NET1_PAC = 'NOT OK'
      AND (
        PARTNER_VALREQ = 'READY FOR PAC&FAC'
        OR PARTNER_VALREQ = 'READY FOR PAC'
      )
      AND RF_PAC = 'OK'
      AND PARTNER_RFPACK != 'NOT OK'
      AND PARTNER_RFPACK != 'REJECTED'
      AND POPR IS NOT NULL
      AND COF_CON = 'BASE OK'
      AND NET1_FUND != 'NOT OK' /* AND NET1_ACQUIRED!='NOT OK'*/
      AND CON_PARTNER != 'NOT OK'
      AND RADIO_FUND != 'NOT OK'
      AND RADIO_FUND != 'ON HOLD'
      AND RADIO_FUND != 'NO BUDGET'
      AND RADIO_FUND != 'NOT FUNDED'
      AND RADIO_FUND != 'END'
      AND TXMN_ACQUIRED != 'NOT OK'
      AND PARTNER_ACQUIRED != 'NOT OK'
      AND PARTNER_ACQUIRED != 'REJECTED'
      AND NET1_LBP != 'NOT OK'
      AND BCS_NET1 != 'NOT OK'
      AND BCS_NET1 != 'AWAIT SYNC'
      AND BCS_NET1 != 'A304'
      AND BCS_RF_INP != 'NOT OK'
      AND BCS_TX_INP != 'NOT OK'
      AND PARTNER_INP != 'NOT OK'
      AND PARTNER_INP != 'REJECTED'
AND NET1_A304 !='NOT OK'
      AND (
        COF_ACQ = 'BASE OK'
        OR COF_ACQ = 'NA'
      )
      AND NET1_LINK != 'NOT OK'
      AND NET1_LINK != 'END'
      AND NET1_LINK != 'BCS CHANGE'
      AND TXMN_INP != 'NOT OK'
      AND RADIO_INP != 'NOT OK'
      AND ACQ_PARTNER != 'NOT OK'
      AND RADIO_FUND != 'END'
      AND LOWER (DELETED) != 'yes'
      AND LOWER (LOCKEDD) != 'yes'";
  if ($_POST['partner']=='benchmark') {
    $query.=" AND CON='BENCHMARK'";
  }else if ($_POST['partner']=='techm') {
    $query.=" AND CON!='BENCHMARK'";
  }
  $query.="
    ) ah ON z.TOTALS = ah.TOTALS
  )";
